### ISSUE TITLE
Audit repo (Code quality)

### ISSUE THREAD

**Issue by bwrsandman** [OCA/account-financial-reporting#10]
The modules in this repo need to be reviewed. There are many instances where the code can be cleaned up. Here is a small list.
- [ ] Long, indented functions
- [ ] Missing context propagations
- [ ] Non-english comments
- [ ] Non-english/non-translatable strings to the end-user
- [ ] Non-english variable names
- [ ] Coverage needs to be increased
- [ ] Duplicated code which can be factored
- [ ] A lot of commented out code

**Comment by pedrobaeza** [comment]
Closing as this has been handled in new versions.
