### ISSUE TITLE
Export data to Excel

### ISSUE THREAD

**Issue by jarodrig00** [OCA/account-financial-reporting#1022]
## Module
account-financial-reporting

## Describe the bug
When I ty to export to Excel, I have this error: TypeError: get_report_xlsx() missing 3 required positional arguments: 'model', 'options', and 'output_format' - - -

## To Reproduce
1. Choose any financial report, click on Export to XLSX
**Affected versions**: 14

1. Select balance
2. Click on Export to XLS
3.

**Expected behavior**
I what to get Excel for report selected

**Additional context**

**Comment by pedrobaeza** [comment]
Is this reproducible on the runboat infrastructure (with the button Runbot | Try me)?

**Comment by jarodrig00** [comment]
No,

**Comment by pedrobaeza** [comment]
Then I'm afraid it's something on your end. Try to update your code, or check if there's extra modules that breaks it.
