### ISSUE TITLE
[14.0] account-financial-reporting (14.0.3.8.1) - rendering the template account_financial_report.report_trial_balance_line 

### ISSUE THREAD

**Issue by whotopia** [OCA/account-financial-reporting#1053]
Seeing the following when running OCA reports  Trial Balance .   This only started recently (I am thinking due to an upgrade of this module).     My organization is in CHF, and we have bank accounts in 4 currencies.   The error comes when we ask the OCA Trial Balance to "Show Foreign Currecy".   Anyone have any suggestions?

Template fallback
An error occured while rendering the template account_financial_report.report_trial_balance_line.

If this error is caused by a change of yours in the templates, you have the possibility to reset the template to its factory settings.

account_financial_report.report_trial_balance_line
 
XXXX

Error message:
Error to render compiling AST
AttributeError: 'int' object has no attribute 'decimal_places'
Template: account_financial_report.report_trial_balance_line
Path: `/t/div/t[3]/t[1]/t/t/div/span/t`
Node: `<t t-esc="balance['initial_currency_balance']" t-options="{'widget': 'monetary', 'display_currency': balance['currency_id']}"/>`
                                
The error occured while rendering the template account_financial_report.report_trial_balance_line and evaluating the following expression: `<t t-esc="balance['initial_currency_balance']" t-options="{'widget': 'monetary', 'display_currency': balance['currency_id']}"/>`

**Comment by pedrobaeza** [comment]
I would say you don't have the latest source code of the module. Please check.

**Comment by whotopia** [comment]
I double checked.   For Trial Balance, whenever I tick the "Show Foreign Currency"  it causes the error.  In the interim I have

1. Updated odoo to latest OCB
2. Cleared out sessions
3. run an update of all modules for the database
4. Ran a 'regenerate asset bundles'

Here is the full error message:
![Screenshot 2023-07-23 at 17 03 53](https://github.com/OCA/account-financial-reporting/assets/9039050/0bd5eb96-1662-4754-b2d6-b0001c15f324)

![Screenshot 2023-07-23 at 17 02 10](https://github.com/OCA/account-financial-reporting/assets/9039050/3e66c8d7-5bf4-4e25-9ec9-d407fac317be)

![Screenshot 2023-07-23 at 17 02 28](https://github.com/OCA/account-financial-reporting/assets/9039050/f45c63d2-243a-4e47-8d92-09b463f70dfa)

![Screenshot 2023-07-23 at 17 02 40](https://github.com/OCA/account-financial-reporting/assets/9039050/ebb6ac99-b030-4a50-9b1a-bf9fc39b6234)

**Comment by whotopia** [comment]
> I would say you don't have the latest source code of the module. Please check.

See above.  Any thoughts?

**Comment by pedrobaeza** [comment]
The latest source code you have to obtain is not OCB, but this module's source code. You can also check if the problem is reproducible in runboat.

**Comment by whotopia** [comment]
> The latest source code you have to obtain is not OCB, but this module's source code. You can also check if the problem is reproducible in runboat.

I know.  I am running latest source code for the module, and using the OCB Odoo 14 code (not the one from Odoo.com)  

As you suggested, I have also tested this on Runboat and am able to reproduce the exact same issue:

http://oca-account-financial-reporting-14-0-3623c7a2124c.runboat.odoo-community.org/web?debug=1#action=account_financial_report.client_action&cids=&menu_id=106

![Screenshot 2023-07-24 at 12 00 20](https://github.com/OCA/account-financial-reporting/assets/9039050/681512a2-7463-4ed4-88eb-9e1d65271407)

In this instance I created a second bank account in EUR with EUR based Journal, EUR Bank Account GL, EUR Suspense account GL,  EUR Outstanding Receipts, EUR Outstanding Payments.  And of course added a couple of journal entities due to sales/purchases.

**Comment by pedrobaeza** [comment]
@victoralmau can you take a look?

**Comment by whotopia** [comment]
I installed the patched branch.  De-installed and reinstalled addon, regenerated asset bundles, and restarted.  

Still have the same issue.
![Screenshot 2023-07-25 at 16 57 12](https://github.com/OCA/account-financial-reporting/assets/9039050/ce9568e1-ea3c-4613-8556-bebc834dec66)

![Screenshot 2023-07-25 at 17 10 28](https://github.com/OCA/account-financial-reporting/assets/9039050/025ac27f-da7c-427f-b526-ffc0b1332847)
