### ISSUE TITLE
[16.0] General Ledger & Journal Ledger Expected singleton: ir.actions.report account_financial_report

### ISSUE THREAD

**Issue by Gadero5565** [OCA/account-financial-reporting#1060]
return super(IrActionsReport, self.with_context(REPORT_ID=self.search([('report_name', '=', report_ref)]).id))._render_qweb_html(report_ref, docids, data=data)
  File "/opt/odoo16/odoo16-server/odoo/fields.py", line 5067, in __get__
    raise ValueError("Expected singleton: %s" % record)
ValueError: Expected singleton: ir.actions.report(561, 560)

**Comment by pedrobaeza** [comment]
Steps to reproduce the problem?

**Comment by Gadero5565** [comment]
It's happenenig in general ledger  & journal report when trying to view the report or print it

**Comment by pedrobaeza** [comment]
That's not enough information. Please try on runboat instance and detail all the steps made to get to that.
