### ISSUE TITLE
[14.0][mis_builder_cash_flow] How is the mis.cash_flow init() function triggered?

### ISSUE THREAD

**Issue by stephansainleger** [OCA/account-financial-reporting#1072]
Hi!

I am currently working on the Odoo OCA add-on **MIS Builder** and **MIS Builder Cash Flow** : my goal is to add new filters in the `mis.builder.instance` and `mis.builder.instance.period` models that can be applied on `mis.cash_flow` entries. I would like to inherit the model `mis.cash_flow` so that I can overload the [init() function](https://github.com/OCA/account-financial-reporting/blob/14.0/mis_builder_cash_flow/report/mis_cash_flow.py#L78). But I don't understand when we go through this `init()` function :

- in debug mode I do not manage to go through
- I do not find any call to an `init()` function in the add-on **MIS Builder**, that can trigger a source model.

Could you please help me on that challenge?
Thanks for your attention!
Stéphan

**Comment by gdgellatly** [comment]
init is an odoo core method that is called when you set autoinit to False. Generally used for SQL views. It is in lots of places in Odoo code. It is called whenever you load the view.

**Comment by stephansainleger** [comment]
Thanks a lot @gdgellatly for your answer :-) Issue can be closed!
