### ISSUE TITLE
[16][account_financial_report] - Show Partner Details option does not display line with empty partners making the totals of the report inconsistent

### ISSUE THREAD

**Issue by florian-dacosta** [OCA/account-financial-reporting#1097]
With module account_financial_report, when printing the trial balance with the option "show partner details", the lines with no partner are not displayed, but are still counted for into the totals.

![balance_wizard](https://github.com/OCA/account-financial-reporting/assets/5393860/832df409-c8b9-48a6-abaa-f160ff742bfe)

![balance](https://github.com/OCA/account-financial-reporting/assets/5393860/4a78bbed-2678-48db-8e30-a6f389cf1cc6)

We can see that we have 0 lines with credit but the total is 100, it is very confusing. This is because I have created an accounting item for this account with no partner.

Before (I am not sure until when/which version) we has a line with the value "No partner allocated".
This way the total of the report  was consistent with the sum of all lines.
I am not sure if this behavior was removed on purpose or not and for which reason, but, if we don't want to display this "No partner allocated" line, I guess we'd want to remove the balance/credit/debit of these line without partner from the totals.

I personally liked the "No partner allocated" behavior and could not find why it was removed.

Anyway, I could try to fix it one way or another (adding the No partner allocated line or removing the no partner amounts from totals) but first I need to be sure on the right way to go

What do you think @alexis-via @pedrobaeza @JordiBForgeFlow

**Comment by pedrobaeza** [comment]
OK, go ahead with the code.
