### ISSUE TITLE
PDF reports are not aligned properly

### ISSUE THREAD

**Issue by arunsak04** [OCA/account-financial-reporting#1118]
I have installed the OCA financial report  addon in odoo 10v when i am trying to download the pdf reports its not aligned correctly you can see in the pic below
![Screenshot 2024-03-07 113506](https://github.com/OCA/account-financial-reporting/assets/128994108/ed8dd61b-00a8-47d6-a6c6-c18b27587f2c)

## Module
The name of the module that has a bug.
account_financial_report_qweb

## Describe the bug
the pdf report alignment is not proper

## To Reproduce
**Affected versions**:
odoo 10v 
1.Go to reports in the account_financial_report 
2.Clear the bug for all the PDF reports

**Expected behavior**
The PDF report should has columns and rows see the picture
**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by pedrobaeza** [comment]
This is a problem of your deployment, not a problem of the module. Please check report.url value in your system parameters, and ask for more help in the Odoo forums.
