### ISSUE TITLE
[16.0][Account_financial_reporting] General ledger doesn´t group by taxes

### ISSUE THREAD

**Issue by Jesarregui** [OCA/account-financial-reporting#1135]
Summary:
When its generated, the general ledger report, in Odoo version 16 it is not grouped by taxes.

Modules:
[Account financial report](https://github.com/OCA/account-financial-reporting/tree/16.0/account_financial_report)

Describe the bug:
Generate a general ledger report configuring a tax account and grouping it by taxes. It looks like the following screenshot:
![V16_general_ledger](https://github.com/OCA/account-financial-reporting/assets/153611478/4cc015d8-58e3-4d69-b7c6-8a95f0de37f2)

Expected behaviour:

The correct operation would be, however, like the following screenshot taken on a v15

![v15_general_ledger](https://github.com/OCA/account-financial-reporting/assets/153611478/f051d0de-8157-452c-9e64-5143787ad729)

To reproduce:

Generate a general ledger type report with the following parameters:

- Includes an accounting account with tax.
- It is grouped by taxes.

**Comment by HaraldPanten** [comment]
@pedrobaeza @victoralmau  Did you know that? THX

**Comment by HaraldPanten** [comment]
Closing, solved in https://github.com/OCA/account-financial-reporting/pull/1136
