### ISSUE TITLE
Aged Partner Balance from invoice date or due date

### ISSUE THREAD

**Issue by max3903** [OCA/account-financial-reporting#114]
When generating the Aged Partner Balance report, we want to choose the date to compute the age of the invoices. The age could be based on:
- the invoice date
- the due date

Mockup of the wizard:
![customer invoices - openerp 2015-09-02 11-49-55](https://cloud.githubusercontent.com/assets/939952/9636715/f60ab966-516a-11e5-8fcf-d97c7ab15476.png)

**Comment by pedrobaeza** [comment]
Seems to be fixed.
