### ISSUE TITLE
[RFC] account_financial_report: Improve UX in accounting reports and wizards

### ISSUE THREAD

**Issue by carlosdauden** [OCA/account-financial-reporting#1153]
The way accounting reports are obtained leaves a lot to be desired, and it is quite embarrassing to teach accountants how to use them (at least Spanish accountants).

This issue is opened to comment on the improvements to be introduced respecting as much as possible the use and needs of the whole Odoo community.

ping account PSCs: @AaronHForgeFlow @adrienpeiffer @grindtildeath @tafaRU @alexis-via @fclementic2c @HaraldPanten @jgrandguillaume @JordiBForgeFlow @kittiu @max3903 @rafaelbn @sergiocorato @sbidoul @sergio-teruel

**Comment by pedrobaeza** [comment]
One thing mentioned in https://github.com/OCA/account-financial-reporting/pull/1148#issuecomment-2092666292 is that the analytic account column is not hidden if no analytic is selected. I think this is a bug to be fixed, and I think this was taken into account in some moment in the past.

**Comment by carlosdauden** [comment]
A model could be added to show the fields to be displayed as discussed [here](https://github.com/OCA/account-financial-reporting/pull/1148#issuecomment-2092659355), similar to what is done in this development:

https://github.com/Tecnativa/tms/blob/15.0/tms_reporting/models/tms_print_template.py
https://github.com/Tecnativa/tms/blob/15.0/tms_reporting/views/report_account_invoice.xml#L12-L46

**Comment by JordiBForgeFlow** [comment]
@carlosdauden the statement "The way accounting reports are obtained leaves a lot to be desired" is a bit too vague, isn't it? What is wrong with them?

**Comment by HaraldPanten** [comment]
> @carlosdauden the statement "The way accounting reports are obtained leaves a lot to be desired" is a bit too vague, isn't it? What is wrong with them?

I was thinking the same. Could you make a deeper analysis or explain it a little bit more?

Of course, any improvement would be taken in consideration. The Spanish OCA Days meeting could be a nice place where to talk about that.
