### ISSUE TITLE
[17.0] account_financial_reporting - Translation error on accents

### ISSUE THREAD

**Issue by jvbp** [OCA/account-financial-reporting#1159]
Error in accents on .po files. The PO files wich has accents on translations are wrong on 17.0

## Module
account_financial_report

## Describe the bug
The translated field when it has accents are wrong in .po files
See example:
![image](https://github.com/OCA/account-financial-reporting/assets/52859958/cf3245ea-7cee-45ef-92eb-db66a53758bf)

## To Reproduce
**Affected versions**:

1. Look at the files or install module
2.
3.

**Expected behavior**
No ?? in PO files 

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by pedrobaeza** [comment]
I'm not seeing such problem right now:

![imagen](https://github.com/OCA/account-financial-reporting/assets/7165771/30da5f67-4b13-411b-b0d7-26f9cf1c653e)
