### ISSUE TITLE
Profit and Loss template && import error in odoo9

### ISSUE THREAD

**Issue by mfzoutsource** [OCA/account-financial-reporting#132]
Hi everyone,

If I not mistaken, there is template for profit and loss 
(in account-financial-reporting/account_financial_report_webkit/report/templates), but there is no py file that call that template? Am I right or I just missing the where and how to call it?
I'm using odoo 8.

And then, I try to install account_financial_report_webkit in odoo 9, then it cannot find module file.
The error look like this because there is no more function called as common_report_header in odoo9 (I think)

  File "/opt/odoo/extra_addons/account_financial_report_webkit/report/common_reports.py", line 29, in <module>
    from openerp.addons.account.report.common_report_header import common_report_header
ImportError: No module named common_report_header

**Comment by pedrobaeza** [comment]
Bad installation.
