### ISSUE TITLE
MIS - Report - Performance Issue

### ISSUE THREAD

**Issue by nmoturi** [OCA/account-financial-reporting#134]
Hi,

I've been testing MIS reports in version 7 (Backport) and experiencing performance issue when viewing the report, for ex:- below is the report I was trying to run against account move line object with more than a 1 million records. It takes more than 2 hours to present the data view..Is there something I need to be looking at..?

![report](https://cloud.githubusercontent.com/assets/7597063/11162419/bd4cb5e4-8ac6-11e5-9f5d-b52da62f702d.png)

MIS Template 

![image](https://cloud.githubusercontent.com/assets/7597063/11162489/6c54368c-8ac9-11e5-9f5c-b1425de9b91a.png)

Thanks,
Naran

**Comment by sbidoul** [comment]
@nmoturi thanks for using mis_buider. This is typically the kind of reports that should be reasonably fast with that kind of data volume. We have tested on high volume with 8.0 only, though. 

So a few things come to mind:
- perhaps the `read_group` of Odoo is faster in 8.0 than 7.0. With such a report, mis_builder should do only one `read_group` per column with a group by account_id.
- to better understand what happens, enable logging of long running queries in postgres: https://wiki.postgresql.org/wiki/Logging_Difficult_Queries and report your findings here
- check your postgres version: recent versions have optimized agregation methods (sum group by)

**Comment by nmoturi** [comment]
Thanks @sbidoul for the feedback, I will post the query findings. The current postgres version is 9.1, I will first check by upgrading it to 9.4 and see if any improvement.

**Comment by nmoturi** [comment]
upgrading postgres from 9.1 to 9.4 did made a difference, its now taking only couple of min to generate a view. Thanks @sbidoul
