### ISSUE TITLE
mis_builder_demo : no data is loaded

### ISSUE THREAD

**Issue by mamaf** [OCA/account-financial-reporting#135]
After having installed the module, I can't see any MIS example in the "MIS reports" menu 

Did I miss something ?

Thanks

**Comment by laetitia-gangloff** [comment]
Hello @mamaf,
is your database initialize with demo data ?
Csv from mis_builder_demo are declared in demo section. 

![image](https://cloud.githubusercontent.com/assets/7602419/11177703/b5d21c96-8c47-11e5-9319-fd4c0e775d3f.png)

**Comment by mamaf** [comment]
Hello,

No, as I said, I don't see any reports in "MIS reports" screen

http://www.6it.fr/

*Jean-Marc DUPONT *

*Agence Web, e-Commerce et Systèmes d'entreprise *

68, rue du Refuge - 84200 Carpentras

T. 06.24.91.02.03  -  04 84 25 17 94

Éditeur de la marque _Provenc.io https://provenc.io/_

1° marque e-Commerce 100% Provence

2015-11-16 9:52 GMT+01:00 Laetitia Gangloff (ACSONE) <
notifications@github.com>:

**Comment by houssine78** [comment]
@mamaf I think that laetitia asked you if you created your database with the demo data checked. If you don't, the mis_builder_dem module won't create/display the demo reports at its installation

**Comment by sbidoul** [comment]
I think this one can be closed. Feel free to reopen if not.
