### ISSUE TITLE
MIS report issue

### ISSUE THREAD

**Issue by Ayhamhafez** [OCA/account-financial-reporting#136]
MIS reports not installed, stuck while installing

**Comment by laetitia-gangloff** [comment]
Which version ? (7.0 or 8.0)
Do you have any error message to provide ?
And maybe some step to reproduce your issue ?

**Comment by Ayhamhafez** [comment]
Thanks for fast respond

Today I had updated my Odoo V 8 from Github (pull new update), after that I
tried to install MIS module but it doesn't install and not give any error
just stuck on cancel install mode, before updating Odoo it was installed
fine.

**Comment by sbidoul** [comment]
Closing because of no answer.
