### ISSUE TITLE
Module does not install in odoo 8

### ISSUE THREAD

**Issue by Whytehorse** [OCA/account-financial-reporting#137]
I tried to install this module several different ways to odoo 8 stable nightly and it fails with no error. In the server log is this error:
Error details:
Field `centralized` does not exist

Error context:
View `account.account.form.webkit`

**Comment by eLBati** [comment]
Hello @Whytehorse which module?

**Comment by Whytehorse** [comment]
account-financial-reporting
more specifically, the report_xls module. I've checked the dependencies and all are met.

**Comment by eLBati** [comment]
Just tried on http://3119169-8-0-c9c941.runbot2.odoo-community.org (base DB) installing `account_financial_report_webkit` (which handles the `centralized` field), then installed `report_xls` without errors.

Are you using the last revision of https://github.com/OCA/account-financial-reporting/tree/8.0 ?
Then you should report the steps to make the error happen on a new database and the server traceback.

Thanks

**Comment by Whytehorse** [comment]
I figured it out. It was the permissions. After copying over the files to the addons directory I had to run:
sudo chown -R root:root addon_folder_name
sudo chmod -R 755 addon_folder_name

Please close this issue and mark it solved.
