### ISSUE TITLE
Aged Partner balance - Partial allocations - Not aging Properly

### ISSUE THREAD

**Issue by nmoturi** [OCA/account-financial-reporting#138]
Hi,

The aged partner balance report is not aging correctly when partial allocations exists, the invoice amount is aged at the original amount and the partial allocation is completely ignored becuase it won't have any due date. Below are the screen shots ;- In the example, the invoice INV/6623 is allocated partially for the amount $648.96 and when the report is run, the aging has ignored the partial allocation and ages with the full amount.

1) Partial allocation 

![image](https://cloud.githubusercontent.com/assets/7597063/11331282/abc9e3b2-920c-11e5-907e-012720d01a4b.png)

2) Aged partner balance - Detail List

![image](https://cloud.githubusercontent.com/assets/7597063/11331301/f1792828-920c-11e5-9cf9-155f249a113d.png)

**Comment by pedrobaeza** [comment]
This was already fixed. Please try latest version.
