### ISSUE TITLE
Low performance in last_rec_date initialization

### ISSUE THREAD

**Issue by pablocm-aserti** [OCA/account-financial-reporting#15]
Hello
Please, in the migrate method of account_financial_report_webkit, consider moving the reconcile_id/reconcile_partial_id not null check outside from the inner select.
In densely populated DDBB the query launches the inner select hundreds of thousand times for account_move_lines without reconcile_id nor reconcile_partial_id
Example:

``` SQL
UPDATE account_move_line as acm 
SET last_rec_date =
    (SELECT date from account_move_line
    WHERE reconcile_id =  acm.reconcile_id
    ORDER BY date DESC LIMIT 1)
WHERE last_rec_date is null and acm.reconcile_id IS NOT NULL;
```

**Comment by pedrobaeza** [comment]
Hi @pablocm-aserti, can you please make a PR to the repository with this change?

**Comment by pablocm-aserti** [comment]
Hi @pedrobaeza 
Done!
Please let me know if I did something wrong, the travis test failed but I don't know if it is because of my changes or the travis configuration itself:
dropdb: database removal failed: ERROR:  database "openerp_test" does not exist

**Comment by pedrobaeza** [comment]
Thanks, for the record, it's PR #19
