### ISSUE TITLE
8.0 Required report does not exist: account.account_report_trial_balance_xls

### ISSUE THREAD

**Issue by DayssamAgora** [OCA/account-financial-reporting#150]
Hi OCA members,

I got this error 

<type 'exceptions.Exception'>,Required report does not exist: account.account_report_trial_balance_xls,<traceback object at 0x7fa771ad0ab8>

Best regards

**Comment by davshafik** [comment]
+1

**Comment by pedrobaeza** [comment]
This seems a bad installation or an outdated version. Closing.
