### ISSUE TITLE
account_financial_report_webkit: Initial balance counts not posted moves

### ISSUE THREAD

**Issue by omar7r** [OCA/account-financial-reporting#152]
Hi,

Maybe it can't be consider an issue but i think is dangerous, the general method "_compute_init_balance" sum all move lines in the first special period but it doesn't check the state of its move, maybe we have to rewrite the query of this method from 

`self.cursor.execute("SELECT sum(debit) AS debit, sum(credit) AS credit, sum(debit)-sum(credit) AS balance, sum(amount_currency) AS curr_balance FROM account_move_line WHERE period_id in %s AND account_id = %s", (tuple(period_ids), account_id))`

to

`self.cursor.execute("SELECT sum(debit) AS debit, sum(credit) AS credit, sum(debit)-sum(credit) AS balance, sum(amount_currency) AS curr_balance FROM account_move_line INNER JOIN account_move on account_move_line.move_id = account_move.id WHERE account_move_line.period_id in %s AND account_id = %s AND account_move.state = 'posted'", (tuple(period_ids), account_id))`

What do you think?
Regards

**Comment by pedrobaeza** [comment]
Closing this as very old. If you want to make a PR, feel free to open it.
