### ISSUE TITLE
[blueprint] mis_builder styles

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-financial-reporting#175]
# Problem statement

Mis builder currently uses CSS to adjust report presentation styles. This has two drawbacks:
- it is too technical for many users, steepening the learning curve
- while it works fine for HTML rendering (and PDF), it is hard to implement in excel export
- there is no mechanism to reuse styles across KPIs or reports

This is a proposal to deprecate CSS in favor of explicit style objects.
# Proposed implementation

A new model `mis.report.style` with the following attributes (loosely inspired from CSS, but not too close in order to be easily applicable to various rendering methods):
- name (unique, required)
- color (html #RRGGBB format?)
- background-color (html #RRGGBB format?)
- font-style (normal|italic)
- font-weight (normal|bold)
- font-size (font-size:medium|xx-small|x-small|small|large|x-large|xx-large)
- indent-level: integer (>= 0)

Styles are global and shared across various reports.

`mis.report.style` must have a method to convert to CSS.

`mis.report.style` must have a method to convert to Excel through xslxwriter (https://github.com/OCA/reporting-engine/pull/38) or xslwt (for report_xls).

`mis.report.kpi` `default_css_style` and `css_style` and becomes deprecated.

`mis.report.kpi` gains two new fiellds:
- `style`: a mis.report.style for the row style
- `style_expression`: an expression that returns a style name for the kpi style (TBC: is there a better idea?)

`mis.report.instance.period` may gain a `style` attribute for the column style (TBC).

Styles are applied in the following priority order:
- row (from mis.report.kpi:style)
- column (from mis.report.instance.period:style?)
- kpi (from mis.report.kpi:style_expression)

**Comment by JordiBForgeFlow** [comment]
@sbidoul great proposal! With regards to kpi 'style_expression' do you mean that this would be an expression on what style to apply depending on the value of the KPI? That would be a great addition!

**Comment by sbidoul** [comment]
> With regards to kpi 'style_expression' do you mean that this would be an expression on what style to apply depending on the value of the KPI?

It's exactly that indeed. In the current version there is already the `ccs_style` (aka CSS Style Expression) field where you can write something like `'color: red' if mykpi < 0 else 'color: green'`.

**Comment by sebastienbeau** [comment]
I am ok with the concept :+1:

**Comment by gfcapalbo** [comment]
About the deprecaton of default_css_style and css_style we have agreed to mantain these two fields and make them automatically generated from user selected fields via a stored compute.

**Comment by sbidoul** [comment]
The implementation is in the sorrento PR https://github.com/OCA/account-financial-reporting/pull/189/commits/df59a4702bfc44ed0a2501980a53a7196847bb65

**Comment by sbidoul** [comment]
Merged in 9.0
