### ISSUE TITLE
[8.0] mis_builder: query aggregation and computed fields

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-financial-reporting#178]
When a mis.report.query has the aggregate function set to Sum and there are non-stored fields selected, it does not work, because Odoo's group by function does not support non-stored fields.

In presence of such fields, it must fallback transparently on the the searc_read method.

This can be done by testing the presence of non-stored fields here:
https://github.com/OCA/account-financial-reporting/blob/0244754dcdad7b18f8d7a4c4ed6af314a907defd/mis_builder/models/mis_builder.py#L490
and falling back on the else just after in such case.

**Comment by sbidoul** [comment]
The fix is merged in 9.0, but I reopen for 8.0.

**Comment by Cedric-Pigeon** [comment]
@sbidoul issue can be closed
