### ISSUE TITLE
account_financial_report_webkit 7.0: TypeError: translate_call() takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by akhayyat** [OCA/account-financial-reporting#18]
Using the 7.0 branch of the account_financial_report_webkit module with openerp 7.0 (7.0-20140804-2) and wkhtmltopdf 0.12.1, printing a webkit financial report, such as General Ledger or Trial Balance results in a TypeError: translate_call() takes exactly 2 arguments (3 given).

Full traceback:

``` python
Webkit render

Traceback (most recent call last):
File "/opt/openerp/7.0/account-financial-reporting/account_financial_report_webkit/report/webkit_parser_header_fix.py", line 252, in create_single_pdf
**parser_instance.localcontext)
File "/usr/lib/python2.7/dist-packages/mako/template.py", line 397, in render
return runtime._render(self, self.callable_, args, data)
File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 764, in _render
**_kwargs_for_callable(callable_, data))
File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 796, in _render_context
_exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 822, in _exec_template
callable_(context, *args, **kwargs)
File "memory:0xb292b10", line 22, in render_body
<%
TypeError: translate_call() takes exactly 2 arguments (3 given)
```

**Comment by sbidoul** [comment]
This issue happened at some point because a version mismatch.

Please make sure you have the latest version of openerp 7.0 from github as well as the latest 7.0 branch of OCA/account_financial_report.

**Comment by akhayyat** [comment]
The current github 7.0 branch does solve the problem indeed. However, the Debian packages [provided by OpenERP/Odoo](http://nightly.openerp.com/7.0/nightly/deb/) stop at 7.0-20141004.

Does this mean that I cannot use this module with a deb-packaged version of OpenERP 7.0?

**Comment by sbidoul** [comment]
That is weird because 20141004 is today, so it should be the latest.

**Comment by akhayyat** [comment]
It _is_ weird, because they started getting produced again starting at 20141003! The latest version before that is 20140804. My bad for not checking what I was typing!

**Comment by vishpepala** [comment]
I am already using the old version 7.0-20131230-002457.  Now I have to use this module.  I cannot change entire code since I have modified a lot.  Can you please explain what are the exact files I have to replace?  
Please guide me.

**Comment by vishpepala** [comment]
I just replaced "account_financial_report_webkit" module with your latest module from github.  Still issue persist.  Please help.

**Comment by RoelAdriaans** [comment]
@vishpepala you can replace the file addons/addons/report_webkit/webkit_report.py  and restart openerp. That might fix the issue. Just had the same problem, and replacing only that module worked.

**Comment by vishpepala** [comment]
@RoelAdriaans-B-informed Thank you very much.  I will try this first thing in the morning and update you.  Tons of thanks again.  :-)

**Comment by ashwin-raj** [comment]
Hi Guys,
I also have the same issue.  I replaced the webkit_report.py file. still the issue is coming.  Currently I am using python 2.7.  May I know how to resolve the problem.

**Comment by ashwin-raj** [comment]
My error message is,
{"message": "OpenERP Server Error", "code": 200, "data": {"debug": "Server \nClient Traceback (most recent call last):\n File \"/usr/lib/python2.7/dist-packages/openerp/addons/web/http.py\", line 285, in dispatch\n r = method(self, *_self.params)\n File \"/usr/lib/python2.7/dist-packages/openerp/addons/web_pdf_preview/controllers/**init**.py\", line 31, in index\n result = super(WebPdfReports, self).index(req, action, token)\n File \"/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py\", line 1769, in index\n req.session._db, req.session._uid, req.session._password, report_id)\n File \"/usr/lib/python2.7/dist-packages/openerp/addons/web/session.py\", line 30, in proxy_method\n result = self.session.send(self.service_name, method, *args)\n File \"/usr/lib/python2.7/dist-packages/openerp/addons/web/session.py\", line 91, in send\n raise xmlrpclib.Fault(code_string % (e.name, e.value), '')\nFault: &lt;Fault warning -- Webkit render\n\n\n\nTraceback (most recent call last):\n File \"/usr/lib/python2.7/dist-packages/openerp/addons/account_financial_report_webkit/report/webkit_parser_header_fix.py\", line 228, in create_single_pdf\n \n File \"/usr/lib/python2.7/dist-packages/mako/template.py\", line 443, in render\n return runtime._render(self, self.callable_, args, data)\n File \"/usr/lib/python2.7/dist-packages/mako/runtime.py\", line 807, in _render\n *__kwargs_for_callable(callable_, data))\n File \"/usr/lib/python2.7/dist-packages/mako/runtime.py\", line 839, in _render_context\n _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)\n File \"/usr/lib/python2.7/dist-packages/mako/runtime.py\", line 865, in _exec_template\n callable_(context, _args, *_kwargs)\n File \"memory:0x7f01b9ceecd0\", line 33, in render_body\n &lt;div class=\"act_as_cell\"&gt;${_('Chart of Account')}&lt;/div&gt;\nTypeError: translate_call() takes exactly 2 arguments (3 given)\n: ''&gt;\n", "fault_code": "warning -- Webkit render\n\n\n\nTraceback (most recent call last):\n File \"/usr/lib/python2.7/dist-packages/openerp/addons/account_financial_report_webkit/report/webkit_parser_header_fix.py\", line 228, in create_single_pdf\n \n File \"/usr/lib/python2.7/dist-packages/mako/template.py\", line 443, in render\n return runtime._render(self, self.callable_, args, data)\n File \"/usr/lib/python2.7/dist-packages/mako/runtime.py\", line 807, in _render\n **_kwargs_for_callable(callable_, data))\n File \"/usr/lib/python2.7/dist-packages/mako/runtime.py\", line 839, in _render_context\n _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)\n File \"/usr/lib/python2.7/dist-packages/mako/runtime.py\", line 865, in _exec_template\n callable_(context, _args, *_kwargs)\n File \"memory:0x7f01b9ceecd0\", line 33, in render_body\n &lt;div class=\"act_as_cell\"&gt;${_('Chart of Account')}&lt;/div&gt;\nTypeError: translate_call() takes exactly 2 arguments (3 given)\n", "type": "server_exception"}}
