### ISSUE TITLE
[blueprint] mis_builder: visual fold/unfold mechanism

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-financial-reporting#180]
## Problem statement

With large reports, such as a complete chart of account it can be desirable to express a parent/child relationship between KPI's and let the user fold/unfold parent KPI's on screen when using the mis builder widget.
## Implementation proposal: backend

Add fields on mis.report.kpi
- parent_id
- fold_default: open|closed (default open)

A parent/child relationship does not imply any automatic computation.

The parent/child relationship may influence/enforce ordering of kpi's.
## Implementation proposal: UI
- display folding icons (only if a KPI has children)
- automatically indent row labels based on parent-child relationship
## Further possible improvements to be investigated
- it may be useful to provide the list of children kpi values in the computation context of a kpi
- it may be useful to improve the computation algorithm to compute children before parents, knowing that in many circumstances a visual folding implies a dependency on the children values

**Comment by Martronic-SA** [comment]
_Shouldn't we use the nvd3 javascript class [tree](http://nvd3.org/examples/indentedtree.html) ? That would also allow the use of bar, pie and other types of charts_.
ok this is no more supported.

**Comment by sbidoul** [comment]
This issue was moved to OCA/mis-builder#11
