### ISSUE TITLE
[all] Balance with opening and closing values

### ISSUE THREAD

**Issue by ghost** [OCA/account-financial-reporting#187]
Dear all,

I hope that this is the right place/module to post. I know OpenERP 6.04 very well and recently installed OCB 8.0 and 9.0 (as Odoo is becoming proprietary). 

Please pardon my ignorance if this feature is already present in OCB.

When closing a year, accountants print a general balances with:
- Opening values
- Debit
- Credit
- Closing values

This allows to verify that the opening values are the same as in the end of the previous year and compare the balance with fiscal declarations (results, VAT, etc ...). In case of fiscal inquiry by the administration, such a balance is requested. It is a legal issue.

OCB can print a general balance with debit, credit and balance (in the end of the year).  But we need also:
- opening values (including opening journal)
- closing values

Commercial software always print opening and closing values.
I suspect this feature is needed in every country and it would help a lot of people.

Odoo company never did the job of working on a compliant accounting, so I may pick-up myself this issue inside OCA. Please pick it up if you are interested.

Feel free to include this kind of report in the SPEC around accounting rework. I will join the accounting group later, sorry I could not attend the 2016/sprint in Italy (as I was not aware).

Kind regards,
Kellogs

**Comment by sbidoul** [comment]
This is part of the Trial Balance and other reports for v7 and v8 (see account_financial_report_webkit module) and will be part of it in v9 too, for which the work has been done in Sorrento and will be merged in the coming days/weeks.

**Comment by hbto** [comment]
Yet this issue is close I will leave my comment:

Check odoo-afr module it works on v7/v8

https://github.com/Vauxoo/odoo-afr

Best Regards
