### ISSUE TITLE
[8.0] mis_builder: avoid calling compute twice in widget

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-financial-reporting#194]
This is fixed on the 9.0 branch: https://github.com/OCA/account-financial-reporting/pull/189/commits/4dd0aec548b04d80024fcfd7b244b41935ebe0c8

**Comment by ovnicraft** [comment]
If was fixed, close it please.

**Comment by sbidoul** [comment]
AFAIK this bug is still present in 8.0?

**Comment by Cedric-Pigeon** [comment]
@sbidoul issue can be closed
