### ISSUE TITLE
[9.0] mis_builder col_width-related crash in xslx export when there is only one column

### ISSUE THREAD

**Issue by wiseguuy** [OCA/account-financial-reporting#204]
when i test with mis_builder (9.0), i found some error at line no. 134 of "mis_report_instance_xslx.py".
show the following.

 data_col_width = min(MAX_COL_WIDTH, max(*col_width.values()))
TypeError: 'int' object is not iterable

when i printed out show "col_width.values() is [10]" and not working.

help me some solution.

Thank you.

**Comment by sbidoul** [comment]
Thanks for reporting. I confirm the issue which must occur when there is only one column. 

`max(*[10])` fails while `max(*[10,11])` works. But both `max([10])` and `max([10,11])` work. 

So the fix would consist in removing the `*` on that line and the 2 following lines.

Can you test that and provide a pull request?

**Comment by wiseguuy** [comment]
Thank you for your immediate response. now i got it. by the way, any reference for dynamic query and kpi setup? If have it, please let me know. Thank you.
