### ISSUE TITLE
[8.0] mis_builder: Drill down for entries

### ISSUE THREAD

**Issue by lcymic** [OCA/account-financial-reporting#206]
Hi, 

I am new to odoo and want to know if there is any drill down feature in this addon. 
Could we click any of the output lines and go to the accounting entries screen?

Thanks a lot~

Mike

**Comment by sbidoul** [comment]
Yes the drill-down to accounting entries is built-in. Any cell rendering an expression on accouting entries (balp, crdp, debp, etc) is clickable and shows the underlying account move lines.
