### ISSUE TITLE
[9.0] MIS Builder no longer installs on enterprise version

### ISSUE THREAD

**Issue by richard-willdooit** [OCA/account-financial-reporting#208]
@sbidoul 

The MIS Report Templates menu option, since 5th of May, is defined to be in the "account.menu_account_reports" - This menu is deleted in the enterprise install by "account_extension" module, meaning MIS builder cannot be installed.

commit: 5a1a6e59269a0a309ce66054f780ec79cb6d2f59

**Comment by sbidoul** [comment]
@richard-willowit yes, mis_builder needs some love to work on enterprise.

Do you know if reverting that commit works (on community too?). Can you make a PR or suggest the best parent menu?

**Comment by ovnicraft** [comment]
IMO is not good for OCA modify modules to work with `no open source` modules, MIS builder is open source and must `only` works with Community edition.

**Comment by richard-willdooit** [comment]
@ovnicraft My proposed merge is so it will work with both community and enterprise.  Without merging this, it works in community and crashes in enterprise.  I would never suggest making this enterprise dependent.

**Comment by richard-willdooit** [comment]
@sbidoul Any chance this can be reviewed and pulled?

**Comment by ovnicraft** [comment]
@richard-willowit yes i got it, its just to be friendly with Enterprise, BTW i'm not agree

**Comment by richard-willdooit** [comment]
@ovnicraft Sorry - so you are happy that it does not work on Enterprise?  We support over 30 clients, most with Enterprise agreements.  Why should they not be allowed to use mis_builder?

**Comment by elicoidal** [comment]
:+1: with @richard-willowit 
The policy of the OCA is to be "reasonably" compatible with Enterprise

**Comment by sbidoul** [comment]
@richard-willowit thanks for the fix! It got under my radar during the holidays, sorry for the delay.
