### ISSUE TITLE
[9.0] mis_builder does not handle account with type Current Year Earnings

### ISSUE THREAD

**Issue by fclementic2c** [OCA/account-financial-reporting#210]
If you try to create a Trial balance and populate accounting move lines over 2 fy, the Profit/Loss account do not report the previous year P&L balance in the Current Year Earnings account.

I expect all revenues and expenses accounts having their balance initialized on the 1st day of the fy and reported to the bs account ; all balance sheet accounts having their balance not initialized

see my test database : 
[l10n_fr_test_mis_2016-07-18_14-28-01.zip](https://github.com/OCA/account-financial-reporting/files/369277/l10n_fr_test_mis_2016-07-18_14-28-01.zip)

**Comment by sbidoul** [comment]
@fclementic2c there is a special `balu` expression that computes the previous year unallocated earnings.

So you can configure Classe 9 like this
![image](https://cloud.githubusercontent.com/assets/692075/16928031/ccc68496-4d30-11e6-9037-00e0650a9caf.png)

To obtain a well-balanced balance
![image](https://cloud.githubusercontent.com/assets/692075/16928003/b6115cd0-4d30-11e6-9fd8-7456c76bc49e.png)

I added this Misc Op to your database to allocate the 2015 result during 2016
![image](https://cloud.githubusercontent.com/assets/692075/16928063/fc32cbfe-4d30-11e6-8a76-124cdbaf45f9.png)

**Comment by fclementic2c** [comment]
Thanks. much better. :)

**Comment by sbidoul** [comment]
Yep. Wondering how it would work with the 12 months report, though...

BTW, do you know you can use the same report _template_ to print the 4 and 12 columns reports, by selected which subkpi appear in each column (eg display init + end in first month, and end only in all other month).
