### ISSUE TITLE
[MIG] [8.0] We are planning to migrate account_financial_report to QWeb

### ISSUE THREAD

**Issue by nhomar** [OCA/account-financial-reporting#22]
Hello.

In vauxoo @hbto is planning migrate account_financial_report ([the one which render with reportlab](https://github.com/OCA/account-financial-reporting/tree/8.0/__unported__/account_financial_report)) to QWEb in order to maintain one set of reports with the official report engine, and considering some points that will need to be necessary to improve for [v9.0](https://docs.google.com/document/d/1MahXh0TdfjI0ohdTSz_c8cML7HqxvcAtvSAY63N20Tc/edit?usp=sharing).

The Idea is set this issue as open until we finish the job which will be done on this [fork](https://github.com/Vauxoo/account-financial-reporting) and is being planned to be done for next week.
- Somebody started this job?.
- Some ideas about what need to be improved are welcome (if any).

Regards.

**Comment by mylbco** [comment]
@nhomar any progress on this issue ?

**Comment by nhomar** [comment]
hello @mylbco 

The work is done here:

https://github.com/Vauxoo/odoo-afr

Due to our internal customers and usage do not allow us move at the speed of OCA yet, we didn't finish the rought edges there.

The actual Status is:
- Qweb templates and layout working.
- Actuallly it is printing on rml because the look and feel is not good in our impression, then have it ready need a little more work.
- Cleanup the not used files.
- Put OCA information to make the respective PR.
- It is being used in 2 big customers as it is now.

You can use it on v8.0 actually and give feedback [here](https://github.com/Vauxoo/odoo-afr) in the next few months (probably by the end of the year) we will prepare the PR.

**Comment by mylbco** [comment]
Nice @nhomar !.

**Comment by pedrobaeza** [comment]
It was migrated in v9 to QWeb, so I close.
