### ISSUE TITLE
[9.0] mis_builder: support empty expressions in sub kpis

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-financial-reporting#236]
It currently crashes in such case. The workaround is easy (enter 0 or AccountingNone) but it'd be nice to not have a stack trace.

**Comment by sbidoul** [comment]
Implemented in https://github.com/OCA/account-financial-reporting/commit/f0239b739134acf44e0df5f2198971afbba817c6, pending 9.0 backport

**Comment by JordiBForgeFlow** [comment]
@sbidoul currently it does not support also empty expressions in Kpi's. When exporting to XLSX it crashes.

An example:
![image](https://cloud.githubusercontent.com/assets/7683926/23963001/310bd906-09b0-11e7-999f-36a52d5139c8.png)

Template definition:
![image](https://cloud.githubusercontent.com/assets/7683926/23963055/5ca112b6-09b0-11e7-98af-3fd2fd69ea88.png)

Error when you try to export to Excel:
![image](https://cloud.githubusercontent.com/assets/7683926/23963036/4857b436-09b0-11e7-90a7-bcccad7ea7cc.png)

**Comment by JordiBForgeFlow** [comment]
Crashes here: https://github.com/OCA/account-financial-reporting/blob/9.0/mis_builder/report/mis_report_instance_xlsx.py#L126

**Comment by sbidoul** [comment]
@jbeficent Can you test https://github.com/OCA/account-financial-reporting/pull/275 ?

**Comment by JordiBForgeFlow** [comment]
Sure! Will do tomorrow first thing

**Comment by sbidoul** [comment]
This issue was moved to OCA/mis-builder#10
