### ISSUE TITLE
account_financial_report_webkit_xls error

### ISSUE THREAD

**Issue by ccarly** [OCA/account-financial-reporting#24]
Messege: account_financial_report_webkit_xls/report/trial_balance_xls.py", line 254, in generate_xls_report
    comparisons = current_account.comparisons

**Comment by pedrobaeza** [comment]
When this error happens?

**Comment by ccarly** [comment]
When I export the trial balance

**Comment by sbidoul** [comment]
@ccarly can you test again and close this issue if it works for you?

**Comment by ccarly** [comment]
Hello, sbidoul

I auditioned from your branch and the last commit and works well

**Comment by pedrobaeza** [comment]
Closing as it was fixed.
