### ISSUE TITLE
[9.0][10.0] account_financial_report_qweb: bad override of report_xslx without calling super

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-financial-reporting#241]
https://github.com/OCA/account-financial-reporting/pull/229/files#r80358319

report_xslx must be extended to support options.

cc/ @adrienpeiffer @jcoux

**Comment by jcoux** [comment]
I created 2 PR to resolve this problem: 
- https://github.com/OCA/reporting-engine/pull/77
- https://github.com/OCA/account-financial-reporting/pull/242

**Comment by pedrobaeza** [comment]
Closing as there are PRs in progress
