### ISSUE TITLE
[9.0] mis_builder: UnicodeEncodeError ... ordinal not in range(128) - generate_xlsx_report

### ISSUE THREAD

**Issue by zbik2607** [OCA/account-financial-reporting#244]
Line 45 in mis_report_instance_xlsx.py 
       report_name = '{} - {}'.format(
            objects[0].name, objects[0].company_id.name)

should be replaced by:
       report_name = u'{} - {}'.format(
            objects[0].name, objects[0].company_id.name)

**Comment by sbidoul** [comment]
@zbik2607 thanks for reporting. PR #246 created.

**Comment by sbidoul** [comment]
@zbik2607 BTW for small changes like this github has an edit button which makes it very easy to create pull requests, so don't hesitate to do it next time.
