### ISSUE TITLE
account_financial_report_webkit: Problems with negative numbers

### ISSUE THREAD

**Issue by jonerikceberio** [OCA/account-financial-reporting#255]
The webkit reports substitute the minus sign by a non-breaking hyphen to avoid wrapping issues:
`        def amount(text):
            return text.replace('-', '&#8209;')  # replace by a non-breaking hyphen (it will not word-wrap between hyphen and numbers)
`
However, the font support for this character is minimal: http://www.fileformat.info/info/unicode/char/2011/fontsupport.htm
¿Could it be replaced by the minus sign: MINUS SIGN “−” (U+2212) &minus;? As read in http://stackoverflow.com/questions/22061036/prevent-breaking-of-negative-numbers it has a decent wrapping behaviour (except for Chrome for Mac), and has a max better font support: http://www.fileformat.info/info/unicode/char/2212/fontsupport.htm

**Comment by pedrobaeza** [comment]
If you want to add that support, please open a PR. This version is being very old and the support is limited.
