### ISSUE TITLE
Account Tax balance installation performance issue

### ISSUE THREAD

**Issue by flotho** [OCA/account-financial-reporting#258]
Hi,

I'm trying to install the account_tax_balance released by @eLBati .
My database has ~900.000 move lines and the installation process is stucked in the move_type update process.
Is it possible to delay the update ?
Regards

**Comment by eLBati** [comment]
@flotho if you don't need to fill ```move_type``` values for old move lines, you can manually create the column (varchar) in the DB and install the module.
odoo should skip computing the column  as already existing
