### ISSUE TITLE
issues with wkhtmltopdf 0.12.4 (and 0.12.3) with branch 6.1

### ISSUE THREAD

**Issue by ghost** [OCA/account-financial-reporting#261]
I've recently upgraded to recent OCA bits for 6.1 and wanted to give the webkit report engine a try.

Looks great, in particular the spreadsheet export, but unfortunately the pdf output has issues for all pages after the very first.

That is, it appears as if the header margin loses a point or two every subsequent page causing overwriting
of the column labels by the first data line.

Any fix or workaround ? I started out with wkhtmltopdf 0.12.3 but tried now as well with 0.12.4...

**Comment by ghost** [comment]
Does this have something to do perhaps with the file 
> account_financial_report_webkit/report/webkit_parser_header_fix.py

**Comment by pedrobaeza** [comment]
Sorry, but very old version and wkhtmltopdf not officially supported.
