### ISSUE TITLE
[8.0] account_financial_report_webkit Open Invoices Report error

### ISSUE THREAD

**Issue by abdallamhafeez** [OCA/account-financial-reporting#262]
Hello
I have problem when print "Open Invoices Report" with mark "Group Partner by currency" appear this error:

'account.account' object has no attribute 'ledger_lines'

<type 'exceptions.AttributeError'>,'account.account' object has no attribute 'ledger_lines',<traceback object at 0x7f7999bc33f8>

**Comment by pedrobaeza** [comment]
Can you please try to reproduce the error in runbot and put steps to get it.

**Comment by pedrobaeza** [comment]
I close this meanwhile.
