### ISSUE TITLE
[9.0] mis_builder: MIS builder rounds to entire numbers

### ISSUE THREAD

**Issue by qupro** [OCA/account-financial-reporting#263]
Every KPI I have created results in an entire number, not sure if It's a bug , normal behaviour or it's due to my lack of understanding of this.

For example I am using   this query:
- Name : invoice_sales
- Model : invoice
- Fields : amount_total_company_signed
- Aggregate : Sum
- Date field : Accounting Date
- Domain : [('journal_id.type','=','sale'),('state','not in',['draft','cancel'])]

and for KPI
- Name : invoce_sales_total_signed
- Value type : Numeric
- Comparison Method : Percentage (It's set by default , but I also have tried with "None")
- Multi : [uncheck]
- Expresion : invoices_sales.amount_total_company_signed

And It always results in rounded entire numbers

**Comment by sbidoul** [comment]
Rounding is controlled by the style. Please try to create and assign a style at the report or kpi level.

**Comment by qupro** [comment]
I didn't find any documentation about styling in MIS builder , could you give me an example or  resource url? Thanks

**Comment by qupro** [comment]
Ok , I catched it.

In Accounting > Configuration > MIS  Reports Styles , Create a new style , uncheck 
"Rounding inherit" and set the number of decimals then select it on report or kpi form
