### ISSUE TITLE
[9.0][mis_builder] Add special u mode (unallocated P&L) to the legend for KPI expressions

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/account-financial-reporting#280]
Starting from 9.0 onwards the special mode 'u' (e.g. balu) is essential to compute the profit/loss results from prior years. Should be included in the legend for MIS Report Templates.

![image](https://cloud.githubusercontent.com/assets/7683926/24001846/79faf926-0a5f-11e7-9dea-680231625880.png)

**Comment by JordiBForgeFlow** [comment]
cc @sbidoul

**Comment by JordiBForgeFlow** [comment]
Also in #275

**Comment by sbidoul** [comment]
This issue was moved to OCA/mis-builder#9
