### ISSUE TITLE
[10.0][mis_builder] Cannot delete mis report template if it contains sub kpi's

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/account-financial-reporting#281]
Testing #275 
If I define a mis report template with sub-kpi's, when I try to delete the whole report template I get the error:

`The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: mis.report.subkpi - mis.report.subkpi] 
`

Perhaps a delete=on_cascade should be added

cc @sbidoul

**Comment by sbidoul** [comment]
Should be fixed in https://github.com/OCA/account-financial-reporting/pull/275/commits/1d480d2bbe38b5e8ebdeeeea6c39c7c39c82eee5. Thanks for reporting!

**Comment by JordiBForgeFlow** [comment]
Works correctly now. Thanks!
