### ISSUE TITLE
[10.0][mis_builder] When copying a mis report template, the subkpi's of the kpi lines are not copied referencing to the copied sub-kpì's

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/account-financial-reporting#282]
One would expect that when a mis report template is copied, the whole structure is copied to a new mis report template, maintaining the internal coherence.

Instead, the sub kpi's are copied, but the use of the sub-kpis in the kpi lines is not.

Example:
Original:
![image](https://cloud.githubusercontent.com/assets/7683926/24008255/6c99a900-0a71-11e7-91bc-68bf395c33db.png)

Coped mis report template:
![image](https://cloud.githubusercontent.com/assets/7683926/24008310/8bbd92a6-0a71-11e7-9c61-b6a7c48ce1ab.png)

cc @sbidoul

**Comment by JordiBForgeFlow** [comment]
Related to #275

**Comment by sbidoul** [comment]
Fixed at 96b60d0

**Comment by JordiBForgeFlow** [comment]
I can look into that. There was a similar issue years ago creating projects from templates with regards to task relationships

**Comment by sbidoul** [comment]
@jbeficent it should be fixed at https://github.com/acsone/account-financial-reporting/commit/76f4efaede996361266a15846e0650ed998d718f

**Comment by JordiBForgeFlow** [comment]
I confirm that is now fixed. Thanks!
