### ISSUE TITLE
[10.0][mis_builder] Add constraint on mis report instance to avoid required fields that are blank

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/account-financial-reporting#283]
For example, when you create a MIS Report Instance and change to comparison mode a new line is created with name 'Actuals' where the fields 'Date From' and 'Date to' are blank. This is ok, but the user should then complete the necessary follow-up steps to make the mis report instance line correct.

![image](https://cloud.githubusercontent.com/assets/7683926/24009624/d4320f2c-0a75-11e7-978b-f8813c33d6d3.png)

Otherwise the report will raise an error message at the time of execution, and it is not very easy to understand what is the reason.

cc @sbidoul

**Comment by JordiBForgeFlow** [comment]
Related to #275

**Comment by JordiBForgeFlow** [comment]
I can now see that the lines become red when you change the mis builder instance to comparison mode

![image](https://cloud.githubusercontent.com/assets/7683926/24036626/9f7383da-0afa-11e7-9fe3-c97a8fb65440.png)

But allows to save it.

Is that the expected behaviour?

**Comment by sbidoul** [comment]
Yes, and you get a nice error message when you generate the report.

**Comment by JordiBForgeFlow** [comment]
Ok, thanks. Works fine!
