### ISSUE TITLE
[10.0][mis_builder] error exporting string-type kpis to XLSX

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/account-financial-reporting#285]
When you define a line as a string as indicated below, fails when exporting to XLSX: 
![image](https://cloud.githubusercontent.com/assets/7683926/24036172/b42a5e18-0af8-11e7-9ef9-15784ec0ed91.png)

![image](https://cloud.githubusercontent.com/assets/7683926/24036189/ce3aaf7e-0af8-11e7-944a-0d0bd049ca16.png)

cc @sbidoul

**Comment by JordiBForgeFlow** [comment]
Related to #275

**Comment by sbidoul** [comment]
Fixed in #275 

Note that if you want to display empty cells for kpis that are otherwise numerical, it's best to use `AccountingNone` as their value: it will display empty and nicely participate in arithmetic operations.

**Comment by sbidoul** [comment]
This issue was moved to OCA/mis-builder#8
