### ISSUE TITLE
[9.0][10.0] mis_builder: multi-company consolidation

### ISSUE THREAD

**Issue by Martronic-SA** [OCA/account-financial-reporting#295]
As said in the Readme, we might add a list of companies (which might have their own currencies) and convert amounts for each company/currency to user company currency. That's what Odoo does in account_reports.
As we probably will have to implement this in the mis builder, could you give us advices or ideas to start the project?
Thanks!

**Comment by Martronic-SA** [comment]
I would like to add a field "company_ids" in MIS Report Instance so that it would be possible to search account move lines in different companies.
I see that now only the company defined in the MIS Report Instance is passed to the AccountingExpressionProcessor.
Why not passing the whole MIS Report Instance on init to the AccountingExpressionProcessor so we can get useful data from the AccountingExpressionProcessor directly?

**Comment by sbidoul** [comment]
@Martronic-SA I want the AEP to stay as independent as possible from the rest to avoid useless coupling.

But I'm happy to change `company` to `companies` everywhere in `mis_builder`. The change should be relatively easy.

If you plan to work on this, I recommend doing a PR on top of #275.

**Comment by Martronic-SA** [comment]
Thank you for your reply.
I understand your point of view, in particular if the AEP has to be used somewhere else.
It's important to have the main company for which the other companies will be consolidated.
All the account move lines amounts from other companies have to be converted in main company's currency (rates depending on dates / periods).
In enterprise financial report, they are simply using user company (which can be changed) as main company. Therefore shoud we do the same and use user's company as main company and change the field "company" to "companies" or should we keep the company field and add another "companies" field and pass both of them to the AEP?

**Comment by Martronic-SA** [comment]
> If you plan to work on this, I recommend doing a PR on top of #275.

Is this available for v 9.0 also ? (or at least compatible?)

**Comment by sbidoul** [comment]
It should be compatible with v9. I need some more tests on this branch, before merging then backporting to 9.

**Comment by sbidoul** [comment]
Regarding currency conversion, I've not fully thought about the design yet. At first glance I'd say AEP should accept 3 parameters:
* a list of companies (added automatically to the domain filters, an generalization of the current `company`)
* a target currency (default to the currency in `companies`, error if it is not present and the companies don't have the same currency)
* a date for currency conversion (optional, defaults to today?)

**Comment by Martronic-SA** [comment]
For a client we have had to implement the currency rate feature in the financial reports.
They have many companies some with different currencies.
We have added four options:
today,
end of period (eg 31.12.2016)
start of period (1.1.2016)
average on period (this takes the arithmetic average of rates for the period)

The target currency might be the user's company currency or can be fixed in the MIS report instance.

**Comment by Martronic-SA** [comment]
What do you think of adding
"company", "company_ids", "exchange_rate_time" to MIS report instance
with domain changed to:
'|',('company_id', '=', self.company.id), ('company_id', 'in', self.company_ids.ids)
So we keep main company (for example MyCompany International or user company if empty?)
And we can add MyCompany Egypt, MyCompany India, MyCompany Germany to the report?

**Comment by sbidoul** [comment]
I'm not convinced there must be a concept of main company in mis builder. 

I see you need it to provide de default currency for the report. I think that would be better handled with a dedicated "report currency" field possibly with an onchange to populate it. 

Are there other ways that main company would have special treatments in the algorithm?

**Comment by Martronic-SA** [comment]
Ok, the currency might be enough if we don't need other informations from the mother company which seems to be the case.

**Comment by Martronic-SA** [comment]
I'm developing for Odoo 9.0 and I can't fork [#259](https://github.com/OCA/account-financial-reporting/pull/275) as it's using "from odoo import api" and odoo is not declared in Odoo 9.0 (it's from openerp import ...)

**Comment by sbidoul** [comment]
@Martronic-SA would it work for you to develop that on 10.0? Doing the backport after will be easy. On the contrary maintaining PR's on two different branches will be a real pain.

**Comment by Martronic-SA** [comment]
There might be useful to have a main company for getting fiscal year dates (instead of taking first company) in aep.py:
`fy_date_from = self.company_ids[0].compute_fiscalyear_dates(date_from_date)['date_from']`

**Comment by sbidoul** [comment]
See https://github.com/acsone/account-financial-reporting/pull/16

**Comment by sbidoul** [comment]
This issue was moved to OCA/mis-builder#7
