### ISSUE TITLE
[9.0] - Customer Outstanding Statement : does not work with child customers

### ISSUE THREAD

**Issue by mslokhat** [OCA/account-financial-reporting#299]
Hi,
i have setup one parent company and 2 sub companies
when invoicing to the sub companies , the statement show any data
i have to choose the parent company to be able to view outstanding invoices
but i cannot separate the invoices as per the sub companies ( i should have 3 statement)
Rgds

**Comment by MiquelRForgeFlow** [comment]
These reports only consider receivables, so it is normal that the invoices of the company are seen only in the report of the company. In your case, the sub companies are just customers.
If you think I am not answering what you are asking, please clarify your issue and/or put an example.
Regards

**Comment by mslokhat** [comment]
![image](https://cloud.githubusercontent.com/assets/8535048/25341709/cdeba326-291a-11e7-858f-d3114591f543.png)

![image](https://cloud.githubusercontent.com/assets/8535048/25341731/e24de4be-291a-11e7-8ebb-a5e17c66b04d.png)
[Statement Action to PDF.pdf](https://github.com/OCA/account-financial-reporting/files/952031/Statement.Action.to.PDF.pdf)


BBB and CCC are sub companies of AAA
i have invoiced (validated) the 2 companies 103.50 and  20.70

i have to go to parent companies AAA to view the pending invoices 

[Statement Action to PDF (2).pdf](https://github.com/OCA/account-financial-reporting/files/952054/Statement.Action.to.PDF.2.pdf)

**Comment by MiquelRForgeFlow** [comment]
These two sub companies BBB and CCC are just two contacts. These contacts work for the company AAA and so all the invoices go the the account of receivables that the company has. You can go and check the partner assigned to the journal items created by invoices for BBB and CCC.

**Comment by mslokhat** [comment]
Ok, i see them allocated to AAA. any idea how to allocate them to BBB and CCC? maybe i have used odoo wrongly

**Comment by mslokhat** [comment]
found it ,
Thanks , you can close this issue
