### ISSUE TITLE
[10.0] How to translate for user language

### ISSUE THREAD

**Issue by clxadmin** [OCA/account-financial-reporting#302]
can not find the way to translate the menus and content of charts to users language

there is no technical translation visible with 'settings' - technical translations

**Comment by sbidoul** [comment]
How does this issue relate to the code in this repository? This looks like a generic Odoo question, therefore I'm closing it and recommand you post it to community@odoo.com. Feel free to reopen if it is a bug in one of the OCA modules.

**Comment by clxadmin** [comment]
It's more like the translation files to this module do not work as usual -- all languages mixed up, missing labels etc... You can easely reproduce this by just install the module on a fresh Odoo 10

thats why I thought it is related to this module
