### ISSUE TITLE
account_financial_report_webkit wrong Initial Balance 

### ISSUE THREAD

**Issue by Maurice67205** [OCA/account-financial-reporting#304]
When requesting a Partner Balance report for FY2015, the initial balance is retrieved from an entry in an opening period which is not in FY2015 but rather FY2016 or FY2017 depending on the data
Therefore the Partner Balance report is not in line with the Balance View on the screen

**Comment by mquandalle** [comment]
Indeed, it seems to me that accounting moves registered in opening/closing journals aren't taken into account.

**Comment by Maurice67205** [comment]
Hello let me be more accurate
In the partner_balance.py code there is a comment saying 
"Force computing of initial balance for the partner balance,
        because we cannot use the entries generated by
        OpenERP in the opening period."
But the balance computation for FY-1 is false because it ads somehow the same amounts as the one that are registred in the FY opening period.
As I'm not a programmer I cannot say more on this issue

**Comment by Maurice67205** [comment]
After further review, there was a wrong data in the database 
An account_move_line had a date='2017-02-28' where it should be '0217-02-28'; 
We corrected this wrong entry and reports are fine now.
So there was no bug in the code itself
