### ISSUE TITLE
[9][10] OCA Reports doesn't work properly when filtering by accounts (receiv/payab options)

### ISSUE THREAD

**Issue by amcor** [OCA/account-financial-reporting#314]
Module **account_financial_report_qweb**

There's an error when selecting payable/receivable boolean options. I think the problem is on the onchange function, the onchange works well in view, but when printing it does not work, and all accounts are printed.

(I've checked general ledger and partner balance reports and it's wrong in both)

**Comment by omar7r** [comment]
Check this issue https://github.com/odoo/odoo/issues/14761
Meanwhile you can change the widget of account_ids field to many2many_tags, but we need a solution for the many2many widget bug if it was loaded from on_change.

**Comment by amcor** [comment]
Thanks omar!! It's a temporal fix but at least it's working now. I'll be waiting the final solution to this bug.
