### ISSUE TITLE
ReferenceError: pyeval is not defined

### ISSUE THREAD

**Issue by m3asmi** [OCA/account-financial-reporting#331]
version **10.0**

When I  click **Export XLSX** on the **General Ledger**  I get the error : **pyeval is not defined**

![screenshot from 2017-06-23 11-40-12](https://user-images.githubusercontent.com/7910752/27480752-df4a724c-5808-11e7-81e4-83d06791aea1.png)

is there a bug addons ?

**Comment by pedrobaeza** [comment]
Please try again in runbot, and if you are able to reproduce the error, indicate the steps to reproduce it.

**Comment by pedrobaeza** [comment]
I close this meanwhile.
