### ISSUE TITLE
Issue in Qweb financial report windows 10 odoo 10- relation does'nt exist !!

### ISSUE THREAD

**Issue by DidierLACOMBE** [OCA/account-financial-reporting#340]
hello

I got the following error

ProgrammingError: ERREUR:  la relation « report_general_ledger_qweb » n'existe pas
LINE 1: INSERT INTO "report_general_ledger_qweb" ("id", "centralize"...

I have install xlsxwriter in python 2.7 no changes

can someone help thanks

**Comment by pedrobaeza** [comment]
You must update the module in Odoo.

**Comment by DidierLACOMBE** [comment]
hello 

that's OK it works after updating module
thanks
