### ISSUE TITLE
[mis_builder] extended account selectors

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-financial-reporting#345]
Accounting expressions in mis_builder have the form

`(bal|crd|deb)(p|i|e)[account selector]([optional move line domain])?`

The account selector is currently based on account codes (eg `70%`).

Further account filtering can be added in the move line domain, eg `('account_id.type', '=', ...)`. But that is slow because additional database queries must be done, whereas the account selector boils done to one `read_group` per period and move line domain.

So it is desirable to avoid using the move line domains to filter on accounts.

To implement this, the account selector can be extended to support any domain on gl accounts.

**Comment by JordiBForgeFlow** [comment]
We use mostly gl account tags. And can only use donain selection now, which
makes it slow. Would be great that tags was in the selecion options, to
make searches faster.

**Comment by sbidoul** [comment]
> Would be great that tags was in the selecion options 

Absolutely! So you will be able to write `balp[('tag_ids.name', '=', '...')]`.

On a related topic, optimizing selection on taxes would be interesting too, so you could write an efficient tax report with mis_builder.

**Comment by sbidoul** [comment]
This issue was moved to OCA/mis-builder#4
