### ISSUE TITLE
8.0 - Aged Open Invoices from/to date does not take into account open invoices before from date

### ISSUE THREAD

**Issue by jbaudoux** [OCA/account-financial-reporting#347]
Hello,
I cannot find a way to render open invoices of e.g. year 2016.
The amount never matches the partner balance (from partner balance report or opening entry).
In the report Aged Open Invoice you can filter from/to. When I select from 1/1/2016 to 31/12/2016, it renders all open invoices from 2016 + invoices before 2016 where there was a payment. However it does not include the open invoices created before 2016 and that are still open in 2016 as no payment occurred in 2016
Is there a reason why the aged open invoice behave like that? How to get the list of invoices that explains the partner balance?
Thanks
J-E

**Comment by jbaudoux** [comment]
@luc-demeyer @alexis-via @pedrobaeza @sbidoul Dear all, any experience on this reported issue? Thanks. Kind regards, J-E

**Comment by jbaudoux** [comment]
Here is PR that could solve the issue: https://github.com/OCA/account-financial-reporting/pull/362

**Comment by pedrobaeza** [comment]
Sorry, version too old for me already...

**Comment by sbidoul** [comment]
Sorry I don't know. The expert on the topic is probably @fclementic2c.

**Comment by luc-demeyer** [comment]
There is to my knowledge no OCA module that covers your request in all cases.
You can download the 'account_open_receivables_payables_xls' module from apps.odoo.com or https://github.com/luc-demeyer/noviat-apps/tree/8.0.

That module solves the issue that you have.

**Comment by jbaudoux** [comment]
Here is second PR that solves another issue with reconciliation date: https://github.com/OCA/account-financial-reporting/pull/369

With the PR https://github.com/OCA/account-financial-reporting/pull/362 and https://github.com/OCA/account-financial-reporting/pull/369, now the report provides the right lines and the totals on client/supplier accounts in the open invoices report match the amount of the balance sheet.

**Comment by pedrobaeza** [comment]
As there are opened PRs, I close this issue.
