### ISSUE TITLE
[mis_builder] multi currency support

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-financial-reporting#350]
Preliminary work exists in https://github.com/acsone/account-financial-reporting/pull/16 and https://github.com/acsone/account-financial-reporting/pull/22.

Some calculations are not efficient enough to be included as is.

#295 must be implemented first.

**Comment by Martronic-SA** [comment]
We should also have an average rate on period (fiscal year) frequently used in P&L consolidated

**Comment by sbidoul** [comment]
This issue was moved to OCA/mis-builder#3
