### ISSUE TITLE
[11] account_tax_balance depends on module date_range which is not yet in v11

### ISSUE THREAD

**Issue by jalzaga** [OCA/account-financial-reporting#375]
the v11 module account_tax_balance depends on module date_range which is not  yet in v11

**Comment by pedrobaeza** [comment]
That's not true. See the repository split.

**Comment by jalzaga** [comment]
OK, thank you @pedrobaeza now it is in the repository https://github.com/OCA/server-ux, I couldn't find it directly, I didn´t see a specific reference in the original repository, ¿is there any direct way?

**Comment by pedrobaeza** [comment]
Check always migration issue: https://github.com/OCA/server-tools/issues/1008
