### ISSUE TITLE
[8.0]translation files for unexisting modules. mis_builder.

### ISSUE THREAD

**Issue by AaronHForgeFlow** [OCA/account-financial-reporting#376]
Transifex seems to create translations files for previously existing modules in this repo, e.g. mis_builder. For some reason odoo server is not able to locate those modules when the addons path in the config file refers to this repo before mis_builder repo.

**Comment by pedrobaeza** [comment]
We have to manually remove that translations from Transifex. Doing...

**Comment by pedrobaeza** [comment]
Done.
