### ISSUE TITLE
[odoo 10] 	account_financial_report_qweb not workig , this error appears

### ISSUE THREAD

**Issue by fgarcia-humanoide** [OCA/account-financial-reporting#381]
Hy,

When launching general ledger of the oca reports, this error appears:

  File "/opt/odoo/odoo-server/odoo/modules/registry.py", line 178, in __getitem__
    return self.models[model_name]
KeyError: 'report_general_ledger_qweb'

Same with other reports

 File "/opt/odoo/odoo-server/odoo/modules/registry.py", line 178, in __getitem__
    return self.models[model_name]
KeyError: 'report_trial_balance_qweb'

all the dependencies are met

**Comment by pedrobaeza** [comment]
You haven't installed it correctly, updated or restarted the service.
