### ISSUE TITLE
Naming issue on Financial Reports module. 

### ISSUE THREAD

**Issue by feketemihai** [OCA/account-financial-reporting#394]
We have a naming issue on account_financial_report, the module already exists in Odoo Apps, done by Vauxoo on version before 7.0:
https://www.odoo.com/apps/modules/7.0/account_financial_report/
That's why the module doesn't appear in apps store.
How can we treat this one?
@mreficent @jbeficent @pedrobaeza @moylop260 @nhomar

**Comment by JordiBForgeFlow** [comment]
@nhomar, seems that you have discontinued this module after v6.1. Could you remove from the app store?

**Comment by pedrobaeza** [comment]
I think he can't simply remove the module, but ask to the Apps responsibles to change the owner somehow.

**Comment by JordiBForgeFlow** [comment]
In any case, @nhomar would you agree? Can we mail to Odoo and put you in copy?

**Comment by hbto** [comment]
I @hbto Agree on renaming the module on behalf of @nhomar 
endorse my decision @moylop260 

Regards

**Comment by moylop260** [comment]
👍

**Comment by JordiBForgeFlow** [comment]
Thank you guys!

**Comment by JordiBForgeFlow** [comment]
Let us know when you have done so, and we'll oversee if the issue is resolved in the next days.

**Comment by feketemihai** [comment]
@nhomar @hbto @moylop260 Thanks for your quick reaction and decision. Hope you will use the module on newer versions..

**Comment by pedrobaeza** [comment]
I think you have to start the request to Apps Manager from your side...

**Comment by nhomar** [comment]
sorry for the delay, I will ask for the app manager to be removed.

**Comment by JordiBForgeFlow** [comment]
They have already fixed https://www.odoo.com/apps/modules/11.0/account_financial_report/
