### ISSUE TITLE
[10] customer_activity_statement - report cannot be used as email attachment 

### ISSUE THREAD

**Issue by seancallahan88** [OCA/account-financial-reporting#395]
The CustomerActivityStatement report cant be emailed: if you add it to an email template for res.partner it wont call '_prepare_activity_statement' (function is in the wizard) so 'data' in 

`def render_html(self, docids, data):
        data = {
            'date_start': str(date.today() - timedelta(days=120)),

            'date_end': str(date.today()),

            'company_id': self.env.user.company_id.id,

            'partner_ids': self._context['active_ids'],

            'show_aging_buckets': True,

            'filter_non_due_partners': True,

        }
        company_id = data['company_id']

        partner_ids = data['partner_ids']

        date_start = data['date_start']

        date_end = data['date_end']

        today = fields.Date.today()`

will be None.

I tried fixing by having a condition if data None:

`        data={

            'date_start': str(date.today()-timedelta(days=120)),

            'date_end': str(date.today()),

            'company_id': self.env.user.company_id.id,

            'partner_ids': self._context['active_ids'],

            'show_aging_buckets': True,

            'filter_non_due_partners': True,

        }`

But I found it emailed every partners statement to every partner (generating it again each time). I assume it is to do with `self._context['active_ids'],`  Anyone have any ideas?

**Comment by gdgellatly** [comment]
@seancallahan88 Just call _prepare_activity_statement

https://github.com/odoonz/odoonz-addons/blob/ac8ca60527eb52d9d2b1de5ae87db4729c9d5bfd/customer_activity_statement_monthly/report/customer_activity_statement.py#L32

**Comment by cvinh** [comment]
@tglukhov
