### ISSUE TITLE
Aged Partner Balance - Invoice Date

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/account-financial-reporting#396]
Hi,

Should the aged partner balance not be on invoice date instead of due date? 

The term aged balance already tells us that we want an aged balance, not an overview on how long an invoice is due. I think it's standard accounting to calculate age on the invoice date:

https://www.reviso.com/accountingsoftware/accounting-words/customer-balance-list
https://www.accountingtools.com/articles/what-is-accounts-receivable-aging.html
https://www.investopedia.com/terms/a/accounts-receivable-aging.asp

An outstanding invoice is different than a due invoice, we want to base it on outstanding invoices.

Thank you.
Cas

**Comment by pedrobaeza** [comment]
I don't think so. We want to know when is payment expected.
