### ISSUE TITLE
Module account_financial_report changes fonts in backend

### ISSUE THREAD

**Issue by dynapps** [OCA/account-financial-reporting#398]
This is an issue in Odoo 11.
The stylesheet "report.css" inherits from web.assets_backend. This causes a change in the default font everywhere in the Odoo backend, because of this section:
body, table, td, span, div {
    font-family: Helvetica, Arial;
}
Shouldn't the stylesheet inherit from report_assets_common instead?
Because the font is changed to Helvetica in the backend, this has an impact when you try to edit an XML view. Because the font is wrong, the cursor you see doesn't match the actual position of the cursor. This makes it impossible to edit a view! (see example in attachment)
![selection_001](https://user-images.githubusercontent.com/14269909/37597836-cc0e1bec-2b80-11e8-8dbd-49d886df7c3c.png)

**Comment by feketemihai** [comment]
@dynapps @pedrobaeza @jbeficent I update it locally, i am trying to improve report styles, and i will push after. 

@dynapps You can change first style block with: 
.body, .table, .td, .span, .div {
    font-family: Arial,Helvetica,sans-serif;
}
and it's solved.

**Comment by pedrobaeza** [comment]
OK, thanks!

**Comment by dynapps** [comment]
@feketemihai Thank you for the quick follow-up! I do wonder if the font of all the screens should be updated in this module, because it seems to me that the module is meant for reports. So I'm hesitant to change the style block as you suggest. Or did you just wanted to offer a quick workaround?...

**Comment by feketemihai** [comment]
@dynapps By applying the modifications, the fonts will be restored as the Odoo one, and this will be loaded only the report...
