### ISSUE TITLE
Add foreign currency to Trial balance report

### ISSUE THREAD

**Issue by HviorForgeFlow** [OCA/account-financial-reporting#404]
Relating to #402 #403 

Is it worth that this report shows foreign currencies?

If there is an account with more than one foreign currency, I assume that in this kind of environments there will be an account to every specific foreign currency used, but if not, this report won't be useful.

I assume too that in high volatile currency exchange rate should be perform on the time operation is performed.

After doing some research I've found an interesting article:

[Conversion of Trial Balance from Foreign Currency to Reporting Currency | Financial Analysis](http://www.yourarticlelibrary.com/accounting/accounting-for-currency-transactions/conversion-of-trial-balance-from-foreign-currency-to-reporting-currency-financial-analysis/67565)

So the point is this reports should be aim as much as possible as an standard.   

I'll appreciate your feedback.

**Comment by fclementic2c** [comment]
Yes, definitely the balance in currency would be a great information on the trial balance... but on accounts with a secondary currency only.

**Comment by feketemihai** [comment]
@hveficent @fclementic2c From my side, i don't see it printed in foreign currency, in most of the case the balance won't match the amount in different currency, only after you launch the multicurrency reevaluation, so it can be a nice improvement, but not as default one, a checkbox in wizard, if you want to print it with foreign currency to check it.

**Comment by fclementic2c** [comment]
Yes as a display option is better.

**Comment by JordiBForgeFlow** [comment]
Question resolved. Closing.
