### ISSUE TITLE
Statements show wrong partner with multi company

### ISSUE THREAD

**Issue by thegunshow** [OCA/account-financial-reporting#417]
Hi

Using Odoo 11.0

There seem to be some problems when generating statements, the following problems have been found:
1. The wrong partner(company) details at the top of the statement, this happens regardless of the selection used.
2. When you sell to another partner, for instance, Company A creates a statement for Company B(both A & B are companies within the multi company), the statement will use Company B's details as if company B was sending out the statement.

Not sure how the filters/domains work?

Thanks
Brendan

**Comment by pedrobaeza** [comment]
Please put the detailed steps to reproduce the problem, preferable on runbot infrastructure for being reproducible again.
