### ISSUE TITLE
[9.0]QWeb Financial Reports: Entries quadrupled in German language!

### ISSUE THREAD

**Issue by treviser** [OCA/account-financial-reporting#418]
This is a very strange issue, which seems to affect all QWeb Financial Reports:

This is what should be correctly reported and also gets correctly reported when the user language preference is set to English:
![selection_049](https://user-images.githubusercontent.com/1814941/40228332-4691b984-5a91-11e8-80c2-0a3040f2b1b1.png)

This is what I get when I launch exactly the same report, but with the user language preference set to German DE:
![selection_048](https://user-images.githubusercontent.com/1814941/40228337-4b7ba09a-5a91-11e8-8bde-ee416277e311.png)

How is this possible?

Odoo Version: Version 9.0c-20180501 (Community Edition)
QWeb Financial Report version: latest (9.0.1.0.2)

**Comment by pedrobaeza** [comment]
Can you replicate it in runbot? Exact steps for replicating it?

**Comment by treviser** [comment]
How can I install the QWeb reports on runbot?

**Comment by pedrobaeza** [comment]
On our OCA runbot. Each repository has its own. There should be a button "Try me on runbot" on the README of the module.

**Comment by treviser** [comment]
I can not replicate it on runbot. So that is strange, where should I start to dig further?

**Comment by treviser** [comment]
New observation: It seems as this is related to the number of translation records per account. If an account has only one translation record, the german report is correct. But there are accounts, which have 3 translation records, and therefore we have 4 records in the report, 1 for the source term, and 3 more for the 3 translation lines.
Therefore this seems only to be possible for multilanguage chart of accounts, such as the Swiss chart of account.

**Comment by pedrobaeza** [comment]
Uhm, why these duplicated translation entries? Are you talking about l10n_multilang?

**Comment by treviser** [comment]
Yes, exactly, it is l10n_multilang

**Comment by pedrobaeza** [comment]
Well, it seems this is incompatible with that module then :(

@jcoux @jbeficent any idea of this?

**Comment by jcoux** [comment]
@pedrobaeza @treviser I don't know exactly the problem, and my first implementation don't consider languages, but that pull request:
https://github.com/OCA/account-financial-reporting/pull/227
has added features to translate names of accounts.

Like I see the code, I think if you duplicate translations for a same lang/account, maybe we have a problem. (Normally this case mustn't happen.)

Maybe it's not that, I don't know.
I hope that can be help you.

**Comment by pedrobaeza** [comment]
@jcoux thanks for the insights!

@lbeopennet you added this change, so please check the possible problems that has been notified here.

**Comment by treviser** [comment]
I have to further investigate on what exactly the issue could be...

**Comment by treviser** [comment]
I did test all possible permutations concerning language, translation field name and translation status.
My observation:
Account totals and account move lines appear (and are counted) as many times as a translation value for the "account.account,name"-field in the report user language exists.

Example: 
account.account,name = "Account Receivables" = source term
account.account,name = "Debitoren" = translated term in language German / Deutsch
second ir.translation entry:
account.account,name = "Debitoren" = translated term in language German / Deutsch
User preference settings of the user printing the report: German / DE

Resultat:
1) Each account move line is reported for each ir.translation entry (means 2 lines in our example)
2) This gives a subtotal of the correct amount multiplied with 2
3) The account total line is also reported for each ir.translation entry (means 2 totals per account, each with 2 move lines), in the end the reported total amount is 4 times the proper amount.

**Comment by pedrobaeza** [comment]
@treviser but the abnormal thing is that you have more than one translation term for each language. I think that's the problem.

**Comment by treviser** [comment]
@pedrobaeza I agree with you, but if I remember it correctly, it only came with Odoo 10.0 that it was not possible anymore to update the account translations by uploading another .po file, which I did in 2016 because of the many translation errors.
However, it seems strange to me to select and aggregate account moves based on account name translation entries.

**Comment by pedrobaeza** [comment]
Then remove that duplicated translation terms and all should go normal again. I don't think this can be easily reproduced in other environment except yours.

**Comment by treviser** [comment]
That's what we do now. But it might be helpful to know for others having manipulated their multilingual accounting localization.
