### ISSUE TITLE
[11.0] Feedback on hierarchy for account_financial_report

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-financial-reporting#419]
HI, @feketemihai @jbeficent, I would like to share with you several things after testing `account_financial_reporting` to see possible fixes/improvements:

* If you mark "Hide account ending balance at 0", indeed the accounts are hidden, but not their hierarchy parents, getting an ugly report:

![seleccion_010](https://user-images.githubusercontent.com/7165771/40270859-e7fc4254-5b94-11e8-9d01-08b88e0f54b3.png)

* The blue color and font gets a bit weird for seeing on PDF IMO.

* The option "Hierarchy On" Computed Accounts / Child Accounts gets without meaning, at least in our chart template. A help tooltip would help for knowing what is this.

* But the option I imagine for the hierarchy is the level of hierarchy to group (0 - no group, so the same as previously when no hierarchy exists, 1, 2, 3...) to specify the detail level.

* Another option is to simply not showing account, if you want a summary at one of the levels indicated before.

What do you think about this?

**Comment by pedrobaeza** [comment]
@feketemihai I haven't received any reply from you, and haven't seen you around for a while. Are you OK?

**Comment by lauracvilla-zz** [comment]
There is an option to get Hierarchy or Account Parents Information con Odoo 10 with account_financial_report? I like this module but I don't know how show parents account information on this module or how I need to create this accounts? Thanks for your help.

**Comment by pedrobaeza** [comment]
@lauracvilla no. Please don't hijack threads.
