### ISSUE TITLE
8.0 account_financial_report_webkit open invoices report broken when using Group Partner by currency

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-financial-reporting#42]
How to reproduce:

Enable the following checkbox in the Open Invoices report wizard:
![image](https://cloud.githubusercontent.com/assets/692075/5522808/5fdf625c-89bf-11e4-971a-1592cde7e625.png)

This is due to the method _group_lines_by_currency that is not migrated (it still tries to create a non-existant attribute grouped_ledger_lines).

I'm just reporting to warn about the bug presence, I have no time to fix it right now.

**Comment by pedrobaeza** [comment]
Is this still happening, @sbidoul ?

**Comment by sbidoul** [comment]
I dont know. No time to check, I'm not so much in 8 these days.

**Comment by pedrobaeza** [comment]
OK, let's close it then. If anyone hits this, he/she can open a new issue.
