### ISSUE TITLE
account_financial_report should override default odoo report from chart of account

### ISSUE THREAD

**Issue by fclementic2c** [OCA/account-financial-reporting#421]
account_financial_report should override default odoo report from chart of account

![screenshot-smartliberty odoo camptocamp ch-2018 05 28-13-43-00](https://user-images.githubusercontent.com/5735158/40613011-1519d8f2-627d-11e8-9076-8f616372d47e.png)

**Comment by pedrobaeza** [comment]
This has been achieved already and in v12, there's no such problem.
