### ISSUE TITLE
General Ledger can be computed only if selected company have only one unaffected earnings account.

### ISSUE THREAD

**Issue by jjordaan79** [OCA/account-financial-reporting#426]
Issue when trying to pull General Ledger report.

General Ledger can be computed only if selected company have only one unaffected earnings account.

No Errors in the log.

**Comment by fanha99** [comment]
in your chart of account, (**Accounting / Configuration / Chart of Account**), select one account and set account type to "**Current Year Earnings**"

**Comment by pedrobaeza** [comment]
Yeah, this is not an Odoo issue, but configuration question, and @fanha99 has gently already answered you, so closing this.

**Comment by MOGwebz** [comment]
Hi Actually still after doing as prescribed as @fanha99 still getting the same error

**Comment by ivanporras** [comment]
Hello @MOGwebz, I have the same issue, Could you fix it? I have only Current Year Earnings account but behavior is the same. 
![Screenshot(20)](https://user-images.githubusercontent.com/13451948/62825275-d53f4180-bb6e-11e9-9025-5a3c0954e15e.png)

**Comment by PyaePhyoKhant** [comment]
There should be **exactly one** account with type "Current Year Earnings".
```
@api.onchange('company_id')
def onchange_company_id(self):
    """Handle company change."""
    account_type = self.env.ref('account.data_unaffected_earnings')
    count = self.env['account.account'].search_count(
        [
            ('user_type_id', '=', account_type.id),
            ('company_id', '=', self.company_id.id)
        ])
    self.not_only_one_unaffected_earnings_account = count != 1
```

**Comment by santcosta** [comment]
Is it normal for this account to have a balance? When  i print the ledger
