### ISSUE TITLE
account_financial_report_qweb: CSS conflicts with backend

### ISSUE THREAD

**Issue by yajo** [OCA/account-financial-reporting#430]
STR:

1. Install odoo 10.
1. Install `account_financial_report_qweb`
1. Go edit some view in configuration > Technical > user interface > views.

Problem: Fonts should be monospace, but are Helvetica:
![captura de pantalla de 2018-06-25 12-43-39](https://user-images.githubusercontent.com/973709/41848633-f7071564-7875-11e8-8416-b1208c9389b4.png)

I'd say this addon is injecting some report-only layout fixes in backend client.

@Tecnativa

**Comment by pedrobaeza** [comment]
@jbeficent was it you who changes this?

**Comment by pedrobaeza** [comment]
@Yajo are you able to fix it?

**Comment by yajo** [comment]
I guess so, but the problem is that I don't really know what that addon does, and I saw it includes report things (expected) and backend widgets (not expected). I'm not sure if moving the CSS to reports only would break the widgets...

I guess that somebody that actively uses the addon could be better off fixing it, but yes, I could try anyways.

**Comment by pedrobaeza** [comment]
@jbeficent please help here at least to answer @Yajo's question.

**Comment by HviorForgeFlow** [comment]
On statics/css/src/*.css there is a definition on top about font usage, in
that case Helvetica or Arial, removig that css definition would be
sufficient to display fonts as default/¿monospace?

**Comment by yajo** [comment]
I think the bigger problem is including report css files in backend assets, isn't it?

**Comment by HviorForgeFlow** [comment]
Yes, I noticed in v11 is happening too.

**Comment by HviorForgeFlow** [comment]
Solved with #437 waiting FF in #436 
Issue should be closed after that

**Comment by pedrobaeza** [comment]
Already solved
