### ISSUE TITLE
odoo [8]

### ISSUE THREAD

**Issue by fgarcia-humanoide** [OCA/account-financial-reporting#442]
Error when using webkit reports

  | execv() arg 2 must contain only strings<type 'exceptions.TypeError'>,execv() arg 2 must contain only strings,<traceback object at 0x7f7bb0ad2ea8>
-- | --

**Comment by fgarcia-humanoide** [comment]
Works fine exporting to excel , the problem appears when printing pdf.

**Comment by sbidoul** [comment]
Looks similar to #200, can you please check the workaround there?

**Comment by fgarcia-humanoide** [comment]
Solved restoring the database in another odoo 8 instalation. The difference was:
in ubuntu 14.04 does not work
in ubuntu 16.04 works fine
