### ISSUE TITLE
SQL error in report/abstract_report.py

### ISSUE THREAD

**Issue by open-net-sarl** [OCA/account-financial-reporting#459]
Hi

We've had a flood of error messages while updating a database, caused by an SQL error in the file **_account_financial_report/report/abstract_report.py_**, line 18: 
"self.create_date" not understood by Odoo

Thanks in advance.

**Comment by astirpe** [comment]
Fixed in https://github.com/OCA/account-financial-reporting/pull/465.
This issue can be closed.
