### ISSUE TITLE
odoo [11] account-financial-reporting Trial balance does show acounts properly ordered

### ISSUE THREAD

**Issue by fgarcia-humanoide** [OCA/account-financial-reporting#463]
odoo [11] account-financial-reporting Trial balance does show acounts properly ordered

expected behaviour:

197
199
200

actual behaviour:
goes from 199 to 60
![capturasumasysaldos](https://user-images.githubusercontent.com/7599709/45702182-72694400-bb71-11e8-8c9a-338a79c2e2a5.JPG)

**Comment by fgarcia-humanoide** [comment]
In Spain, we are used to a trial balance ordered by numbers and not grouped as balance sheet.

**Comment by pedrobaeza** [comment]
That's because you have incorrect group assigned to that accounts.

**Comment by lili94** [comment]
hi @fgarcia-humanoide  and @pedrobaeza  i have the correct group assigned to the account but i have incorrect order
![Inkedscreencapture-localhost-8069-web-2019-04-08-09_19_58_LI](https://user-images.githubusercontent.com/32308220/55709271-dc4b1d00-59df-11e9-84de-5358baa18961.jpg)

**Comment by dfragni** [comment]
![image](https://user-images.githubusercontent.com/50833152/58023283-b9984200-7b0f-11e9-848f-42df4dffac23.png)

Same here, why the 4 is between the 1 and the 2 ?
