### ISSUE TITLE
[9.0][10.0][11.0] Customer Outstanding Statement - error when attaching to partner mass mail

### ISSUE THREAD

**Issue by cierek** [OCA/account-financial-reporting#488]
customer_outstanding_statement 
Hi,

When I am trying to attach it to the "Partner Mass Mailing" it gives me the following error:
  File "/odoo11/custom/addons/customer_outstanding_statement/report/customer_outstanding_statement.py", line 325, in get_report_values
    company_id = data['company_id']
TypeError: 'NoneType' object is not subscriptable

Video: https://youtu.be/f0aAkMeAm_U

How would you solve this?

**Comment by gdgellatly** [comment]
@cierek It is resolved in v12, not sure about prior versions. The problem is it is a wizard not a report.

**Comment by cvinh** [comment]
@tglukhov can you confirm ?
