### ISSUE TITLE
[10.0] account_financial_report_qweb: huge performance issues when trying to compute trial balance for all partners

### ISSUE THREAD

**Issue by Cedric-Pigeon** [OCA/account-financial-reporting#492]
On a huge database, the computation of the report takes more than 18 minutes for this request:
![image](https://user-images.githubusercontent.com/7813258/50221855-cbc25880-0396-11e9-9bc2-f318393651e4.png)

Because of an empty filter on partner I enter this line https://github.com/OCA/account-financial-reporting/blob/10.0/account_financial_report_qweb/report/general_ledger.py#L253

I have 2 questions. Does anyone know:

- why we call twice `self._inject_partner_values(`
- what is supposed to do the `only_empty_partner` parameter

if I comment lines 252 and 253, the report is correctly generated within a reasonable time.

**Comment by Cedric-Pigeon** [comment]
@jcoux I think you can help me as you wrote the code on which I have questions through this commit https://github.com/OCA/account-financial-reporting/commit/9ad59f8a2b40b1ad2d9b70a05b192c260dccf80a

**Comment by pedrobaeza** [comment]
Without the intention of offending anyone, this module, getting things with SQL by the fear of being slower than with ORM, is a total mess that has grown very badly. Getting things with `read_group` would have the same performance and be far more readable. I want to refactor this for v12.

**Comment by fclementic2c** [comment]
jcoux is off for few weeks.

The idea of using SQL was to avoid memory errors, as we used to have in previous versions, even for longer reports. Saying that, I am not competent to judge this.

**Comment by Cedric-Pigeon** [comment]
@fclementic2c Thanks, my concern is not about SQL but more about the method called ;-)

**Comment by pedrobaeza** [comment]
Yes, sorry for the offtopic, but each of the problems arisen in this module are a total pain to be debugged/solved due to this SQL thing.

About memory usage, I'm sure with `read_group` it's not a problem. I'll tell in v12.

**Comment by Cedric-Pigeon** [comment]
I just upgraded to last version and the problem seems to be fixed. Sorry
