### ISSUE TITLE
[11] Non zero still show zero

### ISSUE THREAD

**Issue by Vartkat** [OCA/account-financial-reporting#496]
Odoo 11.
Ubuntu 16

Even if I check the box saying 'only non zero accounts' the reports (Trial Balance and General Ledger) are showing zero lines (even some with -0.00).
If I look into my database I see that some numbers are stored as '-24.900000000000002'.
My decimal precision is set to two digits. So when a calculation is made, it sure end with something like 0.000000002' which is obviously not zero, but as the report only shows two digits.... You got the idea.

Did I miss something in my setup ? 
As I'm not using multi-currency, I don't see any settings for currency decimal.
Shouldn't it be this module role to get the decimal precision and consider zero anything infinitesimal less than a tenth of the precision digit ?

Thanks for your help

Regards
V

**Comment by pedrobaeza** [comment]
I can confirm this. @jbeficent do you know where to touch for this?

**Comment by pedrobaeza** [comment]
Fixed in https://github.com/OCA/account-financial-reporting/commit/5924c5c718c271a4bde7ed65445fed9b1eb986b1
