### ISSUE TITLE
10.0 Historial

### ISSUE THREAD

**Issue by lauracvilla-zz** [OCA/account-financial-reporting#510]
Hi,
For some account this situation is happening:

Example:
January Report:
Account1 
Initial balance: -5
Debit: 5
Credit: 0
Period balance: 5
Ending Balance: 0

February Report:
Account1 
Initial balance: -5
Debit: 0
Credit: 0
Period balance: 0
Ending Balance: -5

The report is not taking the Ending balance for the next month.

**Comment by pedrobaeza** [comment]
This is working AFAIK, so please try on runbot and tell back if still happening. Closing meanwhile.
