### ISSUE TITLE
Odoo [9][10] missing data for 9999 profits/losses on first year and follow up years have wrong amounts

### ISSUE THREAD

**Issue by clxadmin** [OCA/account-financial-reporting#511]
I'm writing here to first thank the people from OCA for the great work, making Odoo Community to this great solution :-)

I'm facing some issues with the module account_journal_report with V9 / V10. I can reproduce the same behavior on your runbot with a simple sample. Please have a look to the attached screenshots explaining the two issues:

first year 2016 (starting accounting) - missing profit/losses at account 9999
![profit-loss-16-oca](https://user-images.githubusercontent.com/9445285/51600027-513ea880-1f01-11e9-8abc-5a6d9f639065.png)

followup year 2017 - wrong computed amount for profit/losses at account 9999
![profit-loss-17-oca](https://user-images.githubusercontent.com/9445285/51600198-bc887a80-1f01-11e9-83a3-01e6df720284.png)

is this a known problem? Can someone guide me with a workaround?

**Comment by pedrobaeza** [comment]
The behavior has been improved for showing more why computations are done that way, so closing this.
