### ISSUE TITLE
 [11.0] account_financial_report: General ledger - Total ending balance does not take into account filtered partners

### ISSUE THREAD

**Issue by pedroortega-punt** [OCA/account-financial-reporting#515]
In the general ledger report that is normally used to extract the statement to the client or supplier, it is not normal to indicate the balance of the general accounts, in the case of selecting a general account it should be normal, but not selecting a company .

![imagen](https://user-images.githubusercontent.com/18347857/52176978-f50a3d00-27ba-11e9-8e96-3a3bd28c32b8.png)

Ledger companies:
Is there any other business strategy with initial balances and movements?

**Comment by JordiBForgeFlow** [comment]
@vipvalen When you want to send the statement of activity to customers of suppliers you should use https://github.com/OCA/account-financial-reporting/tree/11.0/customer_activity_statement

**Comment by farazbdm** [comment]
I believe when general ledger is extracted with tick on 
show partner
The generated report should not have total line for the account, as expected result is only concerning particular partners
