### ISSUE TITLE
[10.0] VAT Report missing !

### ISSUE THREAD

**Issue by OthmaneGhandi** [OCA/account-financial-reporting#522]
You mentioned in README of V10 that there is a VAT report, but I didn't find it 
Am I missing someting ?
Thanks

**Comment by fclementic2c** [comment]
mmm. I think this is a newly added report. I saw it on version 12 - not 11.

**Comment by pedrobaeza** [comment]
The report is present AFAIK in 10.0 and 11.0 (12.0 module is not yet migrated). Please check in the proper section (OCA financial reports).

**Comment by fclementic2c** [comment]
for Odoo12 there is this PR not merged yet but very much operational (except pdf export still a bit ugly): https://github.com/OCA/account-financial-reporting/pull/509

**Comment by farazbdm** [comment]
@pedrobaeza 
the VAT report is not available in the OCA reports Menu.
in Odoo 10.0 i even checked in the menu lists.
