### ISSUE TITLE
Trial balance

### ISSUE THREAD

**Issue by mannoble** [OCA/account-financial-reporting#523]
An account with current earning type it's opening balance shows more value than actual at initial balance section.

**Comment by pedrobaeza** [comment]
Sorry, but this is working fine on my end. Try on runbot and put a video/screenshots to demonstrate the problem you are talking about.

**Comment by mannoble** [comment]
![one](https://user-images.githubusercontent.com/9113379/54669019-61d65e00-4b01-11e9-912e-09cb1060b297.PNG)
This is an openining balance for this account on 10/102018
the Excel trial balance report is showing below 
![two](https://user-images.githubusercontent.com/9113379/54669079-829eb380-4b01-11e9-8bab-2be398f31105.PNG)
However, Odoo default trial balance report is showing the exact amount

**Comment by pedrobaeza** [comment]
You are not mentioning even Odoo version and it seems you haven't got latest code version.

**Comment by mannoble** [comment]
Am working on version 10 and Account_financial_reporting version is '10.0.1.5.2'
