### ISSUE TITLE
PDF PRINT ERROR V11

### ISSUE THREAD

**Issue by lili94** [OCA/account-financial-reporting#525]
hi, when i print repport in pdf i get this , the repport not inline please help
![Capture](https://user-images.githubusercontent.com/32308220/54881636-21087d00-4e52-11e9-8264-74fbd54a6c70.PNG)

**Comment by pedrobaeza** [comment]
The screenshot is the PDF? Please try on runbot to reproduce the problem.

**Comment by lili94** [comment]
yes, the screenshot from pdf that i got after print , in runbot work perfect but in my local i got these

**Comment by pedrobaeza** [comment]
Then it's a problem in your configuration (check report.url system config parameter).
