### ISSUE TITLE
Could not find client action 'account_financial_report_backend'.

### ISSUE THREAD

**Issue by lili94** [OCA/account-financial-reporting#526]
hi, after installation of module and try it , when i click in view button i got these error "Could not find client action 'account_financial_report_backend'."
i didin't inderstand what is mean pleas help

**Comment by pedrobaeza** [comment]
It seems you haven't installed the module properly. Try to restart Odoo service and make sure everything is properly update. Any way, this is not an issue of the module itself, so closing.

**Comment by lili94** [comment]
restart server work for me thanks
