### ISSUE TITLE
show Cmputing entry befor calculate  initial balance 

### ISSUE THREAD

**Issue by lili94** [OCA/account-financial-reporting#528]
hi can anyone help me to calculate all entry than calculate the price off all entry with initial balance
thanks

**Comment by pedrobaeza** [comment]
Sorry, this is not an issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups, https://odoo-community.org/groups), but not here.

Closing this by the reason above.
