### ISSUE TITLE
FILTER WITH PARTNER SHOW NOTHING

### ISSUE THREAD

**Issue by lili94** [OCA/account-financial-reporting#529]
HI WHEN THE ACCOUNT OF PARTNER IS IN DEBIT AND MAKE THE FILTER PARTNER ON HIM D'ONT WORK JUST WITH COMPTE WORK

**Comment by pedrobaeza** [comment]
Sorry, but the steps to reproduce the problem are not completed to understand the problem. And please don't write everything in upper.

**Comment by lili94** [comment]
hi,sorry for write everything in upper.My problem is when i filter by partner when the account is credit account is work perfect but when the account is debit account nothing show

**Comment by pedrobaeza** [comment]
Debit account? That doesn't exist... Put the detailed steps to reproduce the problem, with screenshots if needed.

**Comment by lili94** [comment]
thanks i fix it, the solution is that to show the detail when filter by partner ,it must have the same account in partner because i change chart of accounts thanks
