### ISSUE TITLE
Porting account_chart_report, account_move_line_report_xls and account_journal_report_xls

### ISSUE THREAD

**Issue by JehoG** [OCA/account-financial-reporting#53]
Hello,
I'll be porting those three modules for V8:
account_chart_report,
account_move_line_report_xls
account_journal_report_xls

Is there anyone already working on that?
Guillaume

**Comment by sbidoul** [comment]
account_journal_report_xls is in progress in #28

**Comment by JehoG** [comment]
PR of account_chart_report: #54

**Comment by ovnicraft** [comment]
This question was solved, need to close this.
