### ISSUE TITLE
show date _range_id in report general ledger

### ISSUE THREAD

**Issue by lili94** [OCA/account-financial-reporting#531]
hi, i want to show date range_id in general ledger put i got it empty please help

**Comment by pedrobaeza** [comment]
I don't get what is the issue you have. Are you talking about custom development?

**Comment by lili94** [comment]
hi, thanks for replay i want to show the date range on
![Capture6](https://user-images.githubusercontent.com/32308220/55323387-de106000-5476-11e9-836c-73bd4e197155.PNG)
 the form in my genral ledger because it was my fiscal year
![Capture7](https://user-images.githubusercontent.com/32308220/55323431-f84a3e00-5476-11e9-8a4d-374021d1a773.PNG)

**Comment by pedrobaeza** [comment]
You already have the date interval just below in "Plage de dates". That's what is done right now. Other things will require development.

**Comment by lili94** [comment]
it s mean that i can't add 2019 in title of my report

**Comment by pedrobaeza** [comment]
Not right now.

**Comment by lili94** [comment]
ok thanks for help
