### ISSUE TITLE
[10.0] account_financial_report_qweb: trial balance

### ISSUE THREAD

**Issue by omarshatnawi39** [OCA/account-financial-reporting#532]
In the Trial Balance Report when i set the field (Hide accounts at 0) is True

the result in report remove lines if credit equal debit only 

for Example: i have tow account is (Initial balance greater than zero) and (credit equal debit) it is removed from report

i think the solve in
general_ledger.py Lines 555 to 559 
and function: _get_final_account_sub_subquery_sum_amounts

Thanks for the great reports

**Comment by pedrobaeza** [comment]
Are you using latest code version?

**Comment by omarshatnawi39** [comment]
Yes, the code was downloaded yesterday

**Comment by pedrobaeza** [comment]
@jbeficent didn't you fix this on the past?
