### ISSUE TITLE
openning debit/credit for initial balance

### ISSUE THREAD

**Issue by lili94** [OCA/account-financial-reporting#533]
hi, i want in trial balance , initial balance make separation between debit and credit 
if debit in case debit /if credit in case credit 
please help

**Comment by pedrobaeza** [comment]
And again your issues description is not very understandable, but issues are for notifying bugs, not for asking questions.

**Comment by lili94** [comment]
hi when i try to call initial debit from general ledger account in trial balance account line i got these error thanks

**Comment by lili94** [comment]
i fixe it by make condition initial_balance  <0
