### ISSUE TITLE
ending cumul in trial balance

### ISSUE THREAD

**Issue by lili94** [OCA/account-financial-reporting#535]
hi trial balance don't show ending cumule . i want to show total of credit and debit

**Comment by pedrobaeza** [comment]
Please, more information, screenshots, etc. It's impossible to deduce the issue, although again I think this is only a feature request.

**Comment by lili94** [comment]
hi @pedrobaeza  i change the trial balance to make it withe 6 colomun , now i wont to the sum of account group come after  the line and make total in the end of page to each colomun
![screencapture-file-C-Users-Asmaa-Downloads-Trial-Balance-24-pdf-2019-04-08-08_42_45](https://user-images.githubusercontent.com/32308220/55707247-0cdc8800-59db-11e9-82a4-c3ff89d713e9.png)

**Comment by lili94** [comment]
@pedrobaeza  can you help me please

**Comment by pedrobaeza** [comment]
Sorry but no, I haven't understood yet most of your issues and this is for notifying issues, not questions or feature requests
