### ISSUE TITLE
issue in configuration of server  on ubuntu

### ISSUE THREAD

**Issue by Brainoids001** [OCA/account-financial-reporting#538]
**When i give this code :** 

ns]
admin_passwd = odoo
db_host = False
db_port = False
db_user = odoo
db_password = FALSE
addons_path = /opt/odoo/addons
xmlrpc_port = 8069

I  got an error command not found 

What could be the possible solution ?
![error](https://user-images.githubusercontent.com/49274384/55860266-48b74f00-5b8d-11e9-8a72-c1d6e7a2bafe.png)

**Comment by pedrobaeza** [comment]
Sorry, but this is for issues with the modules of this repository, and this is not an issue nor related.
