### ISSUE TITLE
[11.0] wrong domain on wizard for partners 

### ISSUE THREAD

**Issue by fclementic2c** [OCA/account-financial-reporting#542]
We can only select contacts instead of companies on all OCA financial report 

![screenshot-c2c odoo camptocamp ch-2019 05 14-09-58-36](https://user-images.githubusercontent.com/5735158/57680909-ed1a2e80-762e-11e9-8726-b8b789c39f21.png)

**Comment by i-vyshnevska** [comment]
https://github.com/OCA/account-financial-reporting/pull/512

**Comment by MiquelRForgeFlow** [comment]
can be closed
