### ISSUE TITLE
[11.0] Error in Trial Balance report

### ISSUE THREAD

**Issue by labaggio** [OCA/account-financial-reporting#543]
https://github.com/OCA/account-financial-reporting/blob/2e4430f7263efea1e0b790ad30be1ec8a791d8eb/account_financial_report/report/trial_balance.py#L575

Value 'compute' is not valid, the correct value is 'computed'

**Comment by pedrobaeza** [comment]
Thanks for detecting that. Please do the corresponding PR for attributing the fix properly.

**Comment by MiquelRForgeFlow** [comment]
can be closed
