### ISSUE TITLE
[11.0] Trial Balance's Journal option does nothing

### ISSUE THREAD

**Issue by Arvinman** [OCA/account-financial-reporting#545]
By changing Journal Field in Trial Balance Report. Only thing that changes in result is Profit/Loss Account. All other general account still take all entries from all journal.

Is this Journal field still valid for use? Or do you have any plan to make it obsolete?

**Comment by jalzaga** [comment]
How is the status of this issu? I have tried also in version 10 and no filtering is done for journals.

**Comment by eLBati** [comment]
Hi, can you check the following fix?
 - v10: https://github.com/OCA/account-financial-reporting/pull/677
 - v11: https://github.com/OCA/account-financial-reporting/pull/679
 - v12: https://github.com/OCA/account-financial-reporting/pull/678
