### ISSUE TITLE
[BUG] Activity/Partner Statements Aging Balances

### ISSUE THREAD

**Issue by gdgellatly** [OCA/account-financial-reporting#546]
This is a bit tricky to explain and I can't quite diagnose it as I didn't do the original SQL.

The aging takes into account partial reconciliations, initially from Q0, but here is where the action happens. I guess the issue could be tied to Q0, and need to check the date of the associated full_reconcile_id?

https://github.com/OCA/account-financial-reporting/blob/348fb0489d0ae2717e7213cfe8e22619891e2ade/customer_activity_statement/report/customer_activity_statement.py#L181-L184

To reproduce this do the following.
With (adjust dates for 30 day buckets)

- 1 payment of $1000 in Feb 2019
- 5 invoices in March 2019 of 10,000
- 1 invoice in April 2019 for 100,000.
- 1 payment May 2019 Have a payment of 49,000

In May reconcile 1,2,4 leaving the 100k outstanding, either through bank statement or otherwise.

Print a statement for 30/04/2019.
Expected Closing Balance at 30/04 is $149,000 - this is correct on statement
Expected Aging at 30/04 is 

Aging | 1 mth | 2 mth | 3 mth | Total
---------|---------|---------|---------|-------
Expected  | 100,000 | 50,000 | -1,000 | 149,000 |
Observed | 100,000 | 40,000 | 0 | 140,000 |

**Comment by MiquelRForgeFlow** [comment]
No, the Aging buckets only show the outstanding. You should compare the Outstanding Statement with the Aging buckets, not the Activity Statement with the Aging buckets.

But I checked your issue and yes, there is an error in the outstanding and the aging buckets. The problem is in the Q0 subquery and also maybe the Q1 and Q2. I will try to fix.

Aging | 1 mth | 2 mth | 3 mth | Total
-- | -- | -- | -- | --
Expected | 100,000 | 49,000 | 0 | 149,000
Observed | 100,000 | 40,000 | 0 | 140,000

**Comment by gdgellatly** [comment]
@mreficent no that is incorrect. The closing balance of an activity statement must equal the sum of aging. 

Also I don't know why you have changed the expected again here. That is also wrong. The 1 payment for $1000 is unreconciled as at 30/04/2019 in the example. It therefore must be -$1000 in the 3 mth column. 

What happens is when you reconcile a full payment, that also includes another credit balance, Odoo creates a partial reconciliation record as well as a full reconciliation record.

**Comment by gdgellatly** [comment]
@mreficent Actually I wonder if there isn't a bug in Odoo in `_compute_max_date` when the partial reconciliation occurs as part of a full reconciliation. What do you think? Or why there is even a partial reconciliation at all.

**Comment by MiquelRForgeFlow** [comment]
I saw in your example, that when I reconciled the $1000 of Feb with a 10,000$ invoice of March, the date of this partial reconciliation is the same of the invoice. Thus, that's why in date of 30/04, this 1000$ is already reconciled and thus I changed the expected.

I do not know if it's correct o no, but what Odoo does is that, when there is a partial reconciliation between an invoice and a payment, the date of the reconciliation automatically is the max of the dates of the invoice and the payment.

**Comment by gdgellatly** [comment]
@mreficent But that is not correct. Not least of which is because the invoice reconciled against is indeterminate. Take a second example. 

In May.
Reconcile nothing.
Print Statement for 30/04/2019
Part reconcile just the $1000 against a march invoice.
Print Statement for 30/04/2019

You have different aging, but nothing has changed from an April perspective. 

But as I say it is even worse in the original case shown, because at no point does the user partially reconcile anything. You are fully reconciling a group of move lines, Odoo just happens to create a partial reconciliation record as part of that process.

**Comment by MiquelRForgeFlow** [comment]
And that partial reconciliation record is assigned the date of the invoice (March), thus at printing the Statement for 30/04/2019, it should consider that reconciliation.

**Comment by gdgellatly** [comment]
No it shouldn't.

Given NO transactions have occurred, NO new entries, NO nothing except a May payment which has been reconciled. The user didn't even create a partial reconciliation, they processed a full reconciliation which happens, due to Odoo internals create a partial reconciliation record, and this bug change the aging. 

The customer provided no remittance saying apply this $1000 to invoice X (and even if they did you can't do that in that screen anyway), the user never said apply this payment to invoice X. They said apply this May payment of 49,000 to these 5 March Invoices totalling 50,000 and this February balance of -1,000. And they said it after the date of the statement.

**Comment by MiquelRForgeFlow** [comment]
Well, maybe we are speaking of different type of reconciliations. The one I am speaking is the one done manually in the invoice:
![Selection_062](https://user-images.githubusercontent.com/25005517/58024945-a25b5380-7b13-11e9-808d-1844a806fa66.png)

**Comment by gdgellatly** [comment]
@mreficent I'm just talking about plain old normal payment matching using either bank reconciliation, or reconciliation widget.

**Comment by MiquelRForgeFlow** [comment]
Yes, and when you do that reconciliation, and then you go again to the first invoice, you will still see that same image. I tested it with the reconciliation widget. All types of reconciliations, no matter which, Odoo does partial reconciliations between invoices and payments, and always chose different dates for those partial reconciliations (the maximum date between the invoice and the payment). Odoo doesn't use a "reconciliation date" for the whole reconciliation. In your initial example, the payment of 1000$ of Feb, always will have a reconciliation date of March when reconciled with the invoices of March, no matter which complex and other payments and invoices of greater dates you put in the mix.
