### ISSUE TITLE
Bug with customer outstanding statement

### ISSUE THREAD

**Issue by dominiquekonsuntack** [OCA/account-financial-reporting#551]
Steps to reproduce:
- Create a sales invoice (e.g. 1,000)
- make a partial payment (e.g. 100)
- make a second partial payment (e.g. 200)
- Print the customer outstanding statement

Bug:
--> the invoice original amount is 2,000 (instead of 1,000). The amount due is correct

**Comment by MiquelRForgeFlow** [comment]
I was unable to reproduce your issue.

![Selection_063](https://user-images.githubusercontent.com/25005517/58469879-bf5ddb00-8140-11e9-80fd-4eb4f3d75a50.png)

Please, ensure you have the module updated to last version.

**Comment by dominiquekonsuntack** [comment]
oh .. it seems to be fixed in v11, but I was referring to v10 ...
any chance to get this backported ?

**Comment by dominiquekonsuntack** [comment]
My mistake .. this is fixed also in V10.
Sorry for the wrong bug report....
Thanks.

**Comment by mreficent** [comment]
It was backported in https://github.com/OCA/account-financial-reporting/pull/549. I don't know if the PR will get merged someday.

**Comment by MiquelRForgeFlow** [comment]
No problem. Then close this issue haha
