### ISSUE TITLE
[11.0][account_financial_report] :warning: pdf and html report have same name

### ISSUE THREAD

**Issue by Tonow-c2c** [OCA/account-financial-reporting#558]
![image](https://user-images.githubusercontent.com/32262135/58571765-b6e9cb00-823a-11e9-9540-9bfe1684805b.png)

For report creation we pass by this method [_get_report_from_name](https://github.com/odoo/odoo/blob/11.0/odoo/addons/base/ir/ir_actions_report.py#L424-L425)

> She get the first record of ir.actions.report having the ``report_name`` as value for the field report_name.

So in some case (like change paperformat of one of them) we have a issue if we have same name for different reports  :warning: 

I propose to re-name report like : 
* `account_financial_report.report_...._qweb_pdf` for pdf report
* `account_financial_report.report_...._qweb_html` for html report

I will create PR soon

**Comment by pedrobaeza** [comment]
OK, good for me.

**Comment by Tonow-c2c** [comment]
@pedrobaeza should we merge this ?

**Comment by pedrobaeza** [comment]
See my comments in the PR, and it's also conflicting right now in v11.
