### ISSUE TITLE
[10.0] Aged Partner Balance : Expected singleton: account.partial.reconcile(2999, 3000, 3001)

### ISSUE THREAD

**Issue by patel1008b** [OCA/account-financial-reporting#560]
QWebException: Expected singleton: account.partial.reconcile(2999, 3000, 3001)
Traceback (most recent call last):
  File "/opt/odoo/odoo-10.0/odoo/addons/base/ir/ir_qweb/qweb.py", line 315, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_account_financial_report_qweb_report_aged_partner_balance_move_lines_545
  File "<template>", line 47, in foreach_544
  File "/opt/odoo/odoo-10.0/odoo/fields.py", line 869, in __get__
    record.ensure_one()
  File "/opt/odoo/odoo-10.0/odoo/models.py", line 4822, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: account.partial.reconcile(2999, 3000, 3001)

Error to render compiling AST
ValueError: Expected singleton: account.partial.reconcile(2999, 3000, 3001)
Template: account_financial_report_qweb.report_aged_partner_balance_move_lines
Path: /templates/t/div/t/div/div[8]/span/a
Node: <a t-att-data-domain="[('id', 'in', list(filter(lambda x: x != 'False', [str(line.move_line_id.id), str(line.move_line_id.matched_debit_ids.debit_move_id.id), str(line.move_line_id.matched_credit_ids.credit_move_id.id)])))]" t-att-data-res-model="'account.move.line'" class="o_account_financial_reports_web_action_monetary_multi" style="color: black;">
                            <t t-raw="line.amount_residual" t-options="{'widget': 'monetary', 'display_currency': res_company.currency_id}"/></a>

**Comment by patel1008b** [comment]
@pedrobaeza Can you please help on this?

**Comment by pedrobaeza** [comment]
You have to reproduce the problem in runbot and put all the needed steps to reproduce the problem.

**Comment by patel1008b** [comment]
@mreficent , I think it's related to #513

**Comment by MiquelRForgeFlow** [comment]
I think you don't have updated the module. please, update it and try again

**Comment by patel1008b** [comment]
The fix is not merge in 10.0 branch. I have took the fix commit code from 11.0 branch.

So we can apply that 10.0 to resolve this.

**Comment by MiquelRForgeFlow** [comment]
Is it solved now? can be closed this issue?

**Comment by JordiBForgeFlow** [comment]
Fixed and merged.

**Comment by patel1008b** [comment]
Yes, it's solved now.
