### ISSUE TITLE
[11] Customer outstanding statement - show already reconciled invoices

### ISSUE THREAD

**Issue by sergiuga** [OCA/account-financial-reporting#564]
Hello, 

I'm using Odoo 11 Community, on a Centos7 VPS. 
After updating to the last version of the module customer_outstanding_statement, the report shows all the invoices for the customer, not only the open ones. 

Thank you, 
Sergiu

![image](https://user-images.githubusercontent.com/28352258/58784552-6385cd00-85ec-11e9-9daf-7c050dc206eb.png)

**Comment by seancallahan88** [comment]
I too am showing this issue in V12e.

Also to prevent confusion on the customer end, perhaps the outstanding statement should be titled 'abbreviated' or condensed statement?

**Comment by gdgellatly** [comment]
@mreficent I can reproduce this. I think it comes from this change https://github.com/OCA/account-financial-reporting/pull/547/files where originally q0 by chance happened to filter these because its case statement excluded the case of `l.balance == 0.0`. Maybe we just need to add that to the Q1 where clause?

**Comment by gdgellatly** [comment]
@mreficent I tried this in local as a fix and it works. What do you think

```python
    def _display_lines_sql_q2(self):
        return str(
            self._cr.mogrify("""
                SELECT Q1.partner_id, Q1.currency_id, Q1.move_id,
                    Q1.date, Q1.date_maturity, Q1.debit, Q1.credit,
                    Q1.name, Q1.ref, Q1.blocked, Q1.company_id,
                CASE WHEN Q1.currency_id is not null
                    THEN open_amount_currency
                    ELSE open_amount
                END as open_amount
                FROM Q1
                WHERE CASE WHEN Q1.currency_id is not null
                    THEN Q1.open_amount_currency != 0.0
                    ELSE Q1.open_amount != 0.0
                END
                """, locals()
            ),
            "utf-8"
        )
```

**Comment by MiquelRForgeFlow** [comment]
LGTM! why don't you do the PR?

**Comment by MiquelRForgeFlow** [comment]
This issue can be closed.
