### ISSUE TITLE
[11.0] [BUG] account financial report - missing style in PDF

### ISSUE THREAD

**Issue by SilvioGregorini** [OCA/account-financial-reporting#567]
Hello everyone,
I'm experiencing a few problems using the reports implemented within module `account_financial_report`.
Whenever I create an HTML view from the “OCA accounting reports“ menu, everything goes straight; yet, when I try to download the PDF version of it, the report has no styling whatsoever.

Here you can find two pdf reports I created a few minutes ago:
[Trial Balance.pdf](https://github.com/OCA/account-financial-reporting/files/3258206/Trial.Balance.pdf)
[General Ledger.pdf](https://github.com/OCA/account-financial-reporting/files/3258208/General.Ledger.pdf)

Please note that these files were created using the Odoo runbot at [http://3373396-11-0-e05852.runbot3.odoo-community.org/](http://3373396-11-0-e05852.runbot3.odoo-community.org/).

**Comment by eLBati** [comment]
Similar problem fixed in v12 with https://github.com/OCA/account-financial-reporting/pull/559/commits/0fb37f484a666ca2df369031bef19aa910d16f36#diff-d4acce339ed5a97f2ad218fbe91081b7R13

**Comment by pedrobaeza** [comment]
Can you put the PR with the fix, please?

**Comment by SilvioGregorini** [comment]
@eLBati @pedrobaeza 

Just opened PR #568 that might solve this issue.
It is just a backporting of commit 0fb37f4 as suggested above.

**Comment by pedrobaeza** [comment]
I'm reverting 3aae117362f48c846e1ecdc772967f3b52ebbe3c in 2fe67661b1433b810902727fa1db8ff8c3ea210a, as the proposed fix can have side effects.
