### ISSUE TITLE
How to handle accented characters in report names?

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-financial-reporting#57]
Example: when printing the Aged Partner Balance in french, "Balance âgée des tiers" causes an execv() exception or is misprinted. The exact behaviour seems to depend on the locale under which the server runs.

This is due to this title being passed as a --header-left argument to wkhtmltopdf.

Does anyone knows if there is some best practice in this respect?

**Comment by ghost** [comment]
Hi @sbidoul 

Were you able to fix the errors without changing the translation?

**Comment by sbidoul** [comment]
@gs-clearcorp no progress. But I'm pretty sure it's related to the server environment locale.

**Comment by adrienpeiffer** [comment]
Hi @gs-clearcorp,
After several investigation, I think put `LANG="en_US.UTF-8"` as an environment variable should solve the problem. Could you give us your feedback if you test it ?

**Comment by ghost** [comment]
Hi @sbidoul , @adrienpeiffer I tried to fix the error with LANG=en_US.utf-8 and es_CR.utf-8  without success.

**Comment by adrienpeiffer** [comment]
It's strange. 
My scenario :  
I launched my server like this `LANG=en_US ./odoo.py` and the execv() is raised. After that I launched my server like this `LANG=en_US.UTF-8 ./odoo.py` and the initial exception isn't raised.

**Comment by ghost** [comment]
I was able to solve the error

Had to add <i>env LANG=en_US.utf-8</i> to the start-stop daemon script.

**Comment by luisfqba** [comment]
Work for me. I run odoo on Docker Container and when I added env LANG=en_US.utf-8 webkit run fine. Thanks.

**Comment by antoniocanovas** [comment]
Working for me with LANG=es_ES.utf-8
Thanks

**Comment by alexis-via** [comment]
@sbidoul Do you consider the solution above as the "real" fix, or as a sort of hack/workaround ?

When I read this comment in the code:
https://github.com/OCA/account-financial-reporting/blob/8.0/account_financial_report_webkit/report/webkit_parser_header_fix.py#L51

it confirms what I think: it's really dirty to use arguments to a command line to pass this kind of information with accentuated characters.

**Comment by sbidoul** [comment]
@alexis-via Putting .utf-8 in the LANG env var is the best workaround I've seen so far. 

But I agree a better solution should come from somewhere upstream (probably in wkhtmltopdf).

**Comment by alexis-via** [comment]
@sbidoul ok, we have the same point of view.

**Comment by pedrobaeza** [comment]
Closing this as now in new versions doesn't happen and there's a workaround any way.

**Comment by bitsnaps** [comment]
trying odoo v9 in container it doesn't work (it throws the same error)
