### ISSUE TITLE
In account_financial_report, href to an unexisting css file

### ISSUE THREAD

**Issue by alexeirivera87** [OCA/account-financial-reporting#571]
In account_financial_report/report/templates/layouts, branch 11.0, we have this line
`<link href="/account_financial_report/static/src/css/report.css" rel="stylesheet"/>`

but that file report.css does not exists

Regards

**Comment by pedrobaeza** [comment]
Fixed in 2fe67661b1433b810902727fa1db8ff8c3ea210a

**Comment by i-vyshnevska** [comment]
@pedrobaeza reverting for v11 is wrong, as reported branch is wrong 
in v11 used **account_financial_report_qweb** and bug reported about **account_financial_report**
