### ISSUE TITLE
General ledger - Total ending balance does not take into account filtered partners 

### ISSUE THREAD

**Issue by jalzaga** [OCA/account-financial-reporting#575]
When selecting partners in general ledger, the total ending balance is not the sum of the selected partners but the total of the account.
It creates confusion since the user expect to find the total of the selected partners instead of the global balance for the account.
I enclose two screenshots, one with partner selection and another one without selection
![2019-06-14 13_04_34-General Ledger - Odoo](https://user-images.githubusercontent.com/7764079/59506950-d7a45880-8ea9-11e9-9143-5900faf90e00.png)
![2019-06-14 13_03_24-General Ledger - Odoo](https://user-images.githubusercontent.com/7764079/59506963-dd01a300-8ea9-11e9-87ec-80860bbb3c98.png)

**Comment by pedrobaeza** [comment]
Duplicated of #515
