### ISSUE TITLE
Last version of wkhtmltopdf (0.12.2.1) cut rows at half

### ISSUE THREAD

**Issue by cubells** [OCA/account-financial-reporting#58]
Openerp 7.0 with all the code updated.

With wkhtmltopdf 0.12.2.1, webkit reports cut some rows at half at page breaks.

The same with 0.12.1 version doesn't cut rows.

**Comment by BT-ojossen** [comment]
We have the same problem if we use "wkhtmltopdf 0.11.0 rc1", but all the other mako reports are then ok.

If we use the version "wkhtmltopdf 0.12.1 (with patched qt)" then the account-financial-reports do work, but then we have problems with all the other mako reports (the header is not working).

Could you tell us, which version of wkhtmltopdf should be used for your reports?
Don't you have problems with other reports with this wkhtmltopdf version then?

Thanks for your help.

Greetings

**Comment by pedrobaeza** [comment]
This is not an issue of the module itself and not supported version of wkhtmltopdf. Closing.
