### ISSUE TITLE
record rules in account_financial_report

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-financial-reporting#580]
Following the recent issue about the security of account_financial_report that I raised with @jbeficent, I'm wondering if there might not be an easy way to improve security for account_financial_report (short of rewriting it using the ORM which is an undertaking that  probably no one is willing to tackle right now).

Since most reports are based on account.move.line, it might be relatively easy to 
1. check the account.move.line ACL for read access
2. inject in the SQL queries, the where clauses obtained from `env['ir.rule'].get_domain('account.move.line', 'read')`

This would make the behaviour of the reports less surprising w.r.t. confidentiality, and would enable use cases such as safely showing sales persons the partner ledger for their own customers with a simple record rule.

What do people familiar with these report think?

**Comment by pedrobaeza** [comment]
I'm begging for an ORM rewrite for a long time to go out of the SQL hell, but I admit is not easy now and will require some stabilization time.
