### ISSUE TITLE
[10.0] account_financial_report_qweb: trial balance 

### ISSUE THREAD

**Issue by glauco70** [OCA/account-financial-reporting#587]
When I create a trial balance report selecting the VIEW button, I see the result not in a readable mode 
![trial_balance](https://user-images.githubusercontent.com/13453706/60504846-b5d90d00-9cc2-11e9-9546-b395eb5b550d.png)

**Comment by pedrobaeza** [comment]
This seems a deployment issue. Please try to reproduce the problem in OCA runbot following link in the README.

**Comment by glauco70** [comment]
thank you

**Comment by glauco70** [comment]
Pedro,
I found the problem : we use the last stable versione of the module (10.0.1.5.2 of july 2018), instaed runbot use the last version ( 10.0.3.1.0.99.dev12 ); is not possible to create stable version when yo fix problems ?
![module_version](https://user-images.githubusercontent.com/13453706/60573317-bed7e600-9d77-11e9-86b1-88edf62c4eff.png)

**Comment by pedrobaeza** [comment]
No, if using pip, you must always use the modules with `--pre`

**Comment by eLBati** [comment]
Hi @glauco70 and @pedrobaeza 

I think that if, from now on, @OCA-git-bot  will be used to merge PR increasing version (see https://odoo-community.org/blog/the-oca-blog-1/post/the-oca-github-bot-can-now-merge-pull-requests-92) the problem will be solved.

See for example https://pypi.org/project/odoo12-addon-l10n-it-ddt/#history and the related commits https://github.com/OCA/l10n-italy/commits/12.0

**Comment by pedrobaeza** [comment]
If used, yes, but not all contributors do it, so the only way to be sure is to use that option.

**Comment by eLBati** [comment]
I think we should encourage to merge increasing version. It's costless

**Comment by sbidoul** [comment]
Now that bumping the version numbers can be easily done by maintainers without burdening the contributors, there is no reason not to bump versions anymore.

Further improvements will come with https://github.com/OCA/oca-github-bot/issues/15, https://github.com/OCA/oca-github-bot/issues/16, and https://github.com/acsone/setuptools-odoo/issues/39

**Comment by Byloth** [comment]
Hi, @pedrobaeza.  
Thanks for your reply.

Actually, we know pretty well how to use `pip`.
The focus of the discussion, here, it's slightly different.

As you already know, Odoo modules can define external Python dependencies directly inside `__manifest__.py` file via `"external_dependecies"` key.
In those cases, if you force `--pre` flag during installation, you will also install the **unstable** version of those external dependencies.

Based on what those dependencies are, it could be a self-destructive behaviour...

> *«The dependency of the dependency of the dependency of the dependency...»* and so on...

All of those packages will be **unstable**! 🤯

---

And, yes... You can easily figure out that this is **absolutely** unacceptable.  
In fact, all the other *believable* existing packages in the PyPI ecosystem are using this distinction between `stable` and `unstable` versions.  
If OCA plans to be part of that environment, it can't use its own rules... It must be conform with **that** environment rules. That's it.

---

You could probably tell me that another solutions could be use something like:
```bash
pip install [ --ignore-installed | --no-dependencies ] \
    odoo10-addon-financial-report-qweb==10.0.3.1.0.99.dev12 \
    [...]
``` 
But, yeah...  
In this case I should explicitly add also all the `financial_report_qweb`'s dependencies, the dependencies of those dependencies (and so on) with the right unstable versions for all of those.  
This will also make the update procedure longer, more difficult to maintain and increasing the likelihood of human errors.

Why?  
All of this just for a single digit of a single key of a single dictionary in a single file. Is it **really** worth? 🤔

---

Oh...
I almost forget to cite this: [OCA Guidelines](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#version-numbers).

@sbidoul will probably remember an old e-mail I've wrote to support@odoo-community.org some months ago telling exactly the same thing.

The reply was something like:
> Well, yes... You're right.
> The guidelines say this, but the developers always forget to increment the version number.

Developers **always** forget to do something! 🤣
-  Write tests...
-  Using ORM instead pure SQL...
-  Regenerating the docs...
-  Remove useless comments...
-  Remove PDBs...
-  Sign the CLA...
- *... ect...*

For some of those things, there are bots that help us doing that...  
For some other things, there are reviewers that strictly review our code...

And all of those things are written right in the guidelines!

But change a single version number?  
Why **this** single thing is ignored (even if it is written in the docs) by everyone and it's ok?!

It doesn't make sense! 😅

---

Last thing...
Actually, for the [L10N Italy repository](https://github.com/OCA/l10n-italy) we're already follow those guidelines about version numbers and, as also @eLBati can confirm, things are working pretty well. 🤗

**Comment by sbidoul** [comment]
>@sbidoul will probably remember an old e-mail I've wrote to support@odoo-community.org some months ago telling exactly the same thing.

I do and I'm well aware `--pre` is not ideal. That said, in practice, it does not really create issues as the vast majority of python libs in Odoo dependencies don't have unstable version on pypi anyway.

Anyway, it's in part to solve this that I wrote the bot merge command, so the issue will now mostly resolve itself naturally.
