### ISSUE TITLE
[10.0]Account_financial_report_qweb

### ISSUE THREAD

**Issue by manuelviejo** [OCA/account-financial-reporting#588]
Regards,

I have a doubt about the module account_financial_report_qweb, specifically about the generation of the general ledger. I would like to know why only accounts that are type To pay or To collect are grouped by company, and why accounts that are not of these types can not be grouped. Is it for a specific reason? Is there a reason why it is not allowed to group by company the accounts that are not type To pay or To collect?
You can not change the type of accounts, at least not from the interface, so there is a need to group by company but it is not possible. We have seen some comments that some accounts are considered general and others are not, but this is to mix the concept of Odoo.
In any ERP or accounting program it is necessary to create an independent accounting account for each company, but Odoo is able to manage with a generic account because it takes into account the company.
In Odoo if we can filter by ACCOUNT / COMPANY without any problem, thus obtaining the subtotals of each company, but not in the report generated by the module.

Thanks in advance.

**Comment by pedrobaeza** [comment]
That accounts are the one that should be grouped by partner. The rest are not meaningful with that grouping.

**Comment by manuelviejo** [comment]
Regards,

we think there are some cases that are meaningful. For example, we have a client who works in loan managment. We've defined that loans have to be count in the account 542000 by default, what is that is determinated by law, but this account is no To pay or To collect and we can't change account's type because then the balance would fail. 
When we count the loan in this account, we assign to it the company (the client). We think that could be interesting obtain the general ledger of the account 542000 dissaggregated by company, as same like when we obtain the general ledger of the account 430000. 

Any ideas? Any alternative?

Thanks in advance.

**Comment by pedrobaeza** [comment]
You are perverting the concept, so if you want this, you must develop the option, and if you want, contribute it back to the module, but it must be an opt-in option, not the default one.
