### ISSUE TITLE
[11.0] account_financial_report: incorrect order

### ISSUE THREAD

**Issue by cubells** [OCA/account-financial-reporting#591]
As the criteria to order account moves in report is by date, name

https://github.com/OCA/account-financial-reporting/blob/f685a2fb5557e91b2ea06cd294a29f597f8756fb/account_financial_report/report/journal_ledger.py#L223

Then the order of lines are incorrect because different records of the same date will be ordered by this way:

```
date         |  name  | ...
'2019-01-01' |  1
'2019-01-01' |  10
'2019-01-01' |  11
'2019-01-01' |  2
'2019-01-01' |  3
...
```

And we need to order by this way:

```
date         |  name  | ...
'2019-01-01' |  1
'2019-01-01' |  2
'2019-01-01' |  3
'2019-01-01' |  4
'2019-01-01' |  5
...
```

If order is set by name, then the problem is the same, obviously.

https://github.com/OCA/account-financial-reporting/blob/f685a2fb5557e91b2ea06cd294a29f597f8756fb/account_financial_report/report/journal_ledger.py#L221

**Comment by pedrobaeza** [comment]
Why is this a problem? What "name" means in this context?

**Comment by cubells** [comment]
name is the number of the account_move but name is an string. 

When you list the journal, journal are ordered incorrectly.

**Comment by pedrobaeza** [comment]
Then it is correct as is. The journal number must have the needed padding for avoiding this problem. Change the sequence and renumber moves.

**Comment by cubells** [comment]
Ok, you are right.
