### ISSUE TITLE
[10.0]Base Amount Wrong

### ISSUE THREAD

**Issue by jayo2005** [OCA/account-financial-reporting#598]
I am using Odoo 10. I have two vat rates 23% & 13.5%. When running the Tax balance report or the Sale/Purchase report the Base amount is wrong. On the 23rd I have one invoice with 13.5%. Prices include Tax

![1](https://user-images.githubusercontent.com/7015925/61863648-f134b900-aec7-11e9-85d3-4828b96ff02e.jpg)

So the VAt on 13.5% is 11.81.

When I run the Sale/Purchase report.

![2](https://user-images.githubusercontent.com/7015925/61863662-f98cf400-aec7-11e9-8845-4cc2e4007da8.jpg)

You can see above the Base amount is totally wrong but Tax is correct.

If I run the Tax balance Report.

![3](https://user-images.githubusercontent.com/7015925/61863684-027dc580-aec8-11e9-964d-4e1636af1f59.jpg)

A closer look at the Tax Balance report where is €20.71 coming from. 

![4](https://user-images.githubusercontent.com/7015925/61863836-4bce1500-aec8-11e9-98a3-5dd463f6eec0.jpg)

AS a result, my reports are all wrong. My accountant has told me to stop using Odoo as it is not handling the Tax rates correctly. Can some please explain what is going on or supply a fix.

**Comment by pedrobaeza** [comment]
This has nothing to do with this repository, and the answer is simple: you did the invoice before changing the configuration "tax included in price".

**Comment by jayo2005** [comment]
tax included in price" was always set from the beginning. Even if I did the figures still don't make sense

**Comment by jayo2005** [comment]
@pedrobaeza is the tax_balance module not part of this repository?

**Comment by pedrobaeza** [comment]
Yes, but it only showcases what you have in the account move lines, so the problem comes from before.

**Comment by jayo2005** [comment]
I can create a video to prove that the tax included in the price is set before the invoice is created. We are using system 2 months and prices always included tax

**Comment by pedrobaeza** [comment]
As said, this problem should be handled in Odoo, not here (you are showing the tax summary in the invoice report, so that should give you a hint that is not a problem in the tax balance), but proving that is a real problem. Try to reproduce it on runbot (http://runbot.odoo.com/runbot - admin/admin).
