### ISSUE TITLE
Export general ledger is too long

### ISSUE THREAD

**Issue by laetitia-gangloff** [OCA/account-financial-reporting#60]
Impacted version :
- 7.0
- 8.0

Steps to reproduce :
0. Install module account_financial_report_webkit
1. Get alot of journal entries
2. Ask for a general ledger report with 'All posted Entries' as target moves
3. Wait for a loooong time

In the following file : https://github.com/OCA/account-financial-reporting/blob/7.0/account_financial_report_webkit/report/common_reports.py#L440

search on account_move_line are done with orm.
I think the following part is responsible of performance problem : `[('move_id.state', '=', 'posted')]`

**Comment by pedrobaeza** [comment]
Have you tried to put that part in SQL to see if the time is reduced?

**Comment by laetitia-gangloff** [comment]
Yes, I tried with the following method (instead of the existing one, easy-ugly fix) and the time is reduced (quasi immediate) :

``` python
    def _get_move_ids_from_periods(self, account_id, period_start, period_stop,
                                   target_move):
        period_obj = self.pool.get('account.period')
        periods = period_obj.build_ctx_periods(
            self.cursor, self.uid, period_start.id, period_stop.id)
        if not periods:
            return []
        move_state = ['draft', 'posted']
        if target_move == 'posted':
            move_state = ['posted', '']
        #return move_line_obj.search(self.cursor, self.uid, search)
        sql = """select aml.id
                 from account_move_line aml
                      LEFT JOIN account_move am ON (am.id = aml.move_id)
                 where aml.period_id in %s
                 and aml.account_id = %s
                 and am.state IN %s
        """
        self.cursor.execute(sql, (tuple(periods), account_id,
                                  tuple(move_state)))
        res = self.cursor.fetchall()
        return res
```

**Comment by laetitia-gangloff** [comment]
I also tried to set `auto_join=True` on the column move_id of account.move.line and the result is also quasi immediate.

**Comment by laetitia-gangloff** [comment]
I proposed the following PR to odoo (to add auto_join):
https://github.com/odoo/odoo/pull/5573

**Comment by laetitia-gangloff** [comment]
PR is closed, so I closed this issue.
