### ISSUE TITLE
[12.0] Trial Balance - Account Group Hierarchy presentation not correct

### ISSUE THREAD

**Issue by drmedrme** [OCA/account-financial-reporting#604]
When I run trial balance, the account group hierarchy seems to not work if you have child groups.  This worked fine in 11.0, but when testing 12.0, it doesn't seem to present the same way.  In my case I have Parent Group, Child Level 1, Child Level 2, Account Level.  The multilevel accounts are not presented in proper order.  The actual amount shown of the Parent group is correct though.  See jpeg attached.
![finreport](https://user-images.githubusercontent.com/23726500/62703327-e0646700-b9e0-11e9-9c89-ef6fbe41a148.PNG)

**Comment by pedrobaeza** [comment]
It seems your `parent_path` is not correct in `account.group` model. Have you migrated your DB?

**Comment by drmedrme** [comment]
Yes.  I migrated database.

**Comment by pedrobaeza** [comment]
Then you need to recompute parent_path:

https://github.com/OCA/OpenUpgrade/blob/018d2b962859bab237812dcaa57bd80da11abd8f/addons/account/migrations/12.0.1.1/post-migration.py#L230

**Comment by drmedrme** [comment]
Thanks.  I will try that.
