### ISSUE TITLE
[BUG] account_financial_report: Trial Balance groups order

### ISSUE THREAD

**Issue by gaikaz** [OCA/account-financial-reporting#609]
module: account_financial_report
version: 12.0 (11.0 and even 10.0 seems to also be effected)

Probably related issues #604 #463 #495 that people might find when having this problem.

**Current behavior**
In Trial Balance report, groups are ordered incorrectly. See image below. As far as I figured it out, this is caused by how the module uses `account.group` module's field `parent_path` to generate a sequence. The problem is that this field is of type Char that is made up of integer ids separated by slashes. Which means that in case where there is an account group **1** with id `1`, group **2** with id `2` and group **3** with id `10`, the ordering is seen like:
`"1/" < "10/" < "2/"`
And this is pseudo correct programming statement when working with char strings.
This is exactly what I managed to reproduce on community runbot, where the screenshot is taken from.

![image](https://user-images.githubusercontent.com/17097810/63840638-15355f80-c98a-11e9-8d5d-d3d294082703.png)

**Steps to reproduce**
- On a freshly created new database with demo data (so that new `account.group` records will get ids starting from `1`), create account groups in this order:
1. *name:* `1` *Code Prefix:* `1` *Parent:* ` `
2. *name:* `2` *Code Prefix:* `2` *Parent:* ` `
3. *name:* `21` *Code Prefix:* `21` *Parent:* `2 2`
4. *name:* `22` *Code Prefix:* `22` *Parent:* `2 2`
5. *name:* `23` *Code Prefix:* `23` *Parent:*`2 2`
6. *name:* `24` *Code Prefix:* `24` *Parent:* `2 2`
7. *name:* `25` *Code Prefix:* `25` *Parent:* `2 2`
8. *name:* `26` *Code Prefix:* `26` *Parent:* `2 2`
9. *name:* `27` *Code Prefix:* `27` *Parent:* `2 2`
10. *name:* `3` *Code Prefix:* `3` *Parent:* ` `
- Try generating the Trial Balance. The dates don't matter, the important part is to have **Hide accounts at 0** option unchecked, so that all groups get printer.

**Comment by pedrobaeza** [comment]
AFAIK, `parent_path` is not composed of IDs, but group codes + account code.

**Comment by gaikaz** [comment]
Exported all groups from this database in CSV format:
```
"External ID","ID","Name","Code Prefix","Parent Path"
"__export__.account_group_1_e4680276","1","1","1","1/"
"__export__.account_group_2_0e6694b6","2","2","2","2/"
"__export__.account_group_3_9c87df85","3","21","21","2/3/"
"__export__.account_group_4_f097a441","4","22","22","2/4/"
"__export__.account_group_5_d1738d17","5","23","23","2/5/"
"__export__.account_group_6_12319d5c","6","24","24","2/6/"
"__export__.account_group_7_8a4c2366","7","25","25","2/7/"
"__export__.account_group_8_c81dc4f6","8","26","26","2/8/"
"__export__.account_group_9_969ff239","9","27","27","2/9/"
"__export__.account_group_10_27dcac22","10","3","3","10/"
```

The second column here is the actual internal ID and it seems to be used in `parent_path`. Best seen with the very last records which is `3` but ID is `10`

**Comment by pedrobaeza** [comment]
If you do `"1/" > "10/"`, it's False, so they are not sorted that way. There should be something more. Is this DB a migrated one?

**Comment by gaikaz** [comment]
This was (maybe still is) reproduced on runbot.odoo-community.org
Would it help if I find the exact database?

**Comment by gaikaz** [comment]
I don't know if it's a good idea to add links like this here, as it will expire, but It's still there: http://3383961-12-0-4cc432.runbot3.odoo-community.org

**Comment by gaikaz** [comment]
> If you do `"1/" > "10/"`, it's False, so they are not sorted that way. There should be something more.

It's the other way around. `"1/" < "10/"` which is True. But this is not the problem, because this is talking about ID `1` which is Group `1` and ID `10` which is Group `3`. Then it's correct. `1/` goes before `10/`. The problem is `"2/" > "10/"` which evaluates to True because of string comparison, when we actually need the integers `2` and `10` to be compared.

**Comment by pedrobaeza** [comment]
Thanks for extra info. Checking...

**Comment by pedrobaeza** [comment]
There are no groups on OCA runbot you mention:

![Selección_023](https://user-images.githubusercontent.com/7165771/63870742-dcfa4500-c9ba-11e9-8502-4e148428c1a6.png)

so how have you check it?

**Comment by gaikaz** [comment]
I created a custom menu item to add them: `Invoicing > Configuration > [TEST] Account Groups`
But I didn't attach the accounts to groups. This is besides the point. This is why in the "How to reproduce" section, I wrote to uncheck the **Hide accounts at 0** checkbox. Then all groups are displayed, even without accounting data.

*Thought, I see where you are coming from. It's very odd how in the report there are credit/debit numbers shown on my new groups. These must be from demo data. This could also be a whole new issue we just stumbled upon, but I really don't think it's relevant for now.*

**Comment by gaikaz** [comment]
Thinking about this more, I see the little flaw in my test. It's not a real use case to show empty groups (even if it's possible and wrongly ordered anyway). I could add all the current demo accounts to groups on that DB, if you want? And if the theory here is right, it should still stay badly ordered in the report.

**Comment by pedrobaeza** [comment]
Yes, please! I'm any way checking on local installations.

**Comment by gaikaz** [comment]
Done. Attached accounts to groups that would make sense if these were the only groups available. The theory seems to still be valid, as predicted.
![image](https://user-images.githubusercontent.com/17097810/63874420-2b631000-c9ca-11e9-8567-bccda9267327.png)

Still had to uncheck the **Hide accounts at 0** as accounts in group 3 do not have any journal entries and I need it in the report to show the problem.

**Comment by pedrobaeza** [comment]
OK, thanks for the extended info. We need to find other sorting method for this.

**Comment by gaikaz** [comment]
Maybe I'm missing something, but I really think a proper `sequence` field should be added to `account.group` in the core Odoo. It wouldn't hurt, yet would solve this and be a very welcome feature in some other use cases for specific reports or client needs.

If that's not something we can expect to happen with v12 (probably not even v13 at this point), would something like `account_group_sequence` in OCA make sense?

**Comment by pedrobaeza** [comment]
But sequence doesn't serve on a hierarchy topology. It's supposed that `parent_path` solves this in replacement of parent_left/parent_right, but as you have proved, it's not enough. I will think about a possible solution.

**Comment by gaikaz** [comment]
Good point, but menu item records (`ir.ui.menu`) use an integer `sequence` field, yet are very hierarchical by design.

**Comment by pedrobaeza** [comment]
Yeah, but they are populated other way, and with no handler at UI level. Here we are dumping to a table the "final order" and ordering by that column.

**Comment by gaikaz** [comment]
Sorry, I didn't fully understand that. But also, I do not want to be persuasive about something I don't fully understand, so I will not get in your way here. 🙂
Though, I will be active here and help as much as I can. ✌

**Comment by gaikaz** [comment]
@pedrobaeza I know you are very busy, but could there be a point in the schedule to look at this issue again?

**Comment by pedrobaeza** [comment]
Sorry, but it's going to be impossible for me to work on this until after Odoo XP. I will comment this any way in OCA days to see if someone does it.
