### ISSUE TITLE
[12] VAT Report Summary Amount in Net column incorrect calculation

### ISSUE THREAD

**Issue by hitrosol** [OCA/account-financial-reporting#611]
There are 2 issues here :
a. The Summary calculation shows incorrect calculation in the NET Column. The summary formula is supposed to deduct the PPN 10 % Keluaran to PPN 10 % Masukan. The Summary formula in Column Tax is correct, but not in the NET Column. 

![image](https://user-images.githubusercontent.com/5949936/64429797-06b11b80-d0e1-11e9-9d0a-2cd3f6480aa8.png)

It's also better to show the PPN 10.00 % Keluaran as negative amount (Credit) and PPN 10.00% Masukan as Positive amount (Debit)

b. When I try to drill down the detail amount of Net, it shows this error 

![image](https://user-images.githubusercontent.com/5949936/64430201-f188bc80-d0e1-11e9-9ea3-3c884c1c19a8.png)

I change 
   ('date', '&gt;=', o.date_from),
                                         ('date', '&lt;=', o.date_to)]"/>

to : 
 ('date', '&gt;=', o.date_from.strftime('%Y-%m-%d')),
                                         ('date', '&lt;=', o.date_to.strftime('%Y-%m-%d'))]"/>

and it works.

**Comment by lmoram** [comment]
Hello, where should I make the change?
Thanks

**Comment by pasgou** [comment]
#683
