### ISSUE TITLE
General ledger without analytic parent

### ISSUE THREAD

**Issue by pepitovadecurt** [OCA/account-financial-reporting#616]
Hi have a ODOO CE 10 with account_analytic_parent installed but in the General Ledger doesn't appears the analytic parent.
Example: with the analytic account AC and parent AA only shows AC (not AA).
It should appear?

**Comment by pedrobaeza** [comment]
No, it shouldn't appear. They are different modules and no bridge is planned. See parent analytic accounts in the view provided by the module or develop this bridge.

**Comment by pepitovadecurt** [comment]
Thanks pedrobaeza, I will try to make the bridge if I am capable with my little knowledge.

**Comment by pepitovadecurt** [comment]
This is the temporary modification that I have:
In the code field of the analytic account module I have manually put the full text, similar to: "motheraccount / account".
Then in the module account_financial_report_qweb file general_ledger.py, line 910, change aa.name to aa.code

I hope it helps someone
