### ISSUE TITLE
[12.0] statement account error with reconciled entry in report 

### ISSUE THREAD

**Issue by MarcoCalcagni** [OCA/account-financial-reporting#622]
Impacted versions:
12.0
Steps to reproduce:
create an invoice of 464,09
create a payment of 464,19 (extra payment of 0,10)
reconcile and add a 0,10 adjustment .

the invoice is full paid . noting to reconcile .

Current behavior:
in the report statement account there is 3 line

Expected behavior:
in the report statement account it should 0 line

![image](https://user-images.githubusercontent.com/11019886/66466547-2ee6be00-ea83-11e9-9405-57e3954ba5bd.png)

![image](https://user-images.githubusercontent.com/11019886/66466579-3b6b1680-ea83-11e9-8615-ad704c2f6127.png)

**Comment by gdgellatly** [comment]
This is an activity statement, as such it shows all activity, so it is correct. What you want is an Outstanding statement
