### ISSUE TITLE
[odoo 8.0] Error export report inform with slash

### ISSUE THREAD

**Issue by witoszek** [OCA/account-financial-reporting#630]
Hello 

I've got an error with a report with title like 27/12/2019.
The problem is with " / " so the answer is ok quit slashes, but how can i used with slashes?

Thansk

**Comment by pedrobaeza** [comment]
That's a forbidden OS character, so nothing to do with the module itself. Use `-` instead.

**Comment by witoszek** [comment]
Ok thanks Pedro
