### ISSUE TITLE
[12.0] mis_builder_cash_flow: forecast line values don't accumulate anymore to the next column weeks

### ISSUE THREAD

**Issue by rvalyi** [OCA/account-financial-reporting#636]
Hello,

the mis_builder_cash_flow demo data doesn't contain any Cash Flow Forecast Line. But if you add such a line via Reporting>Cash Flow Forecast Line. Then add for instance a line "Sales" on the account 101200 Account Receivable with a balance of 1000 and a date 2 weeks in the future. When you select the Cash Flow report in Reporting>Mis Reports and refresh it.
You will have something like:
![image](https://user-images.githubusercontent.com/16926/69660950-2a408e00-1060-11ea-9b2d-e13cf95bf3d6.png)

As you can see, the columns +2w with the 1000 USD receivable forecast is correct with the balance raising to 6988. **However the columns +3w and next columns are not correct as the 1000 forecast is lost instead of propagating as expected!**

Note that when the module was presented in a Youtube video, it seems these forecast values were propagating properly as expected so I don't know where the problem comes from if it's a regression in mis_builder_cash_flow or in mis_builder itself:
![image](https://user-images.githubusercontent.com/16926/69661229-c8345880-1060-11ea-80fb-b3139ec7e117.png)

cc @etobella @jjscarafia @sbidoul @jbeficent

**Comment by pedrobaeza** [comment]
Why it should be propagated? It happens in that week, not in others, and I don't see in the video that propagation.

**Comment by rvalyi** [comment]
@pedrobaeza Thank you for your interrest. Well the money you expect to receive in that week should still be there in your balance the next week, no? (unless you spend it explicitely which is not the case here). In the 2nd screenshot from Youtube ( https://www.youtube.com/watch?v=dYJdZBqpV6U&t=23s ) , in week 3, you still have the 1000 you forecasted in week 2 as you have -2150=850-3000. You would have -3150 instead if the 1000 of the forecast were lost like in my own screenshot. The same happens with the other forecasts (positive or negative) of the Youtube video, their amount is always propagated to the next week unlike in my fresh test of the module. Is that clear for you?

**Comment by pedrobaeza** [comment]
OK, now I get you. You are talking about the balance, not the entry on the line. Yes, the balance should be affected and indeed seems a bug in the module.

**Comment by jjscarafia** [comment]
Hi @rvalyi !
Thanks one more for the detailed explanation.
This error is fixed with this pr https://github.com/OCA/account-financial-reporting/pull/638

**Comment by rvalyi** [comment]
@jjscarafia thank you very much for the quick fix. I'll soon test and review your PR!

**Comment by rvalyi** [comment]
FYI I approved the fix from @jjscarafia #638, thanks a lot for it!
let's see if we get other approvals...

**Comment by rvalyi** [comment]
so closing as it was fixed by #638
