### ISSUE TITLE
[11.0] Refactor account_financial_report

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/account-financial-reporting#640]
The current design associated to the `account_financial_report` has several important drawbacks:

- Makes heavy use of transient models, which are hard to autovacuum after they have been generated and perform slowly due to the number of inserts to the database (often creating one record for each move line).
- Makes heavy use of direct SQL queries, which is in general bad practice, and these queries are very slow in large databases. ORM calls to search,read, read_group should be used as much as possible.

The intention if this Issue is to track the progression of the refactoring of this module into a more optimum design. 

Please feel free to comment on this ticket if you want to assign yourself to any of the tasks to refactor:

* [ ] Journal Ledger => @jbeficent https://github.com/OCA/account-financial-reporting/pull/639
* [ ] General Ledger
* [ ] Open Items
* [ ] Trial Balance
* [ ] VAT Report
* [ ] Aged Partner Balance

**Comment by kittiu** [comment]
@jbeficent 
To address the performance of big report, I am planning to make abstract class to extend running reports using queue. I could make it also as addon for account_financial_report. WDYT?

I wanted to check first whether similar thing already exists ?

**Comment by patel1008b** [comment]
Hi, @JordiBForgeFlow  big thanks for this PR.

Often when we see the code its looks very complex also very hard to debug the SQL queries for me too.

I also prefer ORM calls as much as possible. Looking forward to having this refactor module.

**Comment by JordiBForgeFlow** [comment]
@kittiu Using queue would be useful. I am not aware of anyone that has worked on this. Please go ahead. We'll see how to adjust after the refactoring.

**Comment by kittiu** [comment]
@JordiBForgeFlow 
https://github.com/OCA/reporting-engine/pull/355
Would appreciate your comment.

**Comment by pedrobaeza** [comment]
This has been refactored in 13.0, so we can close it.
