### ISSUE TITLE
[partner_statement] Unposted journal entries appear in partner_statement reports.

### ISSUE THREAD

**Issue by LGodoo** [OCA/account-financial-reporting#641]
Is this intended? If so I think there should be an option to include or exclude unposted/draft entries.

**Comment by gdgellatly** [comment]
Nah they shouldn't be in there, actually will be even more problematic in v13 so make a PR and we can check

**Comment by MiquelRForgeFlow** [comment]
This issue can be closed, as your PR has been merged.
