### ISSUE TITLE
[12.0] Trial Balance shows account groups from other companies

### ISSUE THREAD

**Issue by qgroulard** [OCA/account-financial-reporting#645]
Context:

- Our customer has a company in France and one in Spain, thus he is using multi-company.
- The Spanish accounting is installed for the Spanish company.
- Spanish account groups come with the Spanish accounting, but are shared between all companies.
- All account groups are displayed on the Trial Balance report, thus groups installed with the Spanish accounting appear in the French Trial Balance report.

Has anyone encountered this kind of issue ?
Any idea why account groups are shared between companies ?

**Comment by pedrobaeza** [comment]
Yeah, this happens when some localizations add account groups, as they are shared between all companies. The only solution I see is to hide them if no accounts found containing them.

**Comment by dreispt** [comment]
Hello, does it make sense to add a "Group By Company" option, to still see all data, but have it each company in it's own section?
