### ISSUE TITLE
[12.0][account_export_csv] no data in exported csv?

### ISSUE THREAD

**Issue by eguane** [OCA/account-financial-reporting#646]
Account report empty. Also tested with runbot.
csv sheet is generated without data, just first row with colonn description.
No error in log file. I tested sql request (copied from account_export_csv.py  for journal entries) directly into pgadmin succeffully.

Rgds

**Comment by aliomattux** [comment]
I can also verify this issue. I am not sure exactly the issue but know it has to do with the StringIO object not having any data.

line 36
data = self.queue.getvalue()
If you check the row before it has a value but the self.queue which is just a stringio is empty. It may have something to do with it initializing, not sure. I am not using the default functionality. I am working on 12 but was used to old extension base popup which no longer exists and ripped out some parts for use in a module to delivery generic csv download. I bypass the issue by converting dictionary values to string and then passing into the encoder.

**Comment by eguane** [comment]
well thanks for your help,
It seems running (not for invoice journal entries, "memoryError when") 
When I replace the code with:
    def writerow(self, row):
        # we ensure that we do not try to encode none or bool
        row = (x or '' for x in row)
        self.writer.writerow(row)
        # Fetch UTF-8 output from the queue ...
        data = self.queue.getvalue()
        # ... and reencode it into the target encoding as BytesIO
        data = self.encoder.encode(data)
        # write to the target stream
        self.stream.write(data)
        # empty queue
        self.queue.truncate(0)
        # empty queue with seek() instead of truncate()
        # see https://stackoverflow.com/a/9729516
        # also problems with seek() if next line is shorter than previous
        # chars of previous line are kept in the new one
        self.queue.flush()
keep one Memoryerror when I try to export journal entries, I am lookink to adapt odoo.conf without success.

**Comment by eguane** [comment]
This is the code modified into account_export_csv.py 

`    def writerow(self, row):
        # we ensure that we do not try to encode none or bool
        #row = (x or '' for x in row)
        self.writer.writerow(row)
        # fetch UTF-8 output from the queue ...
        data = self.queue.getvalue()
        # ... and reencode it into the target encoding as BytesIO
        data = self.encoder.encode(data)
        # write to the target stream
        self.stream.write(data)
        # seek() or truncate() have side effect then we reinitialize StringIO
        # https://stackoverflow.com/questions/4330812/how-do-i-clear-a-stringio-object
        self.queue.seek(0)
        self.queue.truncate(0)`
