### ISSUE TITLE
[10.0] account_financial_report_qweb: Residual amount

### ISSUE THREAD

**Issue by rousseldenis** [OCA/account-financial-reporting#656]
When launching several times the open items report, the residual amount is cumulated.

First one :
![image](https://user-images.githubusercontent.com/19529533/74019176-7af53100-4997-11ea-8b85-be86712574df.png)

Second one : 

![image](https://user-images.githubusercontent.com/19529533/74019207-8ea09780-4997-11ea-9d1e-3a4c65446aa0.png)

@JordiBForgeFlow @jcoux

**Comment by AaronHForgeFlow** [comment]
Hi @rousseldenis , did you find a solution for this?

**Comment by rousseldenis** [comment]
We don't have anymore projects in 10, so ... and I don't remember if it was fixed.

**Comment by pedrobaeza** [comment]
Let's close it then.
