### ISSUE TITLE
[13.0] Account Financial Report - Aged Partner Balance & Open Items

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/account-financial-reporting#672]
Both reports use date and due_date for calculation of the reports, should this not be updated to "invoice_date or date" and "invoice_date_due or due_date". The reports should be based on invoices when possible?

@JoanSForgeFlow

**Comment by pedrobaeza** [comment]
AFAIK `invoice_date_due` is the due date you put manually on invoice if no payment_term is specified. Then, when posted, the valid due date is the one on the account.move.line, which has been transferred from the other field, but subsequent modifications must be done on aml field, isn't it?

**Comment by CasVissers-360ERP** [comment]
@pedrobaeza 
My main issue is invoices where account_move.date != account_move.invoice_date. The option to do this is standardly available only on supplier invoices, but with a simple invisible = 0 also possible on customer invoices. I think you are correct about the due_date , but if we can use invoice dates throughout I think we should.

**Comment by pedrobaeza** [comment]
I don't agree, at least on due dates. Imagine a payment term that split the payment in several parts: you will have several aml with different due dates corresponding to that parts.

Showing the invoice date when applicable in these reports though can be important. How was done in previous versions?

**Comment by CasVissers-360ERP** [comment]
I agree on the due dates. Current workflow is better. Missed the several parts use case.

From what I can see (version 12) it contains the same workflow:
```
    ml.date,
    ml.date_maturity,
```
Since the date on move line is not always equal to the invoice date I think it's incorrect there as well. Or maybe I'm missing something?

**Comment by pedrobaeza** [comment]
I think both dates (aml date and invoice date) can be put in the report, but I would qualify this as improvement.

**Comment by CasVissers-360ERP** [comment]
Well I think an aged partner balance is oftenly used to check state of unpaid invoices. Not showing the invoice date seem illogical to me. Anyhow if considered an improvement, not a bug, I will close the issue.
