### ISSUE TITLE
[13.0] General ledger XLSX error

### ISSUE THREAD

**Issue by fa-odoo** [OCA/account-financial-reporting#681]
Hi i have a error that i can not debug when i try to print a not centralized general ledger:

![image](https://user-images.githubusercontent.com/42148719/80700700-b18da400-8acd-11ea-9e2d-56f13e398b3d.png)

![image](https://user-images.githubusercontent.com/42148719/80700668-a3d81e80-8acd-11ea-804c-ec499a74f275.png)

![image](https://user-images.githubusercontent.com/42148719/80700835-e568c980-8acd-11ea-9ee6-e75a59357120.png)

**Comment by fa-odoo** [comment]
@pedrobaeza can you please help with this

**Comment by MiquelRForgeFlow** [comment]
@JoanSForgeFlow
