### ISSUE TITLE
[BUG][12.0] account_financial_report: VAT Report - Invoices and Refunds are added

### ISSUE THREAD

**Issue by pasgou** [OCA/account-financial-reporting#684]
When we have invoices and refunds, bases are added (but the taxes are ok).
I have tested this issue in a french version with only a company with the french chart of account.
I can't find the code but it seems that it is related about the fact that the amounts are not signed in the account.move model.

seems to be the same error as the first one reported in #611

**Comment by Martronic-SA** [comment]
I confirm that error.
I think the tax base amount should be stored signed. That would solve that reporting problem but also in the list views of account move lines.
