### ISSUE TITLE
[13.0] Label or description of the move item is not displayed as it was for older version

### ISSUE THREAD

**Issue by jpcass** [OCA/account-financial-reporting#687]
The report is not showing the description or label of the move item, it only shows the reference, in older version the label was shown in the same column.

It is important to have the description (label) becuase it has valid information for analysis as for example tax name, product, name, invoice description and others.

**Comment by pedrobaeza** [comment]
Screenshots? Which report? Which module?

**Comment by jpcass** [comment]
For General Ledger report in financial report app, attached screenshots.
Regards
![General Ledger report v10](https://user-images.githubusercontent.com/29762062/81511716-bdf5d600-92f1-11ea-9fb1-9fc962b59bdb.jpg)
![General Ledger report v13](https://user-images.githubusercontent.com/29762062/81511717-bf270300-92f1-11ea-8efc-eb3fcdc4ea3d.jpg)

**Comment by pedrobaeza** [comment]
Well, not sure when this change was done, as you are talking about an old v10, but let's see if @JordiBForgeFlow can say as he has made several refactoring in this.
