### ISSUE TITLE
[13.0] clicking on amount wont show you the details of the account move lines

### ISSUE THREAD

**Issue by yung-wang** [OCA/account-financial-reporting#690]
1. Go to runbot and go to reports OCA General Ledger.
2. Click on View, so you can see the report on screen.

Try to click on amounts. Nothing happens. This used to work in V12.

I see the click event in the JS file.
https://github.com/OCA/account-financial-reporting/blob/13.0/account_financial_report/static/src/js/account_financial_report_widgets.js

> "click .o_account_financial_reports_web_action": "boundLink",
            "click .o_account_financial_reports_web_action_multi": "boundLinkmulti",
            "click .o_account_financial_reports_web_action_monetary":
                "boundLinkMonetary",
            "click .o_account_financial_reports_web_action_monetary_multi":
                "boundLinkMonetarymulti",

**Comment by kittiu** [comment]
We found it from today version of this report also. Any updates?

**Comment by gjotten** [comment]
> We found it from today version of this report also. Any updates?

@kittiu and @yung-wang the above two PRs point towards the solution.
