### ISSUE TITLE
VAT (TAX) report not showing taxes with amount zero

### ISSUE THREAD

**Issue by OpencloudPro** [OCA/account-financial-reporting#698]
Its important to show all taxes even with amount zero, because the net amount is going to be > zero.

**Comment by pedrobaeza** [comment]
Odoo Version? Module?

**Comment by OpencloudPro** [comment]
> Odoo Version? Module?

Odoo **V12**, module **account_financial_report**, **vat_report.py** file

**Comment by pedrobaeza** [comment]
I think that's not possible, as it only show journal items with the tax tag, but I don't use that report.

**Comment by OpencloudPro** [comment]
The tax has tag, and has group, but it does not appear because its amount is zero. 
When i change amount to 1% and do a new invoice, it appears on the report. 
I think this is a bug, because in many countries such as Portugal, we have zero tax but we need to sum the net amount for that tax and make sure it appears in the tax report.

**Comment by francescoUi** [comment]
I have bypassed this by editing the account addon (account/models/account_invoice.py) replacing

`if tax_line.amount_total:`

by

`if 1:`

You then need to regenerate the invoices for the tax line to appear

Making this change is at your own risk!

**Comment by OpencloudPro** [comment]
> I have bypassed this by editing the account addon (account/models/account_invoice.py) replacing
> 
> `if tax_line.amount_total:`
> 
> by
> 
> `if 1:`
> 
> You then need to regenerate the invoices for the tax line to appear
> 
> Making this change is at your own risk!

Thanks for sharing but its not a good resolution, it makes the taxes not appear and so creating more bugs than fixing the report :) 
Everything in invoice and move looks good, i took a look at the query of the report can not understand why its not printing the zero values... The account.move.line is there and is tax_exigible... its just zero..

**Comment by francescoUi** [comment]
With the original condition, no move line is created if the tax amount is equal to 0

**Comment by OpencloudPro** [comment]
> > I have bypassed this by editing the account addon (account/models/account_invoice.py) replacing
> > `if tax_line.amount_total:`
> > by
> > `if 1:`
> > You then need to regenerate the invoices for the tax line to appear
> > Making this change is at your own risk!
> 
> Thanks for sharing but its not a good resolution, it makes the taxes not appear and so creating more bugs than fixing the report :)
> Everything in invoice and move looks good, i took a look at the query of the report can not understand why its not printing the zero values... The account.move.line is there and is tax_exigible... its just zero..

Ok, i changed it to "if tax_line.amount_total>=0:" and it fixes. Not perfect but is a temporary fix. 
Thanks

**Comment by pedrobaeza** [comment]
I don't recommend that patch to anyone, as it's touching the core with a very bad decision only for fixing the problem in other place.

**Comment by OpencloudPro** [comment]
me neither. I did and inherit in other app like so:

# fix to generate account.move.line from zero taxes to
@api.model
    def tax_line_move_line_get(self):
        res = super(AccountInvoice, self).tax_line_move_line_get()
        # keep track of taxes already processed
        done_taxes = []
        # loop the invoice.tax.line in reversal sequence
        for tax_line in sorted(self.tax_line_ids, key=lambda x: -x.sequence):
            tax = tax_line.tax_id
            if tax.amount_type == "group":
                for child_tax in tax.children_tax_ids:
                    done_taxes.append(child_tax.id)

            analytic_tag_ids = [(4, analytic_tag.id, None) for analytic_tag in tax_line.analytic_tag_ids]
            if tax_line.amount_total == 0: # fixed
                res.append({
                    'invoice_tax_line_id': tax_line.id,
                    'tax_line_id': tax_line.tax_id.id,
                    'type': 'tax',
                    'name': tax_line.name,
                    'price_unit': tax_line.amount_total,
                    'quantity': 1,
                    'price': tax_line.amount_total,
                    'account_id': tax_line.account_id.id,
                    'account_analytic_id': tax_line.account_analytic_id.id,
                    'analytic_tag_ids': analytic_tag_ids,
                    'invoice_id': self.id,
                    'tax_ids': [(6, 0, list(done_taxes))] if done_taxes and tax_line.tax_id.include_base_amount else []
                })
            done_taxes.append(tax.id)
        return res

**Comment by francescoUi** [comment]
It was just an hint and not a patch ^^
