### ISSUE TITLE
[13] VAT Report Date selection "=" missing for less than or equal

### ISSUE THREAD

**Issue by Florianson** [OCA/account-financial-reporting#710]
In vat_report.py

Instead of ("date", "<", date_to), please change to ("date", "<=", date_to), 

Equal sign after "<"

Otherwise the last day of the entered period is not considered.

![image](https://user-images.githubusercontent.com/56293519/88659883-114c1900-d0d6-11ea-8f45-7bbad3100c8e.png)

Thanks a lot

**Comment by mfmkhatri** [comment]
Seconded. Same issue here.

**Comment by astirpe** [comment]
Seems this was already fixed with https://github.com/OCA/account-financial-reporting/commit/d0ae3d660fe4a12b8da1f8d36b86c7e73b5f6f2b
