### ISSUE TITLE
[13.0] account-financial-reporting, translations not loaded

### ISSUE THREAD

**Issue by yung-wang** [OCA/account-financial-reporting#712]
1. Go to runbot and activate language nl_NL.
2. Check if terms are translated in Settings:
![image](https://user-images.githubusercontent.com/30628967/88811091-6eb79700-d1b6-11ea-9d3c-d2f37605207f.png)

3. Go to report OCA General Ledger.
4. Click on View. Since user is still en_US, the report shows ENG. This is OK.
![image](https://user-images.githubusercontent.com/30628967/88811226-973f9100-d1b6-11ea-9452-a37f6e0c5b3d.png)

5. Change the language of the user to nl_NL.
6. Go to report OCA General Ledger.
7. Click on View. The report still shows ENG. This is NOT OK.
![image](https://user-images.githubusercontent.com/30628967/88811417-ce15a700-d1b6-11ea-8efd-55e0db9c69b6.png)

This also happens for the Excel export. The PDF report works fine.

**Comment by HaraldPanten** [comment]
Hi, @yung-wang I'm sure that you already did, but let me ask you...

You refreshed the internet browser between steps 5 and 6, right?

**Comment by yung-wang** [comment]
@HaraldPanten Yes, this is now fixed in [[13.0][FIX] account_financial_report: translation not loaded #715](https://github.com/OCA/account-financial-reporting/pull/715)
