### ISSUE TITLE
[13] Trial Balance not showing all accounts at 0

### ISSUE THREAD

**Issue by Levi-Bensley** [OCA/account-financial-reporting#716]
When doing a trial balance with the show accounts at 0 option set to true not all the accounts will be shown on the reports.

**Comment by HaraldPanten** [comment]
Hi @Levi-Bensley could you give us more details?

Which accounts should be shown and are not being shown? How are you setting the report? I mean... dates, account filters... Have you unchecked the checkbox that hides the accounts at 0?

Thx

**Comment by Levi-Bensley** [comment]
> Hi @Levi-Bensley could you give us more details?
> 
> 
> 
> Which accounts should be shown and are not being shown? How are you setting the report? I mean... dates, account filters... Have you unchecked the checkbox that hides the accounts at 0?
> 
> 
> 
> Thx

01/01/2020 -> 31/12/2020
All Posted Entries
Hide accounts at 0 = False
No hierarchy 
(Rest left at default)
Export XLSX

**Comment by HaraldPanten** [comment]
Which account is not being shown and should be shown? 
Do you have a screenshot of the assets in this "missing" account?
I'd like to see how is that account configurated: type, deprecation (true/false)?

**Comment by Levi-Bensley** [comment]
For example:
Office Equipment appears in the report
![Office Equipment Appears](https://user-images.githubusercontent.com/54573198/89623538-b01e0580-d88c-11ea-819d-023706aa5de4.PNG)
However the Office Equipment Depreciation doesn't?
![Office Equipment Doesnt Appears](https://user-images.githubusercontent.com/54573198/89623545-b1e7c900-d88c-11ea-9dd9-6300093eda64.PNG)
Yet they are set up the same

**Comment by HaraldPanten** [comment]
You said that you set: "All posted entries".

Could you check if the depreciations assets are in the correct state? or are them in "Draft" state?

Try using "All Entries" and let's see...

**Comment by JoanSForgeFlow** [comment]
Hello @Levi-Bensley,

This problem was fixed in v13 in this PR #682, that is already merged. Which is a forward port of this PR in v12 #660. 
Thanks for your review, from now on it should work fine.
