### ISSUE TITLE
[13.0][BUG] account_financial_report: Incorrect JS widget dependency

### ISSUE THREAD

**Issue by gaikaz** [OCA/account-financial-reporting#722]
Odoo v13 doens't have `web.ControlPanelMixin` widget anymore, yet `account_financial_report` still tries to depend on it in 
[account_financial_report/static/src/js/account_financial_report_backend.js](https://github.com/OCA/account-financial-reporting/blob/574a89f7524947cc558debe0d284f29fa6dddbc7/account_financial_report/static/src/js/account_financial_report_backend.js#L8)

Which leads to errors in browser console:

![image](https://user-images.githubusercontent.com/17097810/91827878-1c034c00-ec48-11ea-8772-a48f1b347510.png)
_(picture taken on Community Runbot)_

**Comment by pedrobaeza** [comment]
Are you able to provide a fix for this?

cc @JordiBForgeFlow

**Comment by gaikaz** [comment]
OH! You were asking me! Sorry, I didn't notice the "cc" for Jordi :stuck_out_tongue_closed_eyes: 

Sorry, no. I haven't looked into that change between v12 and v13 much more than this.
And I currently don't have much of resources to do it during work hours.

**Comment by gaikaz** [comment]
Can't reproduce the issue on runboat anymore. Must have been fixed.
Moving on...
