### ISSUE TITLE
[13.0] [customer_statement] Wrong permissions for partner_statement?

### ISSUE THREAD

**Issue by atrueba** [OCA/account-financial-reporting#723]
Hi,

On a 13.0 installation the customer statement report seems to be available to all users with access to contacts instead of being restricted to the accounting group or any subgroup. Can someone please try to reproduce and confirm?

- Create a new user with no special privileges
- User should only have access to these modules: Chat, Contacts (in my case also Employees and Boards, but that may vary).
- Select any contact
- Choose the customer statement report from the dropdown and generate it

Regards.

**Comment by atrueba** [comment]
Hi,

I've done some more checking and this seems not to be a bug but an incorrect translation. The module creates two security groups, "Use activity statement" and "Use outstanding statements", whose translation to spanish is not fully correct, so I didn't realize my test user with default privileges had inherited those two check-items.

I believe the correct translations to spanish should be:
- "Use activity statements" -> "Ver informes de estado de cuentas"
- "Use outstanding statements" -> "Ver informes de saldos pendientes"

I'm not familiar with the current translation process, so if anyone can update those terms I think this bug can be closed.

Regards.

**Comment by gdgellatly** [comment]
@atrueba well translation issue aside, I think you have a more general point here as those are technical security groups and really should be displayed only with the Billing Manager security level IMO.
