### ISSUE TITLE
Slow auto vacuum on journal ledger report

### ISSUE THREAD

**Issue by wpichler** [OCA/account-financial-reporting#727]
Hi all,

i've encountered a very slow delete statement in here:

https://github.com/OCA/account-financial-reporting/blob/a3eacc2fe34d84ce0fc0bbefc7002dcebd2544b9/account_financial_report/report/journal_ledger.py#L625

This will get called on auto vacum

In my case it took longer than the default timeout - so it restarted again and again

Wouldn't it be much faster to use:

truncate report_journal_ledger_move, report_journal_ledger_move_line;

**Comment by pedrobaeza** [comment]
Why it's slow? Any extra FK? Truncate won't work without cascade, and maybe it has some side effects.

**Comment by wpichler** [comment]
No modifications from my side - was just slow as it was.
Truncate does work without cascade here - i'ved tested it.
To be sure it would be possible to first try the truncate - if it fails - then fall back to normal delete

**Comment by dalonsod** [comment]
hello,

@pedrobaeza the changes made by commit https://github.com/OCA/account-financial-reporting/commit/f22cb07c7680912160952efe5ba117c4c63a4aca were not enough for me, because `report_journal_ledger_move` deletion was still slow. I've tested on database and these deletion order worked for me:
```

-- DELETE 429 Query returned successfully in 446 msec.
DELETE from report_journal_ledger_report_tax_line;
-- DELETE 1292018 Query returned successfully in 4 secs 326 msec.
DELETE from report_journal_ledger_move_line;
-- DELETE 429 Query returned successfully in 205 msec.
DELETE from report_journal_ledger_journal_tax_line;
-- DELETE 264732 Query returned successfully in 3 secs 669 msec.
DELETE from report_journal_ledger_move;
-- DELETE 442 Query returned successfully in 1 secs 49 msec.
DELETE from report_journal_ledger_journal;
-- DELETE 13 Query returned successfully in 411 msec.
DELETE from report_journal_ledger;
```

So, should be correct adding these deletions (except the last one), not only `report_journal_ledger_move_line` and `report_journal_ledger_move` ones to the `_transient_vacuum()` method for journal ledger report? If I'm right, I should make a PR. Thanks!

**Comment by pedrobaeza** [comment]
Yeah, I think it's correct to do that.

**Comment by gaikaz** [comment]
Just stumbled upon the same issue.
One of our client's Odoo was just stuck and looking at `pg_activity` showed this disaster (loads of blocked queries after it...):
![image](https://user-images.githubusercontent.com/17097810/106358214-536b4700-6313-11eb-98f5-9bb1a9508b43.png)
That's **9.5 hours** of the query running! 👀 

Like @dalonsod already showed, apparently emptying out the "lines" table isn't enough for speeding the "move" table cleaning, as for some reason `pkey` checking still takes long (did some EXPLAIN queries to find this, thanks to [Justin Workman here](https://dba.stackexchange.com/questions/37034/very-slow-delete-in-postgresql-workaround#comment430283_138270))

Thought, the way I solved it feels a little more elegant: just add an index for `report_move_id` field on `report_journal_ledger_move_line`.
On that same client's database, after adding the index, the query completed in **~6s**!

Will make a PR in a minute.

**Comment by pedrobaeza** [comment]
See #750

**Comment by gaikaz** [comment]
Oops... 😄 
Didn't find it before.

**Comment by gaikaz** [comment]
@pedrobaeza Now I also got curious. Could it be that the manual SQL queries here are not needed after all?
Maybe with the index, that vacuum would be fast enough by default?

**Comment by pedrobaeza** [comment]
Well, they are harmless anyway. The problem with the index is that the data filling is going to be a bit slower, but not having a better option and being so critical on vacuum, better to go with this option.

**Comment by gaikaz** [comment]
Hopefully this also increases the reading performance, which should balance out the new insertion cost.
Anyway, thanks for working on weekends. You should take a break, thought 😜

**Comment by dalonsod** [comment]
hello @gaikaz that's great! I've tried to put into code those additional `DELETE` stuff, but things were more complicated than I'd expected (modifying vacuum general schema, with several transient models, linked themselves, has been very difficult to accomplish, at least for me).

When the PR to v11 is done I'll check it
