### ISSUE TITLE
error dependency missing:

### ISSUE THREAD

**Issue by vanderperre** [OCA/account-financial-reporting#738]
in:
account_financial_report_backend.js
odoo.define("account_financial_report.account_financial_report_backend", function(

error dependency missing:
![Screenshot 2020-10-30 at 13 13 55](https://user-images.githubusercontent.com/55125626/97703962-cfa28400-1ab1-11eb-938a-5394df481eaf.png)

this class doesn't exist in v13, v13e : web.ControlPanelMixin
L8    var ControlPanelMixin = require("web.ControlPanelMixin");

regards,

**Comment by captivea-dcr** [comment]
I get the same error here and Odoo webclient is not stable after installing the module `account_financial_report`.

cc @hbrunn @pedrobaeza @guewen
