### ISSUE TITLE
account_financial_report_webkit : How can I modify my general ledger presentation? 

### ISSUE THREAD

**Issue by madox35** [OCA/account-financial-reporting#75]
Hi,
I'm looking for erase the "counterpart" in the general ledger.
I've tried to delete this part in this file: /usr/lib/python2.7/dist-packages/openerp/addons/account_financial_report_webkit/report/templates/account_report_general_ledger.mako

In this file i had comment all part of "counterpart" (like 3lines) --> doesn't work
Then i just deleted the file (account_report_general_ledger.mako) --> doesn't work

The PDF is still create all the general ledger. The file seems to be the wrong one.
Did i need to modify an other file may be? Which one?

Thanks for helping!

**Comment by pedrobaeza** [comment]
Sorry, but this is a question, not an issue. Closing.
