### ISSUE TITLE
[13.0] [BUG] Wrong default value on Move Type field.

### ISSUE THREAD

**Issue by DS-Landoo** [OCA/account-financial-reporting#753]
Hello,

When the account_tax_balance is installed, among other things, it adds the move_type field on Invoices, Credit Notes, Vendor Bills and Refunds (model= account.move). The default move_type for Invoices is "Receivable", for Credit Notes "Receivable refund", for Vendor Bills "Payable" and for Refunds "Payable refund". This means, that every new, lets say Credit Note, will have "Receivable Refund" as the Move Type. This is OK.

However, the **Invoices and Credit Notes that had been created before the account_tax_balance has been installed** have their move_type swapped. So, prior Invoices have "Receivable  refund" and Credit Notes have "Receivable". This is NOT OK. Bills and Refunds do not have the same problem, their Move Type is always right.

Its a very minor bug that can be solved quickly with mass editing, but I still suggest looking into it. Thank you in advance.

Regards,

**Comment by pedrobaeza** [comment]
Maybe it's a problem here on the hook:

https://github.com/OCA/account-financial-reporting/blob/13.0/account_tax_balance/hooks.py#L26
