### ISSUE TITLE
Open Items when reconciled by Partial Reconciliation still reflect 0 amount residual move lines in report

### ISSUE THREAD

**Issue by farazbdm** [OCA/account-financial-reporting#755]
https://github.com/OCA/account-financial-reporting/blob/3e04acb9ae95740b6f86c6196627408ff4d09203/account_financial_report_qweb/report/open_items.py#L372

@pedrobaeza can you please recommend who can resolve this issue.

Steps to Reproduce:

1. Create Invoice
2. Create 2 payments
3. Do Partial reconciliation with the Invoice, both the payments
4. And Make Invoice Due Amount 0.
5. Generate Open Items Report

Expected Behavior:
Invoice Receivable Line should not appear.

Whereas:
Line still reflects in report with Amount Residual == 0 though,
there is no way to get this settled and clear out from this report. It will always stay there reflecting line.

![image](https://user-images.githubusercontent.com/10349579/108172914-e0394180-7116-11eb-92e6-608d79799ee1.png)

**Comment by pedrobaeza** [comment]
Well, putting the issue with the steps to reproduce the problem is the first step, so people can see it, but no specific solver for this.
