### ISSUE TITLE
Aged Partner Balance by invoice

### ISSUE THREAD

**Issue by max3903** [OCA/account-financial-reporting#76]
Provide an aged partner balance report with invoice details:

| Partner | Invoice | 0 - 30 | 30 - 60 | 60 - 90 | 90+ | Total |
| --- | --- | --- | --- | --- | --- | --- |
| Agrolait |  |  |  |  |  |  |
|  | SAJ/2015/0001 |  |  |  | 1000 $ | 1000 $ |
|  | SAJ/2015/0003 | 2000 $ |  |  |  | 2000 $ |
|  | **Total** | **2000 $** |  |  | **1000 $** | **3000 $** |
| Asustek |  |  |  |  |  |  |
|  | SAJ/2015/0002 |  | 5000 $ |  |  | 5000 $ |
|  | **Total** |  | **5000 $** |  |  | **5000 $** |
| **Total** |  | **2000 $** | **5000 $** |  | **1000 $** | **8000 $** |

Mockup of the wizard:
![customer invoices - openerp 2015-09-02 11-49-55](https://cloud.githubusercontent.com/assets/939952/9636715/f60ab966-516a-11e5-8fcf-d97c7ab15476.png)

**Comment by max3903** [comment]
https://github.com/moturi12/shared_public_addons_v7

**Comment by pedrobaeza** [comment]
This seems to be fixed and any way, it's a very old version. Closing.
