### ISSUE TITLE
[13.0] Wrong values in groups in Trial Balance

### ISSUE THREAD

**Issue by rquevedo** [OCA/account-financial-reporting#765]
Hi folks,
I'm getting wrong values in some parent groups when running Trial Balance. For example group "2" get wrong number even when "21" and "22" has the right values and are the only children of "2".
After debug "_get_hierarchy_groups", method that compute values of groups that don't have direct child accounts, I notice that group "2" has been computed before group "21" ends to sum child values ("210001", "210002", etc.).
I think that's the issue

**Comment by jvbp** [comment]
Hi,

I have a similar or same problem in group "4".

If I use Child Accounts option like below, the resulto of group 4 is wrong. 

![image](https://user-images.githubusercontent.com/52859958/159255461-71190f3c-0a12-43b1-9828-859593608f7d.png)

When I Export to Excel I have the follow situactión:
![image](https://user-images.githubusercontent.com/52859958/159262522-f00b2e17-481c-4333-abb3-c93bc3044875.png)


If I use Computed Values option like below, the result of group 4 is correct but this optión doesn't allow me to export in Excel, only on screen (well it allow me to export but I have no groups). 
![image](https://user-images.githubusercontent.com/52859958/159261586-b529a8bd-223f-42fc-8cdc-5a6a7e5d02f7.png)

![image](https://user-images.githubusercontent.com/52859958/159262726-c4ccc1f4-318d-4166-84ee-fd1bfca89a58.png)


Thanks in advance.

**Comment by jvbp** [comment]
Hi again,

We fixed this issue with the following workaround (just code marked between INIT and END) in trial balance report. It works now in View, PDF and Excel modes when Child Accounts are marked. I'm sure there is better ways to do that but fully undestanding how this module works is very dificult.

            if hierarchy_on == "relation":
                groups_data = self._get_groups_data(
                    accounts_data, total_amount, foreign_currency
                )
                trial_balance = list(groups_data.values())
                trial_balance += list(accounts_data.values())
                trial_balance = sorted(trial_balance, key=lambda k: k["complete_code"])
                for trial in trial_balance:
                    counter = trial["complete_code"].count("/")
                    trial["level"] = counter

                    # INIT - FIX LEVEL 0 TRIAL BALANCE
                    if counter == 0:
                        trial["initial_balance"] = 0.0
                        trial["debit"] = 0.0
                        trial["credit"] = 0.0
                        trial["balance"] = 0.0
                        trial["ending_balance"] = 0.0
                        complete_code = trial["complete_code"]
                        for trial_level_0 in trial_balance:
                            counter_level_0 = trial_level_0["complete_code"].count("/")
                            if trial_level_0["complete_code"][:1] == complete_code and counter_level_0 == 1:
                                trial["initial_balance"] += trial_level_0["initial_balance"]
                                trial["debit"] += trial_level_0["debit"]
                                trial["credit"] += trial_level_0["credit"]
                                trial["balance"] += trial_level_0["balance"]
                                trial["ending_balance"] += trial_level_0["ending_balance"]
                    # END - FIX LEVEL 0 TRIAL BALANCE

            if hierarchy_on == "computed":
                groups_data = self._get_computed_groups_data(
                    accounts_data, total_amount, foreign_currency
                )
                trial_balance = list(groups_data.values())
                trial_balance += list(accounts_data.values())
                trial_balance = sorted(trial_balance, key=lambda k: k["code"])
            if hierarchy_on == "none":
                trial_balance = list(accounts_data.values())
                trial_balance = sorted(trial_balance, key=lambda k: k["code"])
