### ISSUE TITLE
Tax balance migration to 14.0

### ISSUE THREAD

**Issue by SimoRubi** [OCA/account-financial-reporting#770]
Hi all,
I am migrating an enterprise DB from 10.0 to 14.0, I have migrated the core with https://upgrade.odoo.com/upload and in the upgrade report they mention:
> The field 'move_type' from the model 'account.move' is now a standard Odoo field, but it already existed in the database (coming from a non-standard module) and thus has been renamed to 'move_type_custom'

I am experiencing a _small_ issue with this code:
https://github.com/OCA/account-financial-reporting/blob/a648e2c7482ff56a41fc7bde598d00fdfb8a43a6/account_tax_balance/migrations/14.0.1.0.0/pre-migration.py#L17
Before this is executed, account moves have these types:
```
# select move_type from account_move group by move_type;
  move_type  
-------------
 entry
 in_invoice
 in_refund
 out_invoice
 out_refund
(5 rows)
# select move_type_custom from account_move group by move_type_custom;
 move_type_custom  
-------------------
 payable_refund
 
 payable
 receivable_refund
 receivable
 other
 liquidity
(7 rows)
```
As the mentioned report says, they have correctly moved the old `move_type` to `move_type_custom`.

After the execution of linked code, account move types are like this:
```
# select move_type from account_move group by move_type;
 move_type 
-----------
 entry
(1 row)
# select move_type_custom from account_move group by move_type_custom;
 move_type_custom  
-------------------
 payable_refund
 
 payable
 receivable_refund
 receivable
 other
 liquidity
(7 rows)
# select financial_type from account_move group by financial_type;
 financial_type 
----------------
 out_invoice
 in_invoice
 in_refund
 entry
 out_refund
(5 rows)
```

The issue is that now none of the account moves is presented as an invoice, so there are _apparently_ no invoices.
In order to solve this, I'll simply copy `financial_type` to `move_type` and `move_type_custom` to `financial_type`, but the question is: could this issue be prevented?

The problem here is that the migration resets the `move_type` field but I can't see how that can happen in https://github.com/OCA/openupgradelib/blob/01cc9a1a8933376dcf6516b9a38030c6d0f16072/openupgradelib/openupgrade.py#L574
So I don't really know if 

- this is expected from openupgradelib, so the upgrade script has to be fixed
- this is not expected from openupgradelib, so it has to be fixed over there
- I had to do something before migrating the module

**Comment by pedrobaeza** [comment]
The script is not correct indeed. Part should be handled in OpenUpgrade `account` pre-migration, renaming the column to the definitive name. With enterprise, you should need to rename the column manually from `move_type_custom` to `financial_type`.

**Comment by SimoRubi** [comment]
> The script is not correct indeed. Part should be handled in OpenUpgrade `account` pre-migration, renaming the column to the definitive name. With enterprise, you should need to rename the column manually from `move_type_custom` to `financial_type`.

Thanks for your opinion :) 
I'd like to fix this for whoever will do a similar migration in the future but I see there is no migration for `account` in OpenUpgrade in `14.0`.
One solution to avoid manual modifications could be the following:

- in OpenUpgrade's `account` script, rename `move_type` (if exists) to `move_type_custom`.
  This way, OpenUpgrade and Enterprise behave in the same way, so we can update the module's migration script to:
- in `account_tax_balance` rename `move_type_custom` (fallback on `move_type`) to `financial_type`

What do you think?

**Comment by pedrobaeza** [comment]
OpenUpgrade v14 is not yet developed (we are on it - soon, but not yet -).

I don't like too much such nomenclature, as it can collide with other existing fields, and will require 2 steps. At OpenUpgrade, we use a name that can't collide: `openupgrade_legacy_x_y_old_field_name`, where x and y is the target version. Even more, being able to do the renaming in one step, I prefer to go in OU directly for the good name and not adding anything in this module.

Being such special case, I think we can include here a migration script detecting the column `move_type_custom` (let's hope anybody have such column name in other module), and perform the renaming for those enterprise upgrade users.
