### ISSUE TITLE
Trial Balance report downloaded in excel for accounts with currency does not show balances in currencies

### ISSUE THREAD

**Issue by paulapose** [OCA/account-financial-reporting#794]
Good Morning,

My name is Paula Pose, I am a Functional Analyst and I work at Nexit, a company located in Uruguay that is a Gold Partner of Odoo.

I need your help to solve the following problem: there is an error in the Trial Balance report (from the OCA accounting reports).
When it is issued in xlsx format and the Show foreign currency and Show Partner Details checkbox are active when clicking "Export XLSX" in the downloaded excel, it does not show the data in the columns: Cur., Initial balance, Ending balance.
 
This only happens with the report format in Excel. When the Show foreign currency checkbox is active, and Show Partner Details is false, the issued Excel shows the "Initial balance" and "Ending balance.", But does not show the currency in the "Cur." Column.

Attached below is a Trial Balance report that has balances in currencies but the excel does not show it (if it is shown in the view when clicking on "View" or on "Export PDF")

The testing was done in a runbot in the Odoo community version 13. But this problem is also in the enterprise version.

I really appreciate your attention and I look forward to an answer.
Have a very nice day

Greetings

Paula

[report_trial_balance (buton Export XLSX).xlsx](https://github.com/OCA/account-financial-reporting/files/6592820/report_trial_balance.buton.Export.XLSX.xlsx)
![trial balance report wizard](https://user-images.githubusercontent.com/85301806/120673277-692b7d00-c469-11eb-98fe-51d177213795.PNG)
![Report Trial Balance (button View)](https://user-images.githubusercontent.com/85301806/120673284-69c41380-c469-11eb-9fe4-5c9bcf2f86d1.PNG)

**Comment by JordiBForgeFlow** [comment]
What is the version you are using?

**Comment by paulapose** [comment]
Odoo version 13 community



Regards,


Cra. Paula Pose


Analista Funcional



Primeros Odoo Gold Partners en Uruguay





Tel.: (+598) 97 08 60 60

Pozos del Rey 1325, of. 3., Montevideo - Uruguay

http://www.nexit.com.uy/











---- En jue, 03 jun 2021 12:57:09 -0300 Jordi Ballester Alomar ***@***.***> escribió ----




What is the version you are using?
