### ISSUE TITLE
account_financial_report_webkit_xls limited to 65536 rows

### ISSUE THREAD

**Issue by guewen** [OCA/account-financial-reporting#8]
The module `account_financial_report_webkit_xls` exports the financial reports to Excel files.
It uses the `xlwt` library so it is compatible with the versions of Excel prior to 2007 which are known to support only 65536 rows per sheet.
65536 rows is a very low limit for reports such as a general ledger or partner ledger.

I propose to replace the xlwt library by openpyxl which allow to generate `.xlsx` files (Excel 2007+). Thus, the limit would be 1 048 576 rows.

The downside is that people with Excel versions prior to 2007 would not be able to open the files, but since Libreoffice 3.3.3+ can open the files, I don't consider that as a real problem.

**Comment by sbidoul** [comment]
:+1: xlsx also works in Excel 2003 with a compatibility pack from Microsoft if my memory is correct.

But first the huge pep8 effort in #6 by @laetitia-gangloff must be finalized and merged.

**Comment by guewen** [comment]
Didn't saw this PR, it is nearly done, still a few annoying lines :-(

This module will be painful to port over openenpyxl I feel. It depends on report_xls which seems intimately tied with xlwt. Should I create a report_xlsx and depends on this one instead?
Or rather modify report_xls in place?

**Comment by pedrobaeza** [comment]
I agree, but first we must fix with current base code.

**Comment by guewen** [comment]
> I agree, but first we must fix with current base code.

What do you mean by "fix"?
Please read my comment on https://github.com/OCA/account-financial-reporting/pull/6#issuecomment-52303873

**Comment by pedrobaeza** [comment]
I mean fix PEP8 correctly in the @laetitia-gangloff branch.

**Comment by guewen** [comment]
So please give your opinion on https://github.com/OCA/account-financial-reporting/pull/6#issuecomment-52303873

**Comment by bwrsandman** [comment]
What's the status on this

**Comment by pedrobaeza** [comment]
This is a limitation of XLS itself. As there's now report_xlsx, I close this.
