### ISSUE TITLE
[11.0] account_financial_reporting InternalError: too much recursion

### ISSUE THREAD

**Issue by pedroortega-punt** [OCA/account-financial-reporting#800]
In a V11 installation with grouping of the accounting entries by account, it has 325,000 accounting entries in a year, the journal to be printed is impossible to generate either in view, in pdf, or in excel, there are errors in execution times and memory sizes.

Memory and times have been expanded to the maximum, does anyone know a solution to print?

In V13 onwards, the entries are not grouped by accounting accounts, but if the invoices have 200 lines, the accounting entry will have some more, can you tell me for this type of companies that have many lines what is the solution?

It is a very important concern for this type of facility. Alternatives or solutions are sought.

**Comment by rdeheele** [comment]
same problem in V12
