### ISSUE TITLE
[13.0][BUG] account_financial_report, error Aged Partner Balance with Show move line details

### ISSUE THREAD

**Issue by kittiu** [OCA/account-financial-reporting#808]
Just install module with demo database, and run Aged partner Balance report.

Affected version: 13.0.1.8.0 (latest)

![image](https://user-images.githubusercontent.com/1973598/130309539-fd22107c-e875-4ec9-97cf-7e32f298d86f.png)

![image](https://user-images.githubusercontent.com/1973598/130309546-5c6a899f-dc7a-424a-b9b7-249f48f323af.png)

![image](https://user-images.githubusercontent.com/1973598/130309336-23f60816-7959-4627-a204-6d581cee2d83.png)

**Comment by SimoRubi** [comment]
Found the same issue on `14.0` and working on a fix, stay tuned :)

**Comment by SimoRubi** [comment]
@kittiu can you check if https://github.com/OCA/account-financial-reporting/pull/811 fixes this issue and leave a review there? Thanks!
