### ISSUE TITLE
Translation Portuguese

### ISSUE THREAD

**Issue by KBrossmann** [OCA/account-financial-reporting#812]
module: partner_statement
version: 13.0

Great module:

I found the Portuguese translation (Source Term = "Balance Forward") a bit awkward, It translates to "Saldo Futuro" but it should be "Transporte" or "Saldo transportado" instead.

I wasn't able to find the term in the translations, so maybe I just miss something here ;)

Is there a way to modify the translation of the pdf statement?

**Comment by pedrobaeza** [comment]
Please join the translation team and change it yourself:

https://odoo-community.org/page/translate
