### ISSUE TITLE
[14.0][BUG] account_financial_report : issue with columns of first line

### ISSUE THREAD

**Issue by tv-openbig** [OCA/account-financial-reporting#815]
There is an issue with the first line representing the column sums of the fields debit/credit.
As you can see in the following screenshot there is a wrong offset of a colum, breaking the table of the report. 
![Bildschirmfoto 2021-09-08 um 18 36 42](https://user-images.githubusercontent.com/8348598/132549852-53bc48a5-59a2-4770-a8ca-1ecd1f155bbe.png)

This happens with the Journal Ledger and Trial Balance.

**Comment by pedrobaeza** [comment]
Steps to reproduce it?

**Comment by tv-openbig** [comment]
> Steps to reproduce it?

1.) Invoicing App / Reporting / OCA accounting reports / Journal Ledger
2.) Select a start/end date or a pre-defined date_range (with account moves for sure)
3.) Click on "View"
