### ISSUE TITLE
Sorting Issue in general ledger report with respect to Rec. Debit Credit and Cumul. Bal column 

### ISSUE THREAD

**Issue by muhammadnaeem786** [OCA/account-financial-reporting#827]
In general_ledger report  records are not sorted with respect to rec. debit and credit and cumul. bal. column.while printing excel report seleting filter partner Rec. , Debit , Credit and Cumul. Bal. columns recocords are not sorted which is a very difficult way to read report.

**Comment by pedrobaeza** [comment]
Unless you get more information with detailed steps to reproduce the problem, I'm afraid I don't get it.

**Comment by muhammadnaeem786** [comment]
Dear Pedrobaeza when i am exporting  general ledger report setting partner filters in drop down data is not sorted in rec_name manner it is sorted with respect to code you can see in general_ledger.py file due to this debit , credit and cumul.bal. columns records also not sorted. you can see in attached screen shot given below.record A82 should be come after A81 also it debit , cr and cumul. bal .
![Screenshot from 2021-11-15 12-54-04](https://user-images.githubusercontent.com/84784929/141743051-1e35330b-16fa-462b-9675-dcc758ede0c1.png)
ow

**Comment by pedrobaeza** [comment]
Yes, but we need to steps to reproduce it in a standard environment. I have never observed such problem till now.

**Comment by muhammadnaeem786** [comment]
ok no problem i have sorted in my local system but i have to work more for cumul.bal. columns. thanks for your response.

**Comment by muhammadnaeem786** [comment]
Dear pedrobaeza hopefully you have noted this issue.i think this problem should be fixed for standard environment such as for v13 or above.thank you very much for your immediate response.

**Comment by pedrobaeza** [comment]
No, I'm afraid not. I don't get the problem and there's no steps to reproduce it in a standard environment with reproducible data.
