### ISSUE TITLE
[14.0] [partner_statement] Exhange gain/loss should not appear on statements

### ISSUE THREAD

**Issue by LGodoo** [OCA/account-financial-reporting#852]
## Module
partner_statement

## Describe the bug
A customer we deal with in Euro. Our reporting/company currency is USD.
If we issue invoices in Euro and record payment in Euro a realised forex is accounted for.

If we generate the receivable statement it is in Euro but it includes the forex gain/loss that was booked in our ledger in USD with the euro sign in front.

As a result the balance in the statement is not zero and the customer/partner will wander what this small amounts are.
The partner should not see forex gain/losses in his Statement. They do not consern them.

## To Reproduce
**Affected versions**:
14.0

1. Company curency is USD
2. Activate multi-currencies, then Euro and fill in the rates
2. Generate invoice in Euro
3. Record payment in Euro at a different date
2. Confirm in general ledger that an exchange gain or loss was booked
3. Generate Activity Statement for this partner

**Expected behavior**
Expected to see the statement in Euro with 2 entries:

1.  The invoice i.e. Dr Euro 100
2. The payment i.e. Cr Euro 100
3. Balance is zero

**Comment by nicolas-tg** [comment]
I am facing the same issue in version 15.

**Comment by AndrzejGerasimukARCHIMEDES** [comment]
We have the same problem i PLN
I have check the code and i think, tat problem is in _display_outstanding_lines_sql_q1 method.

In line 38 system check only balance >= 0
![obraz](https://github.com/OCA/account-financial-reporting/assets/112691008/b7621b8e-07af-4f7d-a5c6-f34d690efa8e)

But in our case then account.move.line has ballance (in system currency) equal 0 and ammount_currency have proper value - positive or negative. 
So in my opinion proper case condition must be:

>             CASE WHEN l.balance > 0.0  or (l.balance = 0.0 and l.amount_currency > 0.0)
>                 THEN l.amount_currency - sum(coalesce(pd.debit_amount_currency, 0.0))
>                 ELSE l.amount_currency + sum(coalesce(pc.credit_amount_currency, 0.0))
>             END AS open_amount_currency,
