### ISSUE TITLE
[14.0] partner_statement shows entries with -0 and 0

### ISSUE THREAD

**Issue by seancallahan88** [OCA/account-financial-reporting#860]
## Module
The name of the module that has a bug.
partner_statement
## Describe the bug

On the outstanding statement, journal entries can show with -0 and 0 that are out of scope of the report (ie they are already paid off). These should not show on the outstanding report at all as they are already paid off. These journal entries are already reconciled but they all have in common that they are partially reconciled with two or more invoices. 

Bit more information - 

Report done on odoo 14e on odoo.sh

See example

![image](https://user-images.githubusercontent.com/11476707/152911374-2ecd2a61-16bf-4d11-a7f8-326e6ead2adc.png)

**Additional context**

There is some link to invoices that are paid with multiple payments and related bank statements.

These erroneous lines do not show on the activity statement - they appear to be only on the outstanding report.

**Comment by gdgellatly** [comment]
@seancallahan88 more likely this is a migration error of the reconciled field. I've seen it before in historic data. You can easily test by essentially replicating new data.

**Comment by sergiuga** [comment]
I have the same problem on a fresh Odoo 14 install. 
Only some of the reconciled records are shown in report, not all of them.

**Comment by gdgellatly** [comment]
@sergiuga You are referring to a different issue than this issue report, this is about 0.00 balances.
