### ISSUE TITLE
[14.0] account_financial_report: trial balance: issue with current year earnings account when filtering on some accounts

### ISSUE THREAD

**Issue by alexis-via** [OCA/account-financial-reporting#870]
On a trial balance, when you filter on some accounts (including the current year earning account), the line for the current year earning account is wrong (bad initial balance and ending balance).

Here is a way to reproduce the problem on a demo DB:
1) Create a customer invoice in 2021 with total amount without taxes of 1000 €
2) print a trial balance for year 2022 : the current year earning account will have:
initial balance: -1000
debit: 0
credit: 0
period balance: 0
ending balance: -1000
3) print a trial balance for year 2022 with filtering on a few accounts (via field "account_ids" of the wizard) including the current year earning account:
initial balance: 0
debit: 0
credit: 0
period balance: 0
ending balance: 0
Note that, on a real DB with real data, the initial balance has a (wrong) not null value when filtering on some accounts.

**Comment by pedrobaeza** [comment]
No easy solution for this one. Maybe not show 129 row saying you need to select all accounts?
