### ISSUE TITLE
[14.0] partner_statement wrong beginning balance in Partner Activity Statement report

### ISSUE THREAD

**Issue by sergiuga** [OCA/account-financial-reporting#872]
## Module
partner_statement

## Describe the bug
When selected a certain period for Partner Statement (usualy last ... months), the beginning balance is wrong. 

## To Reproduce
**Affected versions**: 14.0

1. Select a period for Partner Statement Activity report (e.g. last 2 months) - wrong initial balance (wrong.jpg)
2. Select the period from the beginning of the activity with the partner - the balance at the same date is correct (right.jpg)

**Expected behavior**
Have the same balance - the right one!

**Additional context**
Fresh Odoo 14 install. Additional relevant modules installed: om_account_accountant, om_account_standard _report, account_reconciliation widget
![wrong](https://user-images.githubusercontent.com/28352258/162562937-afea0ca4-b6c1-414e-b4ea-af4112dd16d5.png)
![right](https://user-images.githubusercontent.com/28352258/162562939-c1c6bcc7-578e-426c-a1c5-2155bbb66878.png)

**Comment by gregorygregoriades** [comment]
Hello, I have this issue as well. Have you found a solution by any chance?

**Comment by gdgellatly** [comment]
Hi,

This has been reported a few times, and I have seen it myself. I am not convinced it actually is a bug but rather a data migration error where reconcile flags were not migrated correctly. Certainly every time I have come across it, that was the cause, the change in how the reconcile flag is set between v13 and v14. What we need is not screenshots but clear steps to reproduce on fresh data.

**Comment by gregorygregoriades** [comment]
Hello,

Thanks for your reply, we tried it on a fresh database with new data, not migrated and we are still having the same issue.


________________________________

**Comment by gdgellatly** [comment]
@gregorygregoriades 

Steps to reproduce! It is not enough to say it is broken, we need to be able to make it break. 

Screenshots of output are rarely of any use.
