### ISSUE TITLE
[13.0+14.0] mis_template_financial_report: Earnings current year in profit?

### ISSUE THREAD

**Issue by victoralmau** [OCA/account-financial-reporting#888]
Balance of "_Current Year Earnings_" account (type = `account.data_unaffected_earnings`) is currently displayed in _Profit_: https://github.com/OCA/account-financial-reporting/blob/13.0/mis_template_financial_report/data/mis_report_kpi.xml #L22

IMO move lines from `account.data_unaffected_earnings` type should not be included. What do you think?

Ping @pedrobaeza @StefanRijnhart 
@Tecnativa TT37837

**Comment by pedrobaeza** [comment]
Yeah, I think so. The journal items in this account are the distribution of the benefits, so it shouldn't go anywhere in the P&L. What do you think, @StefanRijnhart ?

**Comment by StefanRijnhart** [comment]
I'm sorry to say that it is not clear to me how these accounts are supposed to be used exactly. https://www.odoo.com/documentation/15.0/applications/finance/accounting/taxation/fiscal_year/close_fiscal_year.html?highlight=current%20year%20earnings implies the account type belongs on the balance sheet. Maybe the original author @hbrunn wants to chip in as well?

**Comment by hbrunn** [comment]
that's one of the types I didn't really know where it should go, so go ahead and put it where it belongs

**Comment by pedrobaeza** [comment]
Let me explain: that one shouldn't go to anywhere.

It's an special type that is recognized by Odoo enterprise reports or OCA financial reports to accumulate all the balances from incomes and expenses to show the running profit & losses. Only one account can be assigned to that type. The only moves that are accounted to that account are the redistribution of the benefits to other part.

With one example in Spanish accounting: you have the account 129000 on that type. Expenses are accounts starting with 6, and incomes accounts starting with 7. Imaging the activity has started on 2021 with 2000 € of incomes, and 1500 € of expenses. If you get a trial balance for 2021, you will see on such account the resulting balance of 7 + 6, having 500 € of benefits. This comes in the code for computing the trial balance (not any logic tied to `balance` field on the account). Then, you retire such benefits to be paid to the owners, so you make a journal entry moving 500 € from 129 to the account that represents the payment. Doing now a trial balance of 2022, you will have an starting balance of 0. Obtaining a P&L mis reports should show such 500 €, not 0 €.

I hope this clarifies a bit.

**Comment by HaraldPanten** [comment]
I agree with Pedro. Good explanation.

**Comment by hbrunn** [comment]
yes, thanks. I'm not proud of it, but my grasp of accounting stuff is somewhat lacking

**Comment by pedrobaeza** [comment]
No worries. We will do the PR removing the type.

**Comment by pedrobaeza** [comment]
Already handled.
