### ISSUE TITLE
[14.0][account_financial_report] general ledger - Group By None show empty details on receivable/payable account (with video demo on runboat)

### ISSUE THREAD

**Issue by andhit-r** [OCA/account-financial-reporting#944]
## Module
account_financial_report

## Describe the bug

No receivable/payable detail data display when Group By None applied on general ledger report

## To Reproduce

Video to reproduce on runboat https://youtu.be/1KOhXGJjwv8

**Affected versions**: 14.0

1. View/export general ledger with None group by

**Expected behavior**
Detail data should be shown

**Comment by HaraldPanten** [comment]
@pedrobaeza Did you have a look at that? I realised I have the same issue.

**Comment by HaraldPanten** [comment]
@victoralmau

**Comment by pedrobaeza** [comment]
Fixed in https://github.com/OCA/account-financial-reporting/pull/955

**Comment by HaraldPanten** [comment]
THX @pedrobaeza !!

**Comment by andhit-r** [comment]
Thx @pedrobaeza
